### ISSUE TITLE
[BUG] App does not automatically connect to treadmill

### ISSUE THREAD

**Issue by CharRich** [cagnulein/qdomyos-zwift#1968] opened 2024-01-08 11:25 UTC
When opening the QZ app it does not automatically connect to my treadmill.

**To Reproduce**
1. Ensure treadmill is switched on. 
2. Ensure both Bluetooth and WiFi are operational on treadmill 
3. Open QZ app
4. App endlessly searches for devices. Finds other devices, such as Apple Watch, IPad, Samsung TV etc, but does not find and/or link to NordicTrack 1750 (2019 model) treadmill.  

N.B. Have restarted treadmill and behaviour does not change. 

Treadmill is connected to WiFi and can successfully run iFit programmes etc over iFit. Have also downloaded QZ companion app to the treadmill using the inbuilt browser, so treadmill WiFi is operational. 
Have connected Bluetooth audio to the treadmill to test the treadmill Bluetooth, and this is also operational with no issues.

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS
 - Version: 17.2.1

**Comment by cagnulein** [comment] 2024-01-08 12:25
hi could you please attach a debug log https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F ?

Thanks

**Comment by CharRich** [comment] 2024-01-08 13:33
Hi,

I don’t think there is a debug log, as technically there wasn’t an error.
The screen just continues to search for my treadmill.

I tried again, as you requested, but all I can find in the files are empty
graphs of cadence, heart-rate etc. No debug logs. Which makes sense, since
there wasn’t an error message. The opening screen just continuously loops
through all the devices it can find, but never shows the treadmill and
never settles on anything.

**Comment by cagnulein** [comment] 2024-01-08 13:48
the debug log it's in order to understand if you set the ip in the right place in the settings. What you are describing is likely that you didn't set the ip in the Nordictrack 2950 setting. So please share a debug log I can verify it

**Comment by cagnulein** [comment] 2024-01-11 09:46
@CharRich any news?

**Comment by CharRich** [comment] 2024-01-17 08:39
Hi,I actually did get it to connect by reading through some of the other bug reports here and seeing that a common recommendation was to reboot the treadmill. So I did that and it then connected no problem. I’ve been using the treadmill pretty much daily with Zwift since then, but unfortunately another issue has occurred this morning. Zwift connects to the app, but the app does not register movement when the treadmill is moving. This is possibly another bug report though so I will close this one and open a separate report with details of that issue. Sent from my iPadOn 11 Jan 2024, at 09:46, Roberto Viola ***@***.***> wrote:﻿
@CharRich any news?

**Comment by CharRich** [comment] 2024-01-17 09:18
QZ is on my iPhone 13 Pro Max, Zwift is on my iPad Pro. It was working perfectly until this morning and nothing about my set-up has changed in that time. Debug log attached. <debug-Wed_Jan_17_08_23_59_2024.log>Sent from my iPhoneOn 17 Jan 2024, at 09:02, Roberto Viola ***@***.***> wrote:﻿
where are you using qz? where zwift? they must running on different devices

**Comment by cagnulein** [comment] 2024-01-17 10:01
hi i can't see the debug log, you have to upload it from the github interface directly. anyway if you didn't change nothing on the qz side it could be a zwift issue. Try to reboot both devices. There a lot of messages on the zwift forums about this kind of issues with all the trainers all the days :)

**Comment by CharRich** [comment] 2024-01-17 12:32
Hi, 
I’d agree there are a lot of issues with the Zwift app (using my Apple Watch as a heart rate monitor is an issue, for example), but this particular issue is definitely a QZ and/or treadmill one. The QZ app does not register treadmill movement, even when I don’t have the Zwift app open. So the treadmill is moving, but on the QZ app everything says 0:00. 

I’ve added the debug log here.

[debug-Wed_Jan_17_08_23_59_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13963196/debug-Wed_Jan_17_08_23_59_2024.log)

**Comment by cagnulein** [comment] 2024-01-17 12:37
hah ok, I didn't understand. yes there is no activity from the qz companion app (the companion is sending empty messages). This means that the qz companion app is not able to get the metrics from the treadmil. So please follow this and report me back which was the output and then I will help you https://github.com/cagnulein/QZCompanionNordictrackTreadmill/wiki/Troubleshooting#i-installed-the-companion-app-but-i-cant-see-any-data-on-my-qz-app

**Comment by CharRich** [comment] 2024-01-17 13:14
So I’ve done all that now. Reset, redownloaded, retried and still getting this issue. 

What I don’t understand is, it’s been working for a week and randomly stopped. 

Debug report attached. 

[debug-Wed_Jan_17_12_40_41_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13963623/debug-Wed_Jan_17_12_40_41_2024.log)

**Comment by cagnulein** [comment] 2024-01-17 13:21
@CharRich did you do a factory reset and DON'T update the ifit app? That's the key thing. The treadmill stopped to send the metrics because ifit is closing the doors to qz. So the only way is to don't update ifit. Otherwise we have to go with the grand tour trick https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559

**Comment by CharRich** [comment] 2024-01-17 13:26
Hi. Yes, I hit ‘later’ when asked if I wanted to update the app, so I’m not running the updated version of iFit. I’ll try setting the treadmill as the bike on the app and see what happens.

**Comment by cagnulein** [comment] 2024-01-17 13:28
nope that setting is not about this issue. We need to understand why the companion stopped to work.
Please generate a log from the companion while you're doing a workout https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-debug.bat

**Comment by CharRich** [comment] 2024-01-17 13:40
Sorry, not quite sure what you’re asking me to do now. I understand nothing on that link! 

You want something other than a debug report when I do a workout?

**Comment by cagnulein** [comment] 2024-01-17 13:46
ok :) i thought you already used adb for installing the qz companion, didn't you?
What I need to understand the issue is a debug from the companion directly. That batch file will do it automatically.
You can run the whole install package for adb here https://github.com/cagnulein/QZCompanionNordictrackTreadmill/archive/refs/tags/3.3.27.zip

**Comment by CharRich** [comment] 2024-01-17 14:01
Oh, I see. No, I downloaded it using the treadmill browser, so I just plugged in the url and everything happened on its own. 😁 Thanks for the additional info.Sent from my iPhoneOn 17 Jan 2024, at 13:46, Roberto Viola ***@***.***> wrote:﻿
ok :) i thought you already used adb for installing the qz companion, didn't you?
What I need to understand the issue is a debug from the companion directly. That batch file will do it automatically.
You can run the whole install package for adb here https://github.com/cagnulein/QZCompanionNordictrackTreadmill/archive/refs/tags/3.3.27.zip

**Comment by cagnulein** [comment] 2024-01-17 14:02
ok so follow this way to collect the adb logs

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 17 gen 2024 alle 15:01 CharRich ***@***.***> ha
scritto:

**Comment by CharRich** [comment] 2024-01-17 15:28
Done. Incredibly frustratingly… it’s working now. Treadmill is currently running and QZ app is picking up all the relevant information. 

I don’t know why it is suddenly working though. Series of events since last message: 

- Downloaded abd package to laptop,
- Clicked and ran abd-debug (with treadmill off and QZ app closed, because I didn’t know what I was doing).
- Realised I should probably have the treadmill on while I do this, so opened the app and turned the treadmill on… only to find it is now responding as normal.
- Ran the abd-debug file anyway - I have no idea where these reports are stored though once generated…

**Comment by cagnulein** [comment] 2024-01-17 15:48
> * Ran the abd-debug file anyway - I have no idea where these reports are stored though once generated…

in the same folder of the btach file



> I don’t know why it is suddenly working though. Series of events since last message:

i know it, because via adb, it does more than simply installing the apk.

Ok anyway let's see if it's consistent now :)

**Comment by CharRich** [comment] 2024-01-20 12:18
It didn’t stay consistent. Went to run this morning and the same thing happened. I did all the previous steps; reset my treadmill, didn’t update iFit, this time I used adb to install the companion app… nothing. Ran a debug while the treadmill was on (last time it started working after running the debug, but not this time). 

You say the debug should be stored in the same folder as the batch file… what is it called? I can’t find any of the files other than what was originally installed on my laptop with the zipped install folder.

**Comment by CharRich** [comment] 2024-01-24 16:09
Hi there. Just wondering if you have had a chance to look in to this some more.

**Comment by cagnulein** [comment] 2024-01-24 16:09
the problem is that adb is off i guess from what you're saying. so also the adb batch file for log doesn't work.
Are you sure ADB is enabled?

**Comment by cagnulein** [comment] 2024-01-24 16:10
I didn't receive the previous notification, sorry

**Comment by cagnulein** [comment] 2024-01-24 17:40
i was meaning adb in the fitness device itself.

the error about adb is because you have to run the batch file from the same path where adb is.

share me a screenshot of what you are doing and i will tell you which is the issue

**Comment by CharRich** [comment] 2024-01-24 17:56
The USB debug is on, is this what you’re talking about? 

I will send you a screenshot.

**Comment by cagnulein** [comment] 2024-01-24 18:35
if it's so adb debug batch should work too

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 24 gen 2024 alle 18:56 CharRich ***@***.***> ha
scritto:

**Closed** 2024-02-16 01:08 UTC
Labels: bug, wontfix

**Comment by cagnulein** [comment] 2024-02-16 03:31
@CharRich any news?
