### ISSUE TITLE
[BUG] Settings page is too wide on some device on portraid mode

### ISSUE THREAD

**Issue by ptrinephi** [cagnulein/qdomyos-zwift#146] opened 2021-01-27 08:28 UTC
Beta 2.3.1, S9 and S9+
Settings page is too wide when viewed in portrait mode.  The switches on the right bleed outside of the screen making it difficult to swipe on/off.

**Comment by cagnulein** [comment] 2021-01-27 08:29
duplicate of #105

**Comment by ptrinephi** [comment] 2021-01-27 08:37
#105 is a different issue, #105 is going from portrait to landscape.  This issue is on the settings page, see right side of screen on image
![Screenshot_20210127-003638](https://user-images.githubusercontent.com/6604478/105965094-dcdef880-6037-11eb-8974-c8946c62952b.jpg)

**Comment by cagnulein** [comment] 2021-01-27 08:40
ops sorry, you're right!

**Comment by cagnulein** [comment] 2021-03-18 06:24
finally fixed in the version 2.4.27 and above!

**Closed** 2021-04-07 09:06 UTC
Labels: UI, android, bug, settings
