### ISSUE TITLE
QZ does not control inclination for a BXT216 Bowflex Treadmill[BUG]

### ISSUE THREAD

**Issue by hpcolus** [cagnulein/qdomyos-zwift#2202] opened 2024-03-10 02:55 UTC
**Desktop 
 - OS: Wondows 11 
 -  - Version 22H2

**Smartphone 
 - Device: Pixel 6
 - OS: Android
 - Version: 14

**Append a debug log**

I would like to use this feature in Zwift to send back to the TM the inclincaion of the walk.  Could this be a limitation of BXT216?

**Comment by cagnulein** [comment] 2024-03-10 07:40
Bowflex devices don't have speed or control from any external app if it's what you mean.

Let me know if you have any other questions

**Comment by hpcolus** [comment] 2024-03-10 14:36
Is this somethong tha can be done with soldering a bluetooth module?    On Sunday, March 10, 2024 at 03:40:59 AM EDT, Roberto Viola ***@***.***> wrote:  
 
 


Bowflex devices don't have speed or control from any external app if it's what you mean.

Let me know if you have any other questions

**Comment by cagnulein** [comment] 2024-03-10 14:38
yes a modbus bluetooth module. i already did the code on qz for this! let
me know if you are interested
https://amzn.eu/d/781H2va


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 10 mar 2024 alle 15:37 hpcolus ***@***.***> ha
scritto:

**Comment by hpcolus** [comment] 2024-03-10 14:46
I am interested!!!

**Comment by cagnulein** [comment] 2024-03-10 15:11
ok buy it and we will setup it!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 10 mar 2024 alle 15:46 hpcolus ***@***.***> ha
scritto:

**Comment by hpcolus** [comment] 2024-03-10 19:18
The link provide is not available in Amazon USA.  Does this work?  DC 7-30V 8 Channel Modbus RTU Relay Module RS485 TTL UART Communicate Board 8 Way Output Input for Arduino Power Control

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
DC 7-30V 8 Channel Modbus RTU Relay Module RS485 TTL UART Communicate Bo...

DC 7 -30V 8 Canali Modulo Relè Modbus RTU RS485 TTL UART Comunicare Bordo 8 Vie di Uscita di Ingresso per Arduin...
 |

 |

 |




    On Sunday, March 10, 2024 at 11:11:48 AM EDT, Roberto Viola ***@***.***> wrote:  
 
 

ok buy it and we will setup it!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 10 mar 2024 alle 15:46 hpcolus ***@***.***> ha
scritto:

**Comment by cagnulein** [comment] 2024-03-10 19:19
yes remember that you also need a usb RS485 serial port

**Comment by hpcolus** [comment] 2024-03-20 21:42
Hi, I got the board and the usb serial port.  What is next?

**Comment by cagnulein** [comment] 2024-03-20 21:43
Did you already di the wires to the buttons?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 20 mar 2024 alle 22:42 hpcolus ***@***.***> ha
scritto:

**Comment by hpcolus** [comment] 2024-03-21 13:52
No.  I do not have any steps or diagram that shows me from where to where to connect nor how many wires.  If I understood  correctly you want me to connect some  wires to each button on the treadmill, up and down for the incline and speed, and where in the board they go? Then what? Do you have somewhere the steps or a video?

**Comment by cagnulein** [comment] 2024-03-21 14:22
no @hpcolus unfortunately i don't have any because I didn't myself. The electrical concept is simple: you have to connect each relay to 1 button of the treadmill. so 1 relay to speed up, 1 relay to speed down, 1 relay to inclination up, 1 relay to inclination down.

the purpose of this is that qz, via the modbus board, can increase and decrease speed and inclination. If you want you can write here https://github.com/cagnulein/qdomyos-zwift/issues/525 there are other guys that did this with qz (they used the gpio from the raspberry but the concept is the same)

**Comment by hpcolus** [comment] 2024-04-06 22:29
I have all the connections ready (speed up, down) inclination (up, down) serial, etc.  I can manually send the singnal for speed and inclination, up or down with a splitter I attached to the treadmill.  
For the modbus board, is there any particular order to connect to the relays?  There are 8 relays in the board, which is the order of connections (speed up, speed down, inclination up, inclination down)? Does it matter?

**Comment by cagnulein** [comment] 2024-04-07 01:38
Yes this is the order 

const uint8_t OUTPUT_SPEED_UP = 0;
    const uint8_t OUTPUT_SPEED_DOWN = 1;
    const uint8_t OUTPUT_INCLINE_UP = 2;
    const uint8_t OUTPUT_INCLINE_DOWN = 3;
    const uint8_t OUTPUT_START = 4;
    const uint8_t OUTPUT_STOP = 5;

Do you have a windows pc? Connect it to Com4 and we are good to go!

**Comment by hpcolus** [comment] 2024-04-07 07:06
Windows PC now connected to COM4 (USBC to RS485) Driver working OK
Nothing works, no inclination no speed control.  I do not see the blinking inclination in the QZ tile or blinking the speed icon in the QZ tile when Swift runs.  In QZ the speed matches the treadmill speed.  The inclination matches the treadmill inclination if I increase or decrease manually the inclination with the button on the treadmill.   Am I missing any step on Zwift or any setting in QZ?

**Comment by cagnulein** [comment] 2024-04-07 07:34
did you download the right branch exe file? a debug log is needed to understand your setup :) 

today is family day, i will check your case tomorrow

**Comment by hpcolus** [comment] 2024-04-13 04:54
What do you mean by "branch exe file"?  When I provided my set up above, you said everything was OK and good to go. I am attaching the log from the QZ android app
[debug-Sat_Apr_13_00_27_27_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14965313/debug-Sat_Apr_13_00_27_27_2024.log)

**Comment by cagnulein** [comment] 2024-04-13 05:04
the gpio implementation is an separate branch. you have to use this zip https://github.com/cagnulein/qdomyos-zwift/actions/runs/8099706528/artifacts/1286743578

then set the com as a com4 and provide me a debug log and i will help you.

**Comment by hpcolus** [comment] 2024-04-13 05:30
Does this means, I do not have to run the android QZ app?  Only the windows exe file, plus zwift?

**Comment by cagnulein** [comment] 2024-04-13 05:55
exactly, you can run qz and zwift on the same pc also

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 13 apr 2024 alle 07:31 hpcolus ***@***.***> ha
scritto:

**Comment by hpcolus** [comment] 2024-04-13 05:56
Where do I get the log file.  The windows app becomes unresponsive after detecting the bowflex.

**Comment by cagnulein** [comment] 2024-04-13 06:07
are you able to pair the treadmill with the windows bluetooth settings? if
so i can fix this

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 13 apr 2024 alle 07:56 hpcolus ***@***.***> ha
scritto:

**Comment by hpcolus** [comment] 2024-04-13 06:18
![image](https://github.com/cagnulein/qdomyos-zwift/assets/104551107/8eaa9102-8c70-45af-a29d-a8c17d53a699)
Zwift is able to pair with the treadmill.  Is this what you mean?

**Comment by hpcolus** [comment] 2024-04-13 06:20
![image](https://github.com/cagnulein/qdomyos-zwift/assets/104551107/69847a67-438c-41df-a1f6-dfe0c63bd016)

**Comment by cagnulein** [comment] 2024-04-13 06:20
no i mean the bluetooth windows settings, where you can pair the mouse or headphones for example

**Comment by hpcolus** [comment] 2024-04-13 06:30
No.  Windows does not list the treadmill when I scan it as "add device"  Keep in mind that zwift was able to see it and connect to it

**Comment by hpcolus** [comment] 2024-04-13 06:54
Is listed now under devices,
![image](https://github.com/cagnulein/qdomyos-zwift/assets/104551107/55b46763-a673-442a-b207-859479aeb318)

**Comment by hpcolus** [comment] 2024-04-13 07:22
Now the QZ windows app runs and shows the speed an inclination on the tiles. But after a few minutes I got a message to 'join the patreon sponsorship'  Does this mean the full inclination (when it works) is only available with a subscription?

**Comment by cagnulein** [comment] 2024-04-13 08:17
yes full inclination is available with a patreon membership. there is a
high workload under this.

i'm with my family now, i will be available on monday!

have a nice weekend!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 13 apr 2024 alle 09:22 hpcolus ***@***.***> ha
scritto:

**Comment by cagnulein** [comment] 2024-04-14 06:29
@hpcolus I unlock the version for you. Be sure to set the patreon email all lower case to the qz email setting and press OK.

I also created a new version for you this morning https://github.com/cagnulein/qdomyos-zwift/actions/runs/8678624419/artifacts/1411972582 that will directly connect to the com4 

share me a log so i can check if the modbus communication is working properly. one question: did you buy exactly the modbus peripheral that i show in the link above? if so we should be ready to have it running with this build!

let me know

**Comment by hpcolus** [comment] 2024-04-16 01:41
The relays work, albeit manually.  Using the qz windows app, I am able to increase/decrease speed and inclination pressing + or - in the corresponding tile for speed or inclination.  However there are **THREE** issues
1.  The speed and inclination values that is on the treadmill does not synchronize with the value on the QZ app or Zwift.  With the android app I have no problem, since the speed and inclination on the treadmill always match with the android app.
2. I Zwift, I see the wahoo tread 003 that I connected to.  Again, the speed that it shows is the wrong speed from the QZ windows app, not from the real speed in the treadmill.  Changes in the inclination in Zwift are not sent do the QZ windows app or the treadmill
3. The COM4 was not stable.  Sometimes I lost responsiveness.


[debug-Mon_Apr_15_21_36_17_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14985859/debug-Mon_Apr_15_21_36_17_2024.log)

**Comment by cagnulein** [comment] 2024-04-16 09:22
> 1. The speed and inclination values that is on the treadmill does not synchronize with the value on the QZ app or Zwift.  With the android app I have no problem, since the speed and inclination on the treadmill always match with the android app.

yes because in this way QZ is getting the metrics from the modbus directly. in order to do so you have to tell me:
1. which is the speed value when you press start on the treadmill? Actually it's 0.8 km/h
2. which is the increment of the speed when you hit the plus button? Actually it's 0.1 km/h



> 2\. In Zwift, I see the WAHOO TREAD 00033 that I connected to.  Again, the speed that it shows is the wrong speed from the QZ windows app, not from the real speed in the treadmill.

same as 1.



> 2\. Changes in the inclination in Zwift are not sent do the QZ windows app or the treadmill

you have to set the zwift username and password in the qz app in order to have this



> 3\. The COM4 was not stable.  When I press consecutively the speed + many times I lost responsiveness with the treadmill

disable the bluetooth on the pc since we don't need anymore for this. in the log the serial port is ok, are you referring to another session?

Let me know!

**Comment by hpcolus** [comment] 2024-04-17 02:42
No changes at all. Here is what happened.  
I cannot disable the BLUETOOTH as you suggested because qz app crashed upon start.  I turned on the BT, then after starting the QZ app in windows I turned the Bluetooth off.
1. When I press start the value on the treadmill is 1 mi/hr.  Qz screen shows 0.5 mi/hr and Zwift shows also 0.5 mi/hr. And it is not updated after starting the treadmill.
2. The increment of speed with the plus button is 0.1 mi/hr.  But when I press the plus button, the treadmill increases the speed but NO changes are reflected in QZ windows app.
3.  When I press consecutively the speed + many times I lost responsiveness with the treadmill in the SAME session.

Somehow the windows app is not reading the actual speed and the actual inclination on the treadmill.  In addition, Zwift is not controlling the treadmill at all.
[debug-Tue_Apr_16_22_27_44_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15004845/debug-Tue_Apr_16_22_27_44_2024.log)

**Comment by hpcolus** [comment] 2024-04-18 02:08
Hi Roberto

1. The file to download is huge.  More than 1GB!
2. It took 20 min to decompress as it is doble zipped
3. The bluetooth issue was solved when the BT is deactivated
4. Speed is defalted to 1mi/hr
5. However, the speed value on the QZ tiles does not match with the speed value on the treadmill when I press the plus button.
6. I did not see the inclination tile on this version


[debug-Wed_Apr_17_21_57_46_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15018961/debug-Wed_Apr_17_21_57_46_2024.log)

**Comment by cagnulein** [comment] 2024-04-18 07:42
> Hi Roberto
> 
> 1. The file to download is huge.  More than 1GB!

yeah because I sent you the full package with also the OCR system that it's for auto inclination and auto speed on zwift. i will send you back the smallest one the next time

> 2. It took 20 min to decompress as it is doble zipped.
> 3. The Bluetooth issue was NOT solved when the BT is deactivated.  If BT is off, QZ does not start

yes you can leave it enabled now. i removed the BT part directly in the code.

> 4. Speed is defaulted to 1mi/hr  After I paused it with the QZ tiles, it was defaulted to 0.5mi/hr

got it. fixed in the next one

> 5. However, the speed value and inclination on the QZ tiles do not match with the speed value and inclination on the treadmill when I press the plus button of the speed or inclination

which is the grade of changing of the inclination every time you press the inclination button on the treadmill? 1% or 0.5%? now qz is thinking is 0.5%

for the speed I guess I found the issue and I'm sending you another one later. Send me a video showing treadmill and qz if the error persists.

> 
> The android app shows the right speed and inclination only when I connect in Zwift using the phone name 'PhP'. If I select on Zwift WAHOO TREAD 0003, which I think is the wifi name coming from the QZ android app, it does not always work.

wahoo tread uses wifi, maybe the router is filtering out the frames. anyway if it's working with PhP, use this one, no problem using this.

> 
> I do not know what setting I changed later that now QZ appp does not wants to start. How can I reset the settings?

you can clear the data on the android app from the android settings.

**Comment by cagnulein** [comment] 2024-04-18 08:08
new build https://github.com/cagnulein/qdomyos-zwift/actions/runs/8734194577/artifacts/1424982925

**Comment by hpcolus** [comment] 2024-04-18 14:29
`you can clear the data on the android app from the android settings.`
It is the qz windows app that does not go beyond the main screen.  Android app works fine.  How do I reset the settings for the QZ windows app?

[debug-Thu_Apr_18_10_21_15_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15026280/debug-Thu_Apr_18_10_21_15_2024.log)

![image](https://github.com/cagnulein/qdomyos-zwift/assets/104551107/dfecef38-f94f-42bb-afbd-dd7d8e5a9e62)

**Comment by cagnulein** [comment] 2024-04-18 15:06
new build https://github.com/cagnulein/qdomyos-zwift/actions/runs/8739952329/artifacts/1426335902

**Comment by hpcolus** [comment] 2024-04-19 18:18
After the new build.  Let's concentrate on making sure the speed and inclination matches between the treadmill and the windows QZ app (running on the same laptop)  Let's defer the COM4 auto control for later
Still the inclination and speed does not match between the treadmill and the windows QZ Zwift.  As I mentioned to you, with the android app, both speed and inclination are synchronized. In the video link I show the lack of synchronization between the treadmill and QZ Windows app.

[https://youtu.be/j6bbTTijH8E](url)

**Comment by cagnulein** [comment] 2024-04-19 18:34
do you have also the debug log of this run?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 19 apr 2024 alle 20:19 hpcolus ***@***.***> ha
scritto:

**Comment by hpcolus** [comment] 2024-04-22 03:06
I respectfully disagree.  It should have the same functionality as the QZ android.  With the android app, once I press the plus or minus button in the treadmill the android app updates the value of inclination or speed.  It would be difficult with a laptop trying to press the tiny plus or minus buttons on the screen while walking.
I am attaching you again another log.  Let me know if you can have the same basic functionality in windows as the one in android.  
[debug-Sun_Apr_21_21_51_26_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15056699/debug-Sun_Apr_21_21_51_26_2024.log)

**Comment by cagnulein** [comment] 2024-04-22 03:17
i mean it's the current stage of development, adding the bluetooth connection along with the modbus communication it's something that i have to develop.

i will do in the next days.

consider that's will be a huge task (qz is only an hobby for me, i have a regular job) so im trying to do my best here

**Comment by cagnulein** [comment] 2024-04-22 08:06
ok i did a first frankestain here (modbus + bluetooth) https://github.com/cagnulein/qdomyos-zwift/actions/runs/8780612156 (at the bottom of the page you will find the download link)

of course I didn't try anything, so put me a debug log if it doesn't work as expected

What I'm expecting to see is:
- speed and inclination reading from bluetooth
- speed and inclination control to modbus

Let me know!

**Comment by hpcolus** [comment] 2024-04-23 01:12
I did not see the link you mentioned
I got this screen

![image](https://github.com/cagnulein/qdomyos-zwift/assets/104551107/8f335242-8f37-45cb-a470-4201362cdc67)

**Comment by cagnulein** [comment] 2024-04-23 09:01
this one https://github.com/cagnulein/qdomyos-zwift/actions/runs/8797412100/artifacts/1438700541

**Comment by hpcolus** [comment] 2024-04-25 01:43
- Device manager in windows tells me that COM4 is working.
- QZ app in windows, pressing plus and minus in the ties of inclination and speed has NO effect on the treadmill.
- Pressing up and down in the treadmill for speed or inclination does NOT synchronize with QZ windows app


[debug-Wed_Apr_24_21_38_18_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15102827/debug-Wed_Apr_24_21_38_18_2024.log)

**Comment by cagnulein** [comment] 2024-04-25 06:30
hi @hpcolus in this log the issue is that you have the fake treadmill setting in the experimental settings turned on. disable it and restart qz and show me a new debug log if it doesn't work, let me know

**Comment by hpcolus** [comment] 2024-04-26 01:11
We are finally going in the right direction.
-The treadmill synchronizes with the windows qz app for speed and inclination.  I presssed the plus or minus button of the speed and inclination of the treadmill and QZ synchronized the values
- I was able walk a little bit with zwift matching speed on the treadmill
The following are the issues I identified:
- The windows app quitted unexpectedly a couple of times
- When I press the plus button once for inclination on the QZ, the treadmill increased the inclination 3x higher 
- The minus button of the QZ app for inclination INCREASES the inclination
I am attaching two logs

[debug-Thu_Apr_25_21_01_55_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15123941/debug-Thu_Apr_25_21_01_55_2024.log)

[debug-Thu_Apr_25_20_59_31_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15123943/debug-Thu_Apr_25_20_59_31_2024.log)

**Comment by cagnulein** [comment] 2024-04-26 07:03
ok i guess i fixed the plus and minus inclination issue (i'm attaching the new build in some minutes). About the crashes: what do you see? is windows reporting any issue? maybe you can show me a screenshot of the error?

**Comment by cagnulein** [comment] 2024-04-26 07:28
https://github.com/cagnulein/qdomyos-zwift/actions/runs/8844379807/artifacts/1449995475

**Comment by hpcolus** [comment] 2024-04-30 01:44
Pressing the plus and minus on the windows qz app tile now properly increase or decrease the inclination by 1%. Same as speed. The increase or decrease of 0.1mi/hr
However, suddenly with no warning the qz app quitted unexpectedly without any error message. 

[debug-Mon_Apr_29_21_33_37_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15156708/debug-Mon_Apr_29_21_33_37_2024.log)
[debug-Mon_Apr_29_21_38_46_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15156709/debug-Mon_Apr_29_21_38_46_2024.log)

**Comment by cagnulein** [comment] 2024-04-30 04:43
that's great! ok for the crash: does windows report something when qz
closes itself? did you check in the event register of windows?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 30 apr 2024 alle 03:45 hpcolus ***@***.***> ha
scritto:

**Comment by hpcolus** [comment] 2024-05-02 02:47
Attaching the windows log from event viewer

[windows_log_202405012235.log](https://github.com/cagnulein/qdomyos-zwift/files/15183259/windows_log_202405012235.log)

QZ log while crash occurred

[debug-Wed_May_1_22_30_11_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15183260/debug-Wed_May_1_22_30_11_2024.log)

**Comment by cagnulein** [comment] 2024-05-02 06:58
checked the log and it seems that it lost bluetooth communication from your treadmill. are there other events on the event register before the qz crash? because probably the crash is due to the fact of something that happened before.

we can try another way to have this working, using the mingw instead of the msvc version, but first we have to check if there isn't something about the pc setup that causing this issue.

Let me know!

**Comment by hpcolus** [comment] 2024-05-05 03:45
Hi Roberto.
I deactivated the real time protection of the antivirus and it is working with no crash.  I tested three consecutive days for sessions lasting upto 45 minutes.
So far it seems to be working.
However, the pause/stop tile in the QZ does not produce a "click" sound on the od bus and does not have any effect on the treadmill.

To avoid future crash you should try to implement a catch error routine.
Let me know when we can start trying the autoinclination in Zwift.

[debug-Sat_May_4_23_37_22_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15211658/debug-Sat_May_4_23_37_22_2024.log)

**Comment by cagnulein** [comment] 2024-05-05 05:12
that's great!
a catch error routine it's everywhere in the code so i should understand
where the antivirus put his hands on to add a countermeasure. anyway let's
keep this disabled :)

for the pause stop : does it work on android? the current implementation
it's directly on bluetooth.

for auto inclination you can already try: set the zwift credentials on qz
and give it a go on a free run

let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 5 mag 2024 alle 05:45 hpcolus ***@***.***> ha
scritto:

**Comment by hpcolus** [comment] 2024-05-09 03:36
With QZ android
When In the treadmill I press
- PAUSE, does not have any effect on QZ android tiles
- STOP, QZ android synchronizes with the speed of the treadmill until speed "0" is achieved

With QZ windows app
- Neither PAUSE or STOP on the treadmill yields any effect on the QZ app tiles
- Autoinclination did not work 
[debug-Wed_May_8_23_28_51_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15257259/debug-Wed_May_8_23_28_51_2024.log)

**Comment by cagnulein** [comment] 2024-05-09 04:45
For auto inclination you have to set the zwift credentials in qz and enable
the auto inclination setting under the credentials.

I will check the pause stop thing

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 9 mag 2024 alle 05:36 hpcolus ***@***.***> ha
scritto:

**Comment by cagnulein** [comment] 2024-05-09 09:01
ok i handled also the start and stop modbus command now

https://github.com/cagnulein/qdomyos-zwift/actions/runs/9014929319

did you connect them onto the treadmill too?

**Comment by hpcolus** [comment] 2024-05-10 01:04
Could not download.  It says build status failure
![image](https://github.com/cagnulein/qdomyos-zwift/assets/104551107/84738ac7-a7cc-45b3-b1b6-9da74e88c0d6)

**Comment by cagnulein** [comment] 2024-05-10 03:41
the windows build built, here the direct link https://github.com/cagnulein/qdomyos-zwift/actions/runs/9014929319/artifacts/1487195601

enable also the android setting for auto inclination and also the zwift credentials 

let me know

**Comment by hpcolus** [comment] 2024-05-11 04:17
With this version QZ windows app crashed 

I am able to start QZ app.  I disabled all antivirus.  I started Zwift.  I login.  I paired the treadmill in Zwift.  The moment I start the treadmill the QZ app crashed


[debug-Sat_May_11_00_07_14_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15281610/debug-Sat_May_11_00_07_14_2024.log)

**Comment by cagnulein** [comment] 2024-05-11 12:34
ok i will check next week. in the mean time you can use the previous one to
test auto inclination now the zwift credentials are fine

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 11 mag 2024 alle 06:17 hpcolus ***@***.***> ha
scritto:

**Comment by hpcolus** [comment] 2024-05-13 03:01
I was able to walk for an interval of 10min (first attempt ended up in a crash)
The autoinclination somehow works.  The minimum inclination of BTX216 treadmill is 1%  When I reached in Zwift a hill with an inclination of 2%, the autoinclination went up to 4%  The QZ software attempted several times to fix it; first changing the inclination from 4% down to 3% then up again to 4%  The software tried several to fix it.  I did not have a debug log.  I am reporting just in case you could check this.  I will try to replicate this week.

**Comment by cagnulein** [comment] 2024-05-13 03:24
Consider that qz is using the real inclination, zwift shows the average
.Anyway you can change the zwift inclination gain to 0.5 if you see more or
less always the double
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 13 mag 2024 alle 05:01 hpcolus ***@***.***> ha
scritto:

**Comment by hpcolus** [comment] 2024-05-14 05:09
The 0.5 inclination gain did the trick for a while.  I was able to have a long walk and at the beginning the autoinclination worked, After that I walked down the hill and in the middle of the walk I went up to the hill but the autoinclination stopped working.  The speed continued to work synchronizing between the treadmill and the QZ app.  But the autoinclination did not.  I do not have a small log.  This is the log in a zip file for the entire workout.
I also observed that starting QZ app first then Zwift it was more probable to have a crash.  When I started first Zwift, then QZ I was able to have a long walk.  I will keep testing this scenario. 
[debug-Mon_May_13_21_02_40_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/15302903/debug-Mon_May_13_21_02_40_2024.zip)

**Comment by cagnulein** [comment] 2024-05-14 07:22
hi @hpcolus do you remember when you didn't see the inclination changing anymore? from the log, till the 23:02 everything seems working fine. I can see the incliantion from zwift and i can see the inclination changing on the treadmill from bluetooth and commanded by qz via modbus. A timestamp will be good to isolate the issue. THanks!

**Comment by hpcolus** [comment] 2024-05-14 14:00
You are correct.  The first 30min autoinclination worked.  Between 30min and 50min the terrain was flat or descending so there was no effect of inclination needed.  Around 50-55min there was a hill witt an inclination of 3-4% and that is when I noticed autoinclination did not work.

**Comment by cagnulein** [comment] 2024-05-14 14:05
checked and i saw that QZ was handling the modbus but the inclination
didn't change. Maybe a modbus fault? did you try to change the inclination
manually from QZ then?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 14 mag 2024 alle ore 16:01 hpcolus ***@***.***>
ha scritto:

**Comment by hpcolus** [comment] 2024-05-14 14:19
First, I also checked the device manager in Windows and the COM4 was working.
Yes, I tried to adjust from QZ app tiles, but there was not effect (no click on the modbus)
Then I did adjust the inclination from the buttons of the treadmill.  The treadmill responded to the buttons.
But I did it after I noticed the autoinclination did not work, NOT before.  Not sure if is also related to the fact that between 30 and 50min I was going down the hill with negative inclination in Zwift but because my treadmill minimum inclination is 1%.  I will check tonight or tomorrow again.

**Comment by cagnulein** [comment] 2024-05-14 14:34
it could be the fact that was negative. let me know and in case I will investigate in this direction. thanks

**Closed** 2024-06-09 00:15 UTC
Labels: bug, wontfix

**Comment by hpcolus** [comment] 2024-06-10 00:11
The autoinclination, when it works it does it well.  Compared to previous version, it is more stable, but still there are random crashes at the beginning of the activit

For example, in the first minute or two of the walking on the treadmill, I still see random crashes between 1 or 3 times.  I usually keep the Zwift open when I reinitiate the windows QZ app.  After the second or third time of restarting finally I am able to run the entire session.  I am attaching the logs during the first three crashes then the entire session I completed successfully.

[debug-Thu_Jun_6_2024.zip](https://github.com/user-attachments/files/15755121/debug-Thu_Jun_6_2024.zip)

**Comment by cagnulein** [comment] 2024-06-10 03:17
Ok, I'll check it out.


Il giorno lun 10 giu 2024 alle 02:12 hpcolus ***@***.***> ha
scritto:
