### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Bkbobsledder** [cagnulein/qdomyos-zwift#539] opened 2021-12-30 20:28 UTC
**Describe the bug*
My echelon bike connects to the QZ app for less than 10 seconds and then it disconnects from it which then results in my app shutting down. This is been happening since I first started yesterday with the app. I created a bug report and attached it below.
 Brock Kreitzburg 

[debug-Thu_Dec_30_14_50_46_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/7794541/debug-Thu_Dec_30_14_50_46_2021.log)

iPhone 11
iOS 15.2

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment] 2021-12-31 10:37
@Bkbobsledder the issue is that you have the power sensor device and cadence sensor device set to "Echelon"
Put them to disabled, press ok and restart QZ it should work ok then
Let me know
In case feel free to close this ticket

**Closed** 2021-12-31 14:51 UTC
Labels: bug

**Comment by Bkbobsledder** [comment] 2021-12-31 14:53
Thanks for your help. I still had an issue after I disabled those. I deleted and downloaded again the app and that fixed the problem.
Thanks
Brock

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
