### ISSUE TITLE
[BUG] Two wrong fields on summary display

### ISSUE THREAD

**Issue by laurenweinstein1** [cagnulein/qdomyos-zwift#1645] opened 2023-09-12 19:21 UTC
With the current app, two issues with the "summary" display that now appears upon hitting STOP after a treadmill run:
1) Distance shows 0
2) There is an "average resistance" field (which of course doesn't apply to treadmills) with garbage alpha data displayed.

Thanks.

**Comment by cagnulein** [comment] 2023-09-12 19:24
duplicate of #1564

**Closed** 2023-09-12 19:25 UTC
Labels: bug
