### ISSUE TITLE
Bike doesn’t seem to communicate with app on phone

### ISSUE THREAD

**Issue by Silvermfox** [cagnulein/qdomyos-zwift#2047] opened 2024-01-25 09:52 UTC
Pro form Power 10 bike does not communicate with app on phone. No stats appear. Not sure what equipment to select on bike.
![IMG_9829](https://github.com/cagnulein/qdomyos-zwift/assets/157687851/646ece71-7d28-46bd-9d57-3626070b83f6)
![IMG_9828](https://github.com/cagnulein/qdomyos-zwift/assets/157687851/43c3bc6a-e95e-414b-8807-676acf6b9399)
![IMG_9827](https://github.com/cagnulein/qdomyos-zwift/assets/157687851/5050bc4c-add5-44ba-bd01-b6156c9b3032)
[debug-Thu_Jan_25_18_32_47_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14049867/debug-Thu_Jan_25_18_32_47_2024.log)
[debug-Thu_Jan_25_18_56_17_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14049869/debug-Thu_Jan_25_18_56_17_2024.log)

**Comment by cagnulein** [comment] 2024-01-25 10:17
hi you don't have to put the ip in the tdf4 ip, but in the tdf companion one.
so remove it from the tdf4 and press ok and put it instead on the companion one and press ok and restart qz

share another debug log if the error persists
thanks

**Comment by Silvermfox** [comment] 2024-01-25 11:43
Thank you for trying. Unfortunately it still does not work. Please find new debug log attached.Sent from my iPhoneOn 25 Jan 2024, at 20:17, Roberto Viola ***@***.***> wrote:﻿
hi you don't have to put the ip in the tdf4 ip, but in the tdf companion one.
so remove it from the tdf4 and press ok and put it instead on the companion one and press ok and restart qz
share another debug log if the error persists
thanks

**Comment by cagnulein** [comment] 2024-01-25 11:51
hi you have to attach it from github otherwise i can't see it

**Comment by Silvermfox** [comment] 2024-01-25 12:23
> hi you have to attach it from github otherwise i can't see it

[debug-Thu_Jan_25_21_30_38_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14051552/debug-Thu_Jan_25_21_30_38_2024.log)
[debug-Thu_Jan_25_21_37_54_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14051553/debug-Thu_Jan_25_21_37_54_2024.log)

**Comment by cagnulein** [comment] 2024-01-25 12:24
thanks i will check them asap

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 25 gen 2024 alle 13:23 Silvermfox ***@***.***>
ha scritto:

**Comment by cagnulein** [comment] 2024-01-25 13:04
ok now the issue is that the companion is not sending the metrcics probably because ifit is blocking it.
Try to follow these steps: 

> Set the device in the companion app to C1750 and restart the bike/treadmill.
> Not fixed? Ok do a factory reset to your treadmill/bike tablet but then, after the reset, DON'T update the ifit app. Reinstall the companion and give it a try!
> use this method https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559

**Comment by Silvermfox** [comment] 2024-01-25 22:31
Hi Roberto, QZ app doesn’t seem to be running properly- please see screenshot
![Uploading IMG_9830.jpeg…]()

**Comment by cagnulein** [comment] 2024-01-26 04:37
i can't see the screenshot

**Comment by Silvermfox** [comment] 2024-01-28 06:05
Hi Roberto, I reset the bike and followed the instructions but I got the following results when running the permissions script. Please see attached screenshot. What do I do now?
![IMG_9839](https://github.com/cagnulein/qdomyos-zwift/assets/157687851/fb5afcd5-3236-4136-b563-5259c23b627c)

**Comment by cagnulein** [comment] 2024-01-28 06:50
adb is not working. did you install the companion following the method 1 here? https://github.com/cagnulein/QZCompanionNordictrackTreadmill

**Comment by Silvermfox** [comment] 2024-01-28 06:53
Hi Roberto, yes I did :-( I followed all the steps. I might try from a different device

**Comment by cagnulein** [comment] 2024-01-28 06:57
that's strange @victorypoint do you have any suggestion? it seems that adb is closing down even with the hack of method 1? @Silvermfox maybe you need to do a factory reset and avoid to update ifit in order to disable ifit from closing the door down?

**Comment by Silvermfox** [comment] 2024-01-28 07:03
I did the factory reset before following this method today. I think iFit updates automatically- do not know how to prevent ifit update

**Comment by Silvermfox** [comment] 2024-01-28 07:04
Can factory reset again and see if I missed something

**Comment by cagnulein** [comment] 2024-01-28 07:05
you have to put a null vale in the gateway value of the wifi settings of the treadmill, so ifit can't connect to iternet

**Comment by Silvermfox** [comment] 2024-01-28 07:17
Let me try

**Comment by Silvermfox** [comment] 2024-01-28 08:07
No. Still didn't work.

**Comment by cagnulein** [comment] 2024-01-28 08:08
so with the original ifit version, aren't you able to push via adb the companion? or the issue is that after loading the companion from the adb, the next reboot adb is closed again?

**Comment by Silvermfox** [comment] 2024-01-28 08:13
No can't seem to push the info at all. iFit did not update but no data coming through. I suspect permissions still not right for the app but can't seem to fix it

**Comment by cagnulein** [comment] 2024-01-28 08:15
but are you able now, in this context, to get the adb log? so adb is still open? so I can check what the companion is reading from the treadmill

**Comment by Silvermfox** [comment] 2024-01-28 08:16
I could try- what do I need to do to get it again?

**Comment by cagnulein** [comment] 2024-01-28 08:17
you have to run this
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-debug.bat
from the installpackage folder while you're doing a simple workout (while
the manual window on ifit is open)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 28 gen 2024 alle ore 09:16 Silvermfox <
***@***.***> ha scritto:

**Comment by Silvermfox** [comment] 2024-01-28 08:30
OK. I have done that. Here is the file
[debug-Sun_Jan_28_18_18_54_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14075412/debug-Sun_Jan_28_18_18_54_2024.log)

**Comment by Silvermfox** [comment] 2024-01-28 08:31
NB: Cannot enable all permissions on tablet for companion app

**Comment by cagnulein** [comment] 2024-01-28 08:33
this is the debug log from qz, i need the adb logcat from the tablet using the script that I told you. also what do you mean about the permission? which error did i give you?

**Comment by Silvermfox** [comment] 2024-01-28 12:27
I think that you had said that iFit might be blocking it. It looks like iFit has updated anyway now and privilege mode has disappeared and I can't seem to get it back :-( Looks like I will have to start the whole process again another day. For what it's worth here is the last log I could access
[dumpsys.log](https://github.com/cagnulein/qdomyos-zwift/files/14076020/dumpsys.log)

**Comment by cagnulein** [comment] 2024-01-28 12:30
yes but you could have 2 issues, ifit version and permissions.

so be sure to reset, set the gateway to null, install the companion from
adb and then reboot the treadmill and share an adb log

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 28 gen 2024 alle 13:28 Silvermfox ***@***.***>
ha scritto:

**Comment by victorypoint** [comment] 2024-01-28 20:15
Hi @Silvermfox. So from what I can see in your posts, the companion install script can ping the treadmill (192.168.1.2) but ADB connection was refused. I'd like to troubleshoot this issue. Before launching the install script or "adb connect" again, make sure there are no previous ADB processes running in the background of your PC (use task manager and kill ADB.exe processes). Also make sure to use the correct treadmill IP address as you may be pinging another device on your network with IP 192.168.1.2. Let us know how you make out.

**Closed** 2024-02-20 22:22 UTC
Labels: wontfix

**Comment by cagnulein** [comment] 2024-02-21 07:29
@Silvermfox any news?
