### ISSUE TITLE
[BUG] No data from sensors and avatar won’t move in Zwift (even when data showed on first try)

### ISSUE THREAD

**Issue by Kernow79** [cagnulein/qdomyos-zwift#2178] opened 2024-03-03 10:37 UTC
![Sun Mar 3 11_05_03 2024_heart](https://github.com/cagnulein/qdomyos-zwift/assets/162017647/ff1d01d8-4369-4b7d-981e-3e25002b1e4a)
![Sun Mar 3 11_05_03 2024_cadence](https://github.com/cagnulein/qdomyos-zwift/assets/162017647/8d013887-7738-441b-bc27-ed32faeee41c)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment] 2024-03-03 10:39
Hi @Kernow79 I need a debug log from qz to understand your issue

**Comment by Kernow79** [comment] 2024-03-03 10:47
There are no files with ‘debug’ written in the file name?

Sent from my iPhone

On 3 Mar 2024, at 11:39, Roberto Viola ***@***.***> wrote:

﻿

Hi @Kernow79<https://github.com/Kernow79> I need a debug log from qz to understand your issue

**Comment by cagnulein** [comment] 2024-03-03 10:48
Did you enable the debug log setting as described in the link?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 3 mar 2024 alle 11:47 Kernow79 ***@***.***> ha
scritto:

> There are no files with ‘debug’ written in the file name?
>
> Sent from my iPhone
>

**Comment by Kernow79** [comment] 2024-03-03 10:54
No. I was stressed reading it because I’d driven to the gym to have my workout and couldn’t. I’ve left the gym now. I can try to connect my HRM and cadence sensor without a bike at home and see if I can get a debug file then.

Sent from my iPhone

On 3 Mar 2024, at 11:48, Roberto Viola ***@***.***> wrote:

﻿

Did you enable the debug log setting as described in the link?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 3 mar 2024 alle 11:47 Kernow79 ***@***.***> ha
scritto:

> There are no files with ‘debug’ written in the file name?
>
> Sent from my iPhone
>

**Comment by cagnulein** [comment] 2024-03-03 10:55
Sure thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 3 mar 2024 alle 11:54 Kernow79 ***@***.***> ha
scritto:

> No. I was stressed reading it because I’d driven to the gym to have my
> workout and couldn’t. I’ve left the gym now. I can try to connect my HRM
> and cadence sensor without a bike at home and see if I can get a debug file
> then.
>
> Sent from my iPhone
>

**Comment by Kernow79** [comment] 2024-03-03 11:51
[debug-Sun_Mar_3_12_49_46_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14472766/debug-Sun_Mar_3_12_49_46_2024.log)

**Comment by cagnulein** [comment] 2024-03-03 11:57
interesting. does this sensor work with any app on your phone? i don't see
any messages from it

can you please install the nrfconnect app on the phone and send me a
screenshot about this sensor on the app? nrfconnect is a free app on the
store

thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 3 mar 2024 alle 12:52 Kernow79 ***@***.***> ha
scritto:

**Comment by Kernow79** [comment] 2024-03-03 12:08
![IMG_5604](https://github.com/cagnulein/qdomyos-zwift/assets/162017647/a1a63beb-1861-4d35-8184-6a49847a43a5)
![IMG_5603](https://github.com/cagnulein/qdomyos-zwift/assets/162017647/30aae1f2-9979-4acf-816a-b7e0f8396949)

not sure which page you wanted a screenshot of?

**Comment by cagnulein** [comment] 2024-03-03 12:10
they are ok thanks. i will check later today/ tomorrow 

have a nice sunday

**Comment by Kernow79** [comment] 2024-03-03 12:10
The QZ app picked up both HR and Cadence initially. I tried to use Zwift, connected to my iPhone, but my avatar didn’t move. Then I closed Zwift down and the QZ app no longer shows my HR or Cadence data

**Comment by cagnulein** [comment] 2024-03-03 12:14
indeed i can't see any metrics from both. i will check it, i'm checking it
from the phone, so i need a larger screen to see the log :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 3 mar 2024 alle 13:10 Kernow79 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment] 2024-03-03 15:50
i checked the log @Kernow79 and the issue is that the cadence sensor is not allowing connection to qz. are you able to repeat it trying to keeping alive the sensor moving it for a minute?

**Comment by Kernow79** [comment] 2024-03-03 16:55
I can try again tomorrow. The HR isn’t showing up either, wouldn’t this work ok even if the cadence sensor wasn’t working?

Sent from my iPhone

On 3 Mar 2024, at 16:50, Roberto Viola ***@***.***> wrote:

﻿

i checked the log @Kernow79<https://github.com/Kernow79> and the issue is that the cadence sensor is not allowing connection to qz. are you able to repeat it trying to keeping alive the sensor moving it for a minute?

**Comment by cagnulein** [comment] 2024-03-03 17:01
nope the cadence sensor is the master, if it doesn't work, the HR will not
work neither.
I have already seen strange issues with garmin cadence sensor in the past.
Are you able to connect with nrfconnect to it?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 3 mar 2024 alle ore 17:55 Kernow79 ***@***.***>
ha scritto:

> I can try again tomorrow. The HR isn’t showing up either, wouldn’t this
> work ok even if the cadence sensor wasn’t working?
>
> Sent from my iPhone
>

**Comment by Kernow79** [comment] 2024-03-03 17:05
The Garmin cadence sensor connected to nrfconnect, I think I sent you a screenshot earlier. It’s also worked fine connected directly to Zwift too.

Sent from my iPhone

On 3 Mar 2024, at 18:02, Roberto Viola ***@***.***> wrote:

﻿

nope the cadence sensor is the master, if it doesn't work, the HR will not
work neither.
I have already seen strange issues with garmin cadence sensor in the past.
Are you able to connect with nrfconnect to it?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 3 mar 2024 alle ore 17:55 Kernow79 ***@***.***>
ha scritto:

> I can try again tomorrow. The HR isn’t showing up either, wouldn’t this
> work ok even if the cadence sensor wasn’t working?
>
> Sent from my iPhone
>

**Comment by cagnulein** [comment] 2024-03-03 17:36
this shows connecting , same issue that i see in the qz log. so that's why i'm thinking about a sensor issue in this particular moment 
![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/1a9302ea-a46a-41ad-b465-6986ff4241ba)

**Comment by Kernow79** [comment] 2024-03-03 21:59
![IMG_5605](https://github.com/cagnulein/qdomyos-zwift/assets/162017647/bdb9afdb-7d71-4426-b5b5-69f4a3196515)


The cadence sensor connects to nrfconnect as seen in the image

**Comment by cagnulein** [comment] 2024-03-04 05:23
Ok perfect did you try again on qz in this context? Could you please try again and show me a debug log again? Be sure thst nrf connect is completely closed and also any other apps

**Comment by Kernow79** [comment] 2024-03-04 06:58
I will be able to do it around lunchtime today 👍🏼 thanks

Sent from my iPhone

On 4 Mar 2024, at 06:23, Roberto Viola ***@***.***> wrote:

﻿

Ok perfect did you try again on qz in this context? Could you please try again and show me a debug log again? Be sure thst nrf connect is completely closed and also any other apps

**Comment by Kernow79** [comment] 2024-03-04 12:31
Still not working. Here is debug file and image showing connection to bed connect

[debug-Mon_Mar_4_13_26_51_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14481454/debug-Mon_Mar_4_13_26_51_2024.log)
![IMG_5609](https://github.com/cagnulein/qdomyos-zwift/assets/162017647/6dd77705-4f2e-4059-b39e-9673bcc4510e)

**Comment by cagnulein** [comment] 2024-03-04 13:09
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment] 2024-03-04 13:09
Got the issue! This evening I will send you a new version adding some new
debug view and then I will be able to fix it with the new data.
Unless you have an android too: in this case I can send you an android
version right now to do a test
Let me know

By the way: the problem is that sensor is not sending cadence in a standard
way, but no problem, i can get it (probably zwift have a partnership with
garmin for this)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 4 mar 2024 alle ore 13:32 Kernow79 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment] 2024-03-04 14:40
ok so 
send me an email to roberto.viola83 at gmail.com indicating this ticket and I will send you the newest debug version later today. thanks

**Comment by Kernow79** [comment] 2024-03-04 18:54
Unfortunately it still doesn’t seem to be working…

[debug-Mon_Mar_4_19_52_31_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14485970/debug-Mon_Mar_4_19_52_31_2024.log)

**Comment by cagnulein** [comment] 2024-03-04 18:57
yes it was expected as i said. this version was only to collect more data.
let me check it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 4 mar 2024 alle 19:54 Kernow79 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment] 2024-03-05 05:25
New version sent! Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 4 mar 2024 alle ore 19:57 cagnulein ***@***.***> ha
scritto:

**Comment by Kernow79** [comment] 2024-03-05 06:55
still not working unfortunately! Debug file attached.

[debug-Tue_Mar_5_07_53_11_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14491523/debug-Tue_Mar_5_07_53_11_2024.log)

**Comment by cagnulein** [comment] 2024-03-05 07:21
Argh ok let's try to understand this.

From nrf connect, connect to it and under the 1816 characteristic press this icon

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/6f60bb94-16ab-4be5-a397-17468f6341ea)

Then do you see a value here 

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/99c81cd4-ba2c-40a2-b05a-3482afd13506)

?

**Comment by Kernow79** [comment] 2024-03-05 07:58
![IMG_5611](https://github.com/cagnulein/qdomyos-zwift/assets/162017647/6201ba20-ff30-4d23-bcd3-b8d813e72baf)

**Comment by cagnulein** [comment] 2024-03-05 08:00
nope not the 6A4EC.... but the 1816 one

scroll it down. We have to see a value instead of N/A. It's the current issue of QZ now

**Comment by Kernow79** [comment] 2024-03-05 10:03
I can’t see any values so not sure if I’m looking in the right place…?

![IMG_5614](https://github.com/cagnulein/qdomyos-zwift/assets/162017647/9fed2e0e-6b5c-43c7-a2c8-739d24c2eb1b)

**Comment by cagnulein** [comment] 2024-03-05 10:15
You have to click this one ![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/ff3a04d5-7179-42da-b98c-ee764d8c4b02)

And then the values should provide something.

If not it's the same qz issue. So we need to investigate further

**Comment by Kernow79** [comment] 2024-03-05 11:13
Nothing happens when I press it. It just lights up. See screen capture…


https://github.com/cagnulein/qdomyos-zwift/assets/162017647/4c33dc11-5274-4be5-aa55-53d0ff564d4c

**Comment by cagnulein** [comment] 2024-03-05 11:15
ok that's the issue. so in qz i'm doing the things right but this device is not doing the right thing...don't you have an android device to collect the data from zwift? so we will understand how zwift can read the cadence from it.

**Comment by Kernow79** [comment] 2024-03-05 11:40
No I have MacBook, iPad and iPhone. As I am working away in Malta, I don’t have anyone with android to borrow.

I have found a local bike shop that sells the Wahoo cadence sensor. I think I will have to buy that as this problem doesn’t seem to be easy to fix.

**Comment by cagnulein** [comment] 2024-03-05 12:26
Perfect, a Mac is perfect. Follow these

1. Install Wireshark on your Mac. Download it from [here](https://www.wireshark.org/download.html).
2. Open Wireshark and select your Bluetooth device.
3. Start capturing packets.
4. Start Zwift and connect the cadence sensor.
5. To save, go to File > Save As, and choose your file location and name.

**Comment by cagnulein** [comment] 2024-03-06 14:33
@Kernow79 any news?

**Comment by cagnulein** [comment] 2024-03-06 18:39
sure I would like to! It would help other users!
So now it's working with the wahoo sensor?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 mar 2024 alle ore 19:38 Kernow79 ***@***.***>
ha scritto:

> I bought the Wahoo cadence sensor. I was losing too many days unable to
> train the way I want to.
>
> I appreciate the effort you went to, but I lost 3 days of training and
> didn’t want to lose anymore time.
>
> If you want to continue with the fix for your own benefit then I’m happy
> to send the details you need from my MacBook but I’ll have to fit it in
> around work, I have a busy few days.
>
> Thanks,
>
> Mike
>
> Sent from my iPhone
>

**Comment by Kernow79** [comment] 2024-03-06 19:06
No problem, I understand that. I will try to do what you asked on my MacBook as soon as possible.

Yes it is working with the Wahoo sensor 👍🏼

Sent from my iPhone

On 6 Mar 2024, at 19:40, Roberto Viola ***@***.***> wrote:

﻿

sure I would like to! It would help other users!
So now it's working with the wahoo sensor?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 mar 2024 alle ore 19:38 Kernow79 ***@***.***>
ha scritto:

> I bought the Wahoo cadence sensor. I was losing too many days unable to
> train the way I want to.
>
> I appreciate the effort you went to, but I lost 3 days of training and
> didn’t want to lose anymore time.
>
> If you want to continue with the fix for your own benefit then I’m happy
> to send the details you need from my MacBook but I’ll have to fit it in
> around work, I have a busy few days.
>
> Thanks,
>
> Mike
>
> Sent from my iPhone
>

**Closed** 2024-03-30 23:50 UTC
Labels: bug, wontfix
