### ISSUE TITLE
[REQ] Background operation // Permanent notification option

### ISSUE THREAD

**Issue by IselcoP** [cagnulein/qdomyos-zwift#711] opened 2022-03-03 17:56 UTC
Hello @cagnulein 

I currently use your app on Android to stream from my bike to Zwift on PC, thanks to your excellent work.

I would like to know if it is possible to activate any option so that the application runs in the background (and android does not kill it) and thus be able to use companion on the same device to talk, change direction, control the route and give rideon.

Perhaps via a persistent notification that can be closed on stop to end the activity on completion? I think it would be an interesting option.

PS: I have turned off battery and memory optimization on Android and the app keeps crashing after 10 minutes in the background.

A cordial greeting,

**Comment by cagnulein** [comment] 2022-03-04 07:36
Hi @IselcoP do you think that adding a notification will prevent android to kill the app in background? If so it should be simple to add. @p3g4asus do you have some knowledge about this?

about the companion i don't think it's possible because the companion wants to connect to another device by bluetooth. Do you already try this with the current QZ version? does it work?

**Comment by p3g4asus** [comment] 2022-03-04 07:56
To prevent app from closing in background under Android, app engine has to be turned into Android foreground service that requires a persistent notification to be added (see Service.startForeground method). This is quite an heavy work. I have to think about it.

**Comment by IselcoP** [comment] 2022-03-04 10:20
> Hi @IselcoP do you think that adding a notification will prevent android to kill the app in background? If so it should be simple to add. @p3g4asus do you have some knowledge about this?
> 
> about the companion i don't think it's possible because the companion wants to connect to another device by bluetooth. Do you already try this with the current QZ version? does it work?

Hello again @cagnulein , Currently it is already working together with companion at the same time on the same device and I have not had any problems, that is, I use the mobile as a "translator" and as a command with companion for zwift together and I don't know they annoy each other. On the PC I have a bluetooth receiver so the companion does not act as a receiver itself, I only use it to change the direction while playing, rideon and interact with other players. The only problem is that if I'm not careful, Android closes QZ when changing companion to the foreground to send the actions.

![WhatsApp Image 2022-03-02 at 23 44 24](https://user-images.githubusercontent.com/22306903/156745266-1db3af2c-43e7-496a-b1a0-21a463f60fb1.jpeg)


> To prevent app from closing in background under Android, app engine has to be turned into Android foreground service that requires a persistent notification to be added (see Service.startForeground method). This is quite an heavy work. I have to think about it.

Hi @p3g4asus I thought that a persistent notification would be enough but I'm not a programmer, so what I think may be absurd, what may seem easy to me may involve hard work, I'm sorry for that.

Isn't there an alternative that doesn't involve altering the code? give it a high priority or something? In fact, the program currently lasts in the background working for around 10 minutes.

I think that the modification of the application can be interesting so that other users consider this feature useful. However, if there is a particular solution, I have no problem implementing it myself, nor if you can guide me. My phone is rooted with lineageos as the system and maybe there is some xposed module or some application that allows me to shield the app against android closures to "save" memory that is not in use.

Thanks for everything in advance, sorry for the kilometric messages and a cordial greeting.

**Comment by cagnulein** [comment] 2022-03-04 11:04
@IselcoP i saw that you're quite tech savvy. I have 2 ideas for your setup:
1) why don't you use a VM machine on the pc running QZ with another bluetooth dongle?
2) why don't you use a raspberry otherwise?

Let me know your thoughts

**Comment by IselcoP** [comment] 2022-03-04 21:22
I've considered both options in the past but they come with the downside of having to use the PC to adjust the warm up and cool down for workouts. Using a remote keyboard from the bike is awkward. Both things can be done from the bike with the mobile, so I discarded them in favor of using the phone.

Currently what I am doing is keeping Companion and QZ on split screen, it is not the best option but it is effective.

Coming back to Android, I haven't been able to find any Xposed, Magisk or Application module that manages to keep QZ in the background without closing after ten minutes. I've also tried raising the app's priority and making the app a system app, but to no avail.

**Comment by cagnulein** [comment] 2022-03-05 11:35
what about running QZ on a VM but access to it via cellphone with VNC @IselcoP ? i'm telling you this because putting QZ as a service is a HUGE work and most of the users doesn't have this requirement. So it's defintely possible but it will be low priority for me :)
Let me know your thoughts

**Comment by IselcoP** [comment] 2022-03-06 16:33
> what about running QZ on a VM but access to it via cellphone with VNC @IselcoP ? i'm telling you this because putting QZ as a service is a HUGE work and most of the users doesn't have this requirement. So it's defintely possible but it will be low priority for me :) Let me know your thoughts

I'll look into it, if it's more comfortable than using split screen I'll do it that way. The app is still great, thanks for everything @cagnulein  . 

Greetings and good Sunday.

**Comment by cagnulein** [comment] 2022-03-07 08:47
Thanks @IselcoP I'm leaving this open in order to leave the possibility to others to contribute on this if they will have better ideas to solve this.

**Comment by cagnulein** [comment] 2022-11-29 13:35
i'm checking if simple adding this would leave QZ running on background https://androidwave.com/foreground-service-android-example/

**Comment by cagnulein** [comment] 2022-11-30 08:57
this patch will be in the 2.12.5 let me know if it helps

**Comment by IselcoP** [comment] 2022-11-30 10:49
wow @cagnulein this is great. I'll try it! Although I have already gotten used to using the application on a shared screen and it works wonderfully, it is great news. Thank you very much for your attention, without a doubt the support for the project that you offer is absolutely excellent.

Thank you for everything and a cordial greeting from Spain my friend.

**Comment by cagnulein** [comment] 2022-11-30 20:30
crash on android 13

Exception java.lang.RuntimeException:
  at android.app.ActivityThread.handleServiceArgs (ActivityThread.java:4703)
  at android.app.ActivityThread.-$$Nest$mhandleServiceArgs
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2181)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at android.app.ActivityThread.main (ActivityThread.java:7898)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:936)
Caused by java.lang.IllegalArgumentException:
  at android.app.PendingIntent.checkFlags (PendingIntent.java:401)
  at android.app.PendingIntent.getActivityAsUser (PendingIntent.java:484)
  at android.app.PendingIntent.getActivity (PendingIntent.java:470)
  at android.app.PendingIntent.getActivity (PendingIntent.java:434)
  at org.cagnulen.qdomyoszwift.ForegroundService.onStartCommand (ForegroundService.java:24)
  at android.app.ActivityThread.handleServiceArgs (ActivityThread.java:4685)

**Comment by cagnulein** [comment] 2022-12-01 07:55
thanks @p3g4asus , i will try today with android 13

**Comment by cagnulein** [comment] 2022-12-01 15:01
![image](https://user-images.githubusercontent.com/48216/205086281-0a30bd78-0d05-4f20-8d36-5e09b15c8c60.png)

**Comment by cagnulein** [comment] 2022-12-01 15:02
@victorypoint ok i was missing a permission in the manifest

**Comment by cagnulein** [comment] 2022-12-01 15:30
![image](https://user-images.githubusercontent.com/48216/205093036-49caf952-86a1-467d-9c84-071d1515052d.png)

**Closed** 2022-12-01 15:53 UTC
Labels: enhancement, android
