### ISSUE TITLE
Auto start/sync

### ISSUE THREAD

**Issue by hnbrace** [cagnulein/qdomyos-zwift#1304] opened 2023-02-22 20:05 UTC
[debug-Tue_Feb_21_12_32_20_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10807873/debug-Tue_Feb_21_12_32_20_2023.log)

Calls out seem to be off from auto sync. I don't completely recall but I believe around 10 minutes left was one I could think of more than others.

**Comment by cagnulein** [comment] 2023-02-23 07:09
@hnbrace thanks, I checked, the sync logic works perfectly for the whole workout so I believe that there is something on the metrics from peloton, could you please check that this table is matching the workout that you did?

```
 0 QTime("00:00:06.000") 4.82802 1
 1 QTime("00:00:54.000") 4.82802 1
 2 QTime("00:02:23.000") 2.41401 1
 3 QTime("00:01:25.000") 4.82802 5.5
 4 QTime("00:05:14.000") 4.82802 12.5
 5 QTime("00:00:59.000") 8.0467 12.5
 6 QTime("00:04:04.000") 4.82802 11.5
 7 QTime("00:02:02.000") 7.24203 11.5
 8 QTime("00:03:00.000") 4.82802 11.5
 9 QTime("00:02:57.000") 7.24203 11.5
 10 QTime("00:02:09.000") 4.82802 10.5
 11 QTime("00:00:09.000") 7.5639 10.5
 12 QTime("00:03:44.000") 7.88577 10.5
 13 QTime("00:00:59.000") 8.0467 9.5
 14 QTime("00:05:02.000") 8.20763 9.5
 15 QTime("00:02:51.000") 8.20763 5.5
 16 QTime("00:00:46.000") 4.82802 11.5
 17 QTime("00:00:36.000") 6.43736 11.5
 18 QTime("00:01:23.000") 4.82802 11.5
 19 QTime("00:00:39.000") 5.63269 11.5
 20 QTime("00:00:40.000") 4.82802 11.5
 21 QTime("00:00:43.000") 5.63269 11.5
 22 QTime("00:01:16.000") 8.0467 11.5
 23 QTime("00:00:09.000") 5.63269 11.5
 24 QTime("00:00:24.000") 5.63269 5.5
 25 QTime("00:00:25.000") 5.63269 1
 26 QTime("00:00:02.000") 1.60934 1
```

first column is the index of the training rows (useless)
second column is the duration 
3rd is the speed
4th is the inclination

Let me know, i'm very curious about this

**Comment by cagnulein** [comment] 2023-02-23 07:14
for reference, this is the json from peloton

```
{
  "average_summaries": [

  ],
  "duration": 2700,
  "effort_zones": null,
  "has_apple_watch_metrics": false,
  "is_class_plan_shown": true,
  "is_location_data_accurate": null,
  "location_data": [

  ],
  "metrics": [

  ],
  "muscle_group_score": [

  ],
  "seconds_since_pedaling_start": [

  ],
  "segment_list": [
    {
      "icon_name": "warmup",
      "icon_slug": "warmup",
      "icon_url": "https://s3.amazonaws.com/static-cdn.pelotoncycle.com/segment-icons/warmup.png",
      "id": "041eb29d9db846bca96169944298fc44",
      "intensity_in_mets": 4,
      "is_drill": false,
      "length": 300,
      "metrics_type": "running",
      "name": "Warm Up",
      "start_time_offset": 0
    },
    {
      "icon_name": "walking",
      "icon_slug": "walking",
      "icon_url": "https://s3.amazonaws.com/static-cdn.pelotoncycle.com/segment-icons/walking.png",
      "id": "18256e26c65c4b8798f0a3b48fc1034c",
      "intensity_in_mets": 4,
      "is_drill": false,
      "length": 2340,
      "metrics_type": "running",
      "name": "Walking",
      "start_time_offset": 300
    },
    {
      "icon_name": "cooldown",
      "icon_slug": "cooldown",
      "icon_url": "https://s3.amazonaws.com/static-cdn.pelotoncycle.com/segment-icons/cooldown.png",
      "id": "a9072b2110ca490cbd6da6cbc4c4b7c1",
      "intensity_in_mets": 4,
      "is_drill": false,
      "length": 60,
      "metrics_type": "running",
      "name": "Cool Down",
      "start_time_offset": 2640
    }
  ],
  "splits_data": {
    "distance_marker_display_unit": "mi",
    "elevation_change_display_unit": "ft",
    "splits": [

    ]
  },
  "splits_metrics": {
    "header": [
      {
        "display_name": "mi",
        "slug": "mi"
      },
      {
        "display_name": "Total Time",
        "slug": "total_time"
      },
      {
        "display_name": "Pace",
        "slug": "pace"
      },
      {
        "display_name": "Elevation",
        "slug": "elevation"
      }
    ],
    "metrics": [

    ]
  },
  "summaries": [

  ],
  "target_metrics_performance_data": {
    "target_metrics": [
      {
        "metrics": [
          {
            "lower": 2,
            "name": "speed",
            "upper": 3
          },
          {
            "lower": 0,
            "name": "incline",
            "upper": 1
          }
        ],
        "offsets": {
          "end": 65,
          "start": 60
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 2,
            "name": "speed",
            "upper": 3
          },
          {
            "lower": 0,
            "name": "incline",
            "upper": 1
          }
        ],
        "offsets": {
          "end": 119,
          "start": 66
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 1,
            "name": "speed",
            "upper": 1.5
          },
          {
            "lower": 0,
            "name": "incline",
            "upper": 1
          }
        ],
        "offsets": {
          "end": 262,
          "start": 120
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 2,
            "name": "speed",
            "upper": 3
          },
          {
            "lower": 4.5,
            "name": "incline",
            "upper": 5.5
          }
        ],
        "offsets": {
          "end": 347,
          "start": 263
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 2,
            "name": "speed",
            "upper": 3
          },
          {
            "lower": 11.5,
            "name": "incline",
            "upper": 12.5
          }
        ],
        "offsets": {
          "end": 661,
          "start": 348
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 3,
            "name": "speed",
            "upper": 5
          },
          {
            "lower": 11.5,
            "name": "incline",
            "upper": 12.5
          }
        ],
        "offsets": {
          "end": 720,
          "start": 662
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 2,
            "name": "speed",
            "upper": 3
          },
          {
            "lower": 10.5,
            "name": "incline",
            "upper": 11.5
          }
        ],
        "offsets": {
          "end": 964,
          "start": 721
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 2.5,
            "name": "speed",
            "upper": 4.5
          },
          {
            "lower": 10.5,
            "name": "incline",
            "upper": 11.5
          }
        ],
        "offsets": {
          "end": 1086,
          "start": 965
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 2,
            "name": "speed",
            "upper": 3
          },
          {
            "lower": 10.5,
            "name": "incline",
            "upper": 11.5
          }
        ],
        "offsets": {
          "end": 1266,
          "start": 1087
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 2.5,
            "name": "speed",
            "upper": 4.5
          },
          {
            "lower": 10.5,
            "name": "incline",
            "upper": 11.5
          }
        ],
        "offsets": {
          "end": 1443,
          "start": 1267
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 2,
            "name": "speed",
            "upper": 3
          },
          {
            "lower": 9,
            "name": "incline",
            "upper": 10.5
          }
        ],
        "offsets": {
          "end": 1572,
          "start": 1444
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 2.8,
            "name": "speed",
            "upper": 4.7
          },
          {
            "lower": 9,
            "name": "incline",
            "upper": 10.5
          }
        ],
        "offsets": {
          "end": 1581,
          "start": 1573
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 2.9,
            "name": "speed",
            "upper": 4.9
          },
          {
            "lower": 9,
            "name": "incline",
            "upper": 10.5
          }
        ],
        "offsets": {
          "end": 1805,
          "start": 1582
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 3,
            "name": "speed",
            "upper": 5
          },
          {
            "lower": 8.5,
            "name": "incline",
            "upper": 9.5
          }
        ],
        "offsets": {
          "end": 1864,
          "start": 1806
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 3.1,
            "name": "speed",
            "upper": 5.1
          },
          {
            "lower": 8.5,
            "name": "incline",
            "upper": 9.5
          }
        ],
        "offsets": {
          "end": 2166,
          "start": 1865
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 3.1,
            "name": "speed",
            "upper": 5.1
          },
          {
            "lower": 4.5,
            "name": "incline",
            "upper": 5.5
          }
        ],
        "offsets": {
          "end": 2337,
          "start": 2167
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 1,
            "name": "speed",
            "upper": 3
          },
          {
            "lower": 10.5,
            "name": "incline",
            "upper": 11.5
          }
        ],
        "offsets": {
          "end": 2383,
          "start": 2338
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 2,
            "name": "speed",
            "upper": 4
          },
          {
            "lower": 10.5,
            "name": "incline",
            "upper": 11.5
          }
        ],
        "offsets": {
          "end": 2419,
          "start": 2384
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 1,
            "name": "speed",
            "upper": 3
          },
          {
            "lower": 10.5,
            "name": "incline",
            "upper": 11.5
          }
        ],
        "offsets": {
          "end": 2502,
          "start": 2420
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 1.1,
            "name": "speed",
            "upper": 3.5
          },
          {
            "lower": 10.5,
            "name": "incline",
            "upper": 11.5
          }
        ],
        "offsets": {
          "end": 2541,
          "start": 2503
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 1,
            "name": "speed",
            "upper": 3
          },
          {
            "lower": 10.5,
            "name": "incline",
            "upper": 11.5
          }
        ],
        "offsets": {
          "end": 2581,
          "start": 2542
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 1.1,
            "name": "speed",
            "upper": 3.5
          },
          {
            "lower": 10.5,
            "name": "incline",
            "upper": 11.5
          }
        ],
        "offsets": {
          "end": 2624,
          "start": 2582
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 3,
            "name": "speed",
            "upper": 5
          },
          {
            "lower": 10.5,
            "name": "incline",
            "upper": 11.5
          }
        ],
        "offsets": {
          "end": 2700,
          "start": 2625
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 1.1,
            "name": "speed",
            "upper": 3.5
          },
          {
            "lower": 10.5,
            "name": "incline",
            "upper": 11.5
          }
        ],
        "offsets": {
          "end": 2709,
          "start": 2701
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 1.1,
            "name": "speed",
            "upper": 3.5
          },
          {
            "lower": 4.5,
            "name": "incline",
            "upper": 5.5
          }
        ],
        "offsets": {
          "end": 2733,
          "start": 2710
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 1.1,
            "name": "speed",
            "upper": 3.5
          },
          {
            "lower": 0,
            "name": "incline",
            "upper": 1
          }
        ],
        "offsets": {
          "end": 2758,
          "start": 2734
        },
        "segment_type": "running"
      },
      {
        "metrics": [
          {
            "lower": 0,
            "name": "speed",
            "upper": 1
          },
          {
            "lower": 0,
            "name": "incline",
            "upper": 1
          }
        ],
        "offsets": {
          "end": 2760,
          "start": 2759
        },
        "segment_type": "running"
      }
    ],
    "time_in_metric": [
      {
        "name": "speed",
        "value": 0
      },
      {
        "name": "incline",
        "value": 0
      }
    ]
  }
}
```

**Comment by hnbrace** [comment] 2023-02-24 02:58
![IMG_20230223_204639015_HDR~2](https://user-images.githubusercontent.com/113563203/221079847-25e85516-42cc-4ce4-8034-2cd7826dd963.jpg)


[debug-Thu_Feb_23_12_50_48_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10820218/debug-Thu_Feb_23_12_50_48_2023.log)


I am not too good with all this and the only thing I could think of was to take the class again and try taking notes. I wrote down the instructors call out interval, time she called out it, and when the tread changed. 

Going on when the tread changed it matches closel if not exactly to the duration column you shared above. I do think it is due to how peloton programs the class. The program is not on track with the instructor. QZ seems to track well. 

I think people trying to chase an exact timing will drive them mad. I don't think it is possible after seeing this.

**Comment by cagnulein** [comment] 2023-02-24 07:15
@RickNY can you check also this?

**Comment by cagnulein** [comment] 2023-02-24 07:19
@hnbrace so it seems a peloton error? if so can you open a ticket to them reporting the class and this issue? It should help the other users. What do you think?

**Comment by cagnulein** [comment] 2023-02-24 09:34
@rickny the class is this one https://api.onepeloton.com/api/workout/d99999ca60574d9eb312e21088e4e71c/summary

**Comment by RickNY** [comment] 2023-02-24 12:25
> @RickNY the class is this one https://api.onepeloton.com/api/workout/d99999ca60574d9eb312e21088e4e71c/summary

@cagnulein that link doesn't work -- I dont think it would for me anyway, I think thats the link to his workout summary.  I just looked through the uploaded log -- I think the class in question is "45 min Hike" by Rebecca Kennedy on 3/26/22.. The "id" field allowed me to find the class.. I'll load it up and see how it plays on my setup.. Just to clarify -- this is just the original auto-speed/interval functionality and not the new OCR auto sync on Android, yes?

**Comment by cagnulein** [comment] 2023-02-24 12:31
> that link doesn't work -- I dont think it would for me anyway, I think thats the link to his workout summary. I just looked through the uploaded log

ah you're right

> think the class in question is "45 min Hike" by Rebecca Kennedy on 3/26/22.. The "id" field allowed me to find the class.. I'll load it up and see how it plays on my setup.. Just to clarify -- this is just the original auto-speed/interval functionality and not the new OCR auto sync on Android, yes?

yes the problem is just the auto speed/inclination feature

Thanks

**Comment by RickNY** [comment] 2023-02-24 13:26
OK, so I just let this workout run on its own without me on the tread.. There are a few issues I noticed with the programming of it by Peloton in relation to Rebecca's call-outs... In the first half of the class, she has several call-outs where she says "3...2...1" where you would expect T.Speed/T. Incline to change -- but they dont program it until anywhere from 3-10 seconds after.. Those are relatively minor issues.. Once we get to around the 30:00 elapsed mark of the class, maybe I wans't paying attention to how she structured it -- but she calls for a recovery, and only drops incline from 9 to 5% and leaves speed at 4.1 (I have difficulty set to medium) -- although while watching, it does seem like she slows down at this point.  I will note that the Rebecca Kennedy is not someone you want to watch to gauge if you are at the right speed level - she does her own speed much higher than what the callouts are on any class Ive done with her.   At around the 40:45 mark, the issues with the programming are more pronounced -- with T. Speed at 2.0 and T. Incline at 11.0, she calls out to "go as fast as you can go" -- but T.Speed only changes from 2.0 to 2.3.  At around the 42:00 mark, she then calls out "Roll speed back to 1-1.5", and T. Speed increases here from 2.0 to 2.3.

But QZ itself -- worked as its supposed to.  I think this is just a class with not perfect programming in it -- and I've encountered more of these that are older as opposed to more recent ones -- this one being from May 2022 is one of the oldest Ive ever played.  This one is somewhat manageable with its flaws -- but Ive encountered ones that were so bad, I just quit 10-15 mins in and found a different class.

**Comment by cagnulein** [comment] 2023-02-24 13:29
thank you for the confirmation @RickNY , so @hnbrace if you agree I guess we can close this. Of course, if you want to proceed with opening a ticket to peloton about this, it will be a good thing because they should know that they have an error on their metrics. Or maybe we should just leave things as they are without waking the monster :D

**Comment by hnbrace** [comment] 2023-02-24 15:09
Thanks for your help. I think it is a Peloton issue. I thought about contacting because it seems if these classes are programmed after the fact, they should be able to make them spot on with timing unless it's more involved than I can understand. But I believe you're right about maybe not bringing this to their attention as I don't want to lose this feature of QZ.  Learning this has helped me with trying to chase to offset through out the class to line up the changes with the instructor. I now realize it's probably just peloton. This might be good for newer users to keep this in mind, that it's not the app but rather peloton. Thanks again for putting into action your brilliant ideas. I think closing this fine as it's not on your end.

**Closed** 2023-02-24 15:09 UTC
Labels: peloton
