### ISSUE TITLE
QZ Not Finding FTMS Rower 

### ISSUE THREAD

**Issue by PugMamma** [cagnulein/qdomyos-zwift#2226] opened 2024-03-14 18:05 UTC
Peloton now allows FTMS rowers to connect to the app. Having problems bridging Concept2>QZ>Peloton. Peloton can find my Concept2, but not when it is connect to QZ. 

[debug-Thu_Mar_14_10_17_37_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14606313/debug-Thu_Mar_14_10_17_37_2024.log)

**Comment by PugMamma** [comment] 2024-03-14 18:35
I just tried again and it was still had Virtual Rower enabled. 
[debug-Thu_Mar_14_11_28_17_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14606670/debug-Thu_Mar_14_11_28_17_2024.log)
![Screenshot_20240314-113322](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/5fadbdee-081e-4432-acde-abb5a62276fb)
![431326538_420749970320069_7793483358988717242_n](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/e9cba2cb-6106-40cf-a783-50479aeda03c)

**Comment by cagnulein** [comment] 2024-03-14 18:39
ok yes now i can see it. and qz is doing the right thing. i guess peloton did an implementation adhoc for C2 so they are looking for a C2 specifically.

i will investigate this thanks

that's unfortunate that i can't this myself without the peloton app

**Comment by cagnulein** [comment] 2024-03-14 18:42
peloton is forbidden here in italy :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 14 mar 2024 alle 19:41 PugMamma ***@***.***> ha
scritto:

**Comment by PugMamma** [comment] 2024-03-14 18:43
No way! How dare Italy ban Peloton. Well was trying to offer the slim way I could assist.

**Comment by cagnulein** [comment] 2024-03-14 18:46
yeah i got it thank you :)
i will try to investigate from the log the reason and i will come back to
you

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 14 mar 2024 alle 19:43 PugMamma ***@***.***> ha
scritto:

**Comment by cagnulein** [comment] 2024-03-14 21:08
@PugMamma are you running peloton on android?
if so are you able to follow this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device using the peloton app directly with your rower?
i should be able to check what they are looking for.

is the treadmill bridge from qz instead still working?

**Comment by PugMamma** [comment] 2024-03-14 21:45
I am running Peloton on my phone and was able to enable my developer settings. I will test later and report back. The QZ bridge for my treadmill was working yesterday and I'll test that later today as well.

**Comment by cagnulein** [comment] 2024-03-14 21:47
Ok, thanks for the update.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 14 mar 2024 alle ore 22:45 PugMamma ***@***.***>
ha scritto:

**Comment by PugMamma** [comment] 2024-03-15 15:08
My phone running Peloton was unable to connect to QZ on either the tread or rower. I used my phone to play Peloton on March 9th and it worked, debug log from then, 
[debug-Sat_Mar_9_15_30_19_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14617205/debug-Sat_Mar_9_15_30_19_2024.zip)

I was able to bridge my treadmill by using my Amazon Fire Tablet (which hasn't updated to the newer Peloton version my phone is using). After class 1, I tried to connect Peloton on my phone and was unsuccessful. Here is the debug log from that, 
[debug-Thu_Mar_14_15_55_04_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14617247/debug-Thu_Mar_14_15_55_04_2024.log)

I tried to use QZ on my phone and downloaded Peloton on my Android tablet it was unable to connect too. 

I tried using the Developer instructions. I got the email, but no zip file?
![image](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/2e32b00d-65d0-4d38-8088-498ab51e6f79)
![image](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/63da9cb0-701c-4baa-b36c-5b8bdcadde64)

**Comment by cagnulein** [comment] 2024-03-15 15:16
> My phone running Peloton was unable to connect to QZ on either the tread or rower. I used my phone to play Peloton on March 9th and it worked, debug log from then,
> [debug-Sat_Mar_9_15_30_19_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14617205/debug-Sat_Mar_9_15_30_19_2024.zip)

so maybe it's a bug from their? or they are just trying to closing down the door of QZ for sending bluetooth information.



> I tried using the Developer instructions. I got the email, but no zip file?

usually the zip file (it's a big one) it will be created after 10 minutes and it's in the phone root. Did you check it?

**Comment by PugMamma** [comment] 2024-03-15 15:22
It's been over 30 minutes since I got the developer email and haven't found anything on my phone. Tried googling the file directory it should be located and plugged my phone into the computer via USB to search as well.
Any tips?

**Comment by cagnulein** [comment] 2024-03-15 15:32
didn't receive a notification from the phone after some minutes? the name of the file is the subject of the email so you can try to look to it in the files app

**Comment by PugMamma** [comment] 2024-03-15 20:02
Is there another way I can share the zip files? I did it twice (tried again with a shorter class, but files are still too big). I have them on my Google Drive and could share that way. 
![image](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/83a6ec81-7ecf-4155-9ed1-03f8cdeb7d01)

**Comment by cagnulein** [comment] 2024-03-15 20:04
Sure, Share the link or actually I just need the hci snoof file inside the Bluetooth subdirectory

**Comment by cagnulein** [comment] 2024-03-15 20:10
Got them, thanks! I will check during the weekend hopefully!

**Comment by cagnulein** [comment] 2024-03-15 20:14
Glad to hear it! So strange that no one else is reporting this. Are you aware of others with the same issue after the peloton update?

**Comment by PugMamma** [comment] 2024-03-15 20:40
I am not aware. Should ask people in the FB thread to test as well.

**Comment by cagnulein** [comment] 2024-03-15 20:42
let's wait, i don't want to create a flame :D

**Comment by PugMamma** [comment] 2024-03-15 20:42
True. I did ask Jana, since she is a trusted tester and uses iOS (vs my Android).

**Comment by cagnulein** [comment] 2024-03-15 20:44
sure she is also here @janabouc

**Comment by PugMamma** [comment] 2024-03-15 20:45
I tried to tag Jana but was unsuccessful at finding her. Thanks!

**Comment by janabouc** [comment] 2024-03-15 20:47
@PugMamma  could you clarify what the issue is you'd like me to test?

**Comment by PugMamma** [comment] 2024-03-15 20:51
If you are able to connect QZ to your rower, then have the Peloton app find QZ for the pulled metrics. Currently I can only have my rower connect to QZ or just Peloton. I cannot bridge the 2.

**Comment by janabouc** [comment] 2024-03-15 21:12
Ok, I'll check it out tomorrow. I’m not sure if it’s a feature available on
the guide yet though.

**Comment by PugMamma** [comment] 2024-03-15 21:23
It's not on the Guide. I have to use my phone or tablet. You'll know if your app is up to date if you can see add Rower. 
![431059900_388299343945271_5231154750702197762_n](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/37a73bd2-1119-425a-ae19-0605deae737e)

**Comment by cagnulein** [comment] 2024-03-15 22:03
@PugMamma i'm checking your log before saying good night to my daughter: were you saying that you don't see the QZ device at all on peloton right? or you see it but when you click on it you can't connect to it?

**Comment by PugMamma** [comment] 2024-03-15 22:07
I can't see it at all. Shows no Bluetooth devices.

**Comment by PugMamma** [comment] 2024-03-15 23:09
It must be something with Peloton. My Amazon Fire tablet just updated and now I can no longer bridge for my treadmill workout.

**Comment by cagnulein** [comment] 2024-03-16 07:01
I hope it is. I briefly checked the log and they are doing anything fancy.
The only thing that comes to my mind is: did you try to rename the phone
with qz as a fitness device like the rower or the treadmill? Maybe they are
using the name as a discrimination

I will continue to think about this

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 16 mar 2024 alle 00:10 PugMamma ***@***.***> ha
scritto:

**Comment by cagnulein** [comment] 2024-03-16 07:21
for example renaming your phone as "PM5" and reboot it

**Comment by cagnulein** [comment] 2024-03-16 14:36
an user on iOS she's confirming to me that it's working as it should. So maybe it's an Android bug of the peloton app?

**Comment by PugMamma** [comment] 2024-03-16 15:00
The other day I tried renaming my phone to Row without success, but I'll try PM5.

**Comment by cagnulein** [comment] 2024-03-16 15:01
it could be they would like to see PM5 with also the numbers right to it (it's just a speculation of course)

**Comment by PugMamma** [comment] 2024-03-16 15:04
It's just renaming the device that is running QZ, correct?

**Comment by cagnulein** [comment] 2024-03-16 15:05
yes exactly

**Comment by janabouc** [comment] 2024-03-16 19:22
First i tried connecting pm5 to peloton directly on ipad then on iPhone
after making sure Bluetooth connection was turned on in settings and pm5
was set to Connect. In Peloton’s Bluetooth connection screen it only showed
my polar HR band, didn’t offer Bluetooth FTMS devices as options though it
said to choose a type of device.

I tried the same thing with connecting QZ to PM5 and Peloton still didn’t
show any connection options.

I checked for peloton updates in App Store but it said i was up to date. So
now I’m just going to row. 🙃

Jana

**Comment by cagnulein** [comment] 2024-03-16 19:29
Thanks, maybe on ios this possibility is not possible yet.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 16 mar 2024 alle 20:23 janabouc ***@***.***> ha
scritto:

**Comment by PugMamma** [comment] 2024-03-16 19:39
I know some iOS users have been able to connect their app to their Concept2. Just assume things are slowly being pushed out. 
I tried to just connect my Peloton app directly to my Horizon tread and it was unable to find it. I tried on my phone and Kindle Fire. I'm asking in another group if other Android users who got the update, can no longer connect their treadmills (only rowers).
![Screenshot_20240316_114652_Peloton](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/731f73a8-7671-4182-a770-85d84136cee8)

**Comment by cagnulein** [comment] 2024-03-16 19:40
@PugMamma that's could be a great news since it's seems a bug not a feature of the peloton app since it doesn't work also with standard ftms devices

finger crossed

**Comment by janabouc** [comment] 2024-03-16 19:50
I probably haven't gotten the roll out yet. I haven't tried it on my treadmill. I haven't been taking peloton treadmill classes, just walking and reading on it. I'm happy to try to connect if it helps but maybe after I get an update to the peloton app.

**Comment by cagnulein** [comment] 2024-03-16 19:54
@janabouc yes sure, let's wait the update . thanks so far as always

**Comment by PugMamma** [comment] 2024-03-17 03:00
I tried renaming my tablet that I use QZ with, PM5 530382227 Row, PM5 530382227 and just PM5 and I was never able to get it to connect or be seen by Peloton.

**Comment by cagnulein** [comment] 2024-03-17 07:01
ok thanks for trying :(

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 17 mar 2024 alle 04:00 PugMamma ***@***.***> ha
scritto:

**Comment by cagnulein** [comment] 2024-03-20 13:58
@marklogan17 are you able to test if you have issues too to send ftms treadmill to peloton with the last update?
I would like to try myself but creating a vpn, creating a fake account on peloton it's too risky for the my personal position

**Comment by cagnulein** [comment] 2024-03-20 14:54
perfect, so that's a confirmation that they have some issues. Fingers crossed!

**Comment by gitoutofhere8** [comment] 2024-04-27 13:36
@cagnulein FYI the Peloton FTMS tread integration broke in Peloton 3.20.  it still can't find QZ FTMS on 3.23 however it can find QZ HR.

3.19.1 works.

**Comment by gitoutofhere8** [comment] 2024-04-27 13:48
Is there a way to change the FTMS name from QZ (QZ on IOS)  to something custom?

**Comment by cagnulein** [comment] 2024-04-27 14:16
> @cagnulein FYI the Peloton FTMS tread integration broke in Peloton 3.20. it still can't find QZ FTMS on 3.23 however it can find QZ HR.
> 
> 3.19.1 works.

i hope they will fix it soon



> Is there a way to change the FTMS name from QZ (QZ on IOS) to something custom?

nope but i can do it. could I ask you why?

**Comment by gitoutofhere8** [comment] 2024-04-27 14:19
Curious just in case it was being blocked but I don't think that's the current reason for it not working as it's connecting with QZ on HR feed ok.

**Comment by cagnulein** [comment] 2024-04-27 14:26
nope that's not the reason: users with ftms treadmills or rowers has the
issue as well!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 apr 2024 alle 16:19 gitoutofhere8 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment] 2024-06-11 07:17
ok let's go back on this. i was checking again your logs @PugMamma and i found that the rower is sending frames in a slightly different way from QZ. Both PM5 and QZ are using the FTMS standard but i guess that the funny devs on peloton are filtering only the PM5 in order to close the doors to QZ.
So that's my plan I will create a fake version of data to match the PM5 one, just to check if my understandings are right.

I will update you with the new build

**Comment by cagnulein** [comment] 2024-06-11 08:06
this is the build https://github.com/cagnulein/qdomyos-zwift/actions/runs/9461681239

you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.

@PugMamma use this only for a test (this version will send FAKE FTMS data to peloton, so the scope of this test is only to understand if peloton is strictly looking for these kind of datas)

let me know

**Comment by cagnulein** [comment] 2024-06-13 09:17
ok there is an issue for sure on the QZ side, are you able to provide me a debug log from QZ on iOS? I can't see any FTMS at all!

**Comment by RowYourBoatWill** [comment] 2024-06-13 09:24
Have I just captured the wrong thing?I’ll do it after I put the kids to bed.Sent from my iPhoneOn 13 Jun 2024, at 7:17 PM, Roberto Viola ***@***.***> wrote:﻿
ok there is an issue for sure on the QZ side, are you able to provide me a debug log from QZ on iOS? I can't see any FTMS at all!

**Comment by cagnulein** [comment] 2024-06-13 09:25
No I guess you captured the right screenshots but there is something wrong on the QZ setup on iOS for sure, so i would try to check it with a debug log from QZ on iOS https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Thanks

**Comment by RowYourBoatWill** [comment] 2024-06-13 09:32
Sent from my iPhoneOn 13 Jun 2024, at 7:26 PM, Roberto Viola ***@***.***> wrote:﻿
No I guess you captured the right screenshots but there is something wrong on the QZ setup on iOS for sure, so i would try to check it with a debug log from QZ on iOS https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
Thanks

**Comment by RowYourBoatWill** [comment] 2024-06-13 09:33
I hope that worked.CheersRossSent from my iPhoneOn 13 Jun 2024, at 7:26 PM, Roberto Viola ***@***.***> wrote:﻿
No I guess you captured the right screenshots but there is something wrong on the QZ setup on iOS for sure, so i would try to check it with a debug log from QZ on iOS https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
Thanks

**Comment by cagnulein** [comment] 2024-06-13 09:33
you have to attach to the github web interface otherwise I can't see it. thanks

**Comment by RowYourBoatWill** [comment] 2024-06-13 09:39
[debug-Thu_Jun_13_19_25_32_2024.log](https://github.com/user-attachments/files/15817174/debug-Thu_Jun_13_19_25_32_2024.log)

**Comment by RowYourBoatWill** [comment] 2024-06-13 10:38
![Screenshot_2024-06-13-20-32-13-240](https://github.com/cagnulein/qdomyos-zwift/assets/172378184/714dab75-d4b4-47b6-a8d2-087382bd0d65)
![Screenshot_2024-06-13-20-31-28-728](https://github.com/cagnulein/qdomyos-zwift/assets/172378184/c5cef8e7-4440-4c0b-8e29-99861719230c)
![Screenshot_2024-06-13-20-31-34-989](https://github.com/cagnulein/qdomyos-zwift/assets/172378184/13dfb28e-cf4e-4622-9b7e-d56f59d5ce25)
![Screenshot_2024-06-13-20-31-44-627](https://github.com/cagnulein/qdomyos-zwift/assets/172378184/69e49f75-4358-4452-b357-a25e23652790)
![Screenshot_2024-06-13-20-32-03-341](https://github.com/cagnulein/qdomyos-zwift/assets/172378184/67b4bd8b-43bf-4c92-8e77-1e29f8b03819)
![Screenshot_2024-06-13-20-32-05-330](https://github.com/cagnulein/qdomyos-zwift/assets/172378184/f00f6b72-5207-4965-9683-ddad118e2e81)

**Comment by cagnulein** [comment] 2024-06-13 12:30
ok @RowYourBoatWill I got for sure the issue: the FMTS data is correctly displayed on the left side of the screen on nrfconect but it doesn't on the right one. I guess Peloton is reading somehow only the right one.
The same thing is shown from the hci snoof that you created for the C2 against the QZ iOS one. So I guess we have a lead!
Now I have to understand how this is possible since I'm not doing anything different from the bike, that on peloton works correctly.
I have to test myself if I can see the same behaviour on nrfconnect.
I will let you know

**Comment by gitoutofhere8** [comment] 2024-06-13 12:50
Hi @cagnulein,

The Tread FTMS (from QZ on ios) continues to be broken on Peloton for
Android since rev 3.20.  Whenever I try to upgrade it won't connect to QZ
FTMS and have to downgrade to Peloton 3.19.  I have tried many times and
Peloton Support will not acknowledge / investigate.

If you happen to have a user with a Horizon Treadmill perhaps they could
help with the troubleshooting steps like what's being done for the C2.  As
I have Nordictrack, no direct connection is possible for me to try.

**Comment by cagnulein** [comment] 2024-06-13 12:52
Hi @gitoutofhere8 I guess the problem it could be the same. Anyway @RowYourBoatWill told me that even with 3.19 (am I right?) the FTMS rower doesn't work. So maybe they did 2 different things.
Anyway I will try to follow the lead that i saw from the @RowYourBoatWill logs

**Comment by gitoutofhere8** [comment] 2024-06-13 16:18
Mostly.  Instead of Cycling Speed and Cadence 0x1816 I see Running Speed
and Cadence 0x1814.

**Comment by gitoutofhere8** [comment] 2024-06-13 17:16
I just borrowed another Apple device.  Peloton on iOS can successfully
connect with QZ Tread FTMS from another iOS device.

So the connection problem seems Android specific.

**Comment by cagnulein** [comment] 2024-06-13 17:21
That's a great news!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 13 giu 2024 alle 19:17 gitoutofhere8 ***@***.***>
ha scritto:

**Comment by gitoutofhere8** [comment] 2024-06-13 17:22
Also I looked at a row class on Peloton App 3.19 on Android and there was
no option to connect FTMS rower, just HR.

**Comment by RowYourBoatWill** [comment] 2024-06-13 19:19
3.19 was the last version prior to adding the option for FTMS rowers.  I think the option starts at 3.20.Sent from my iPhoneOn 13 Jun 2024, at 10:53 PM, Roberto Viola ***@***.***> wrote:﻿
Hi @gitoutofhere8 I guess the problem it could be the same. Anyway @RowYourBoatWill told me that even with 3.19 (am I right?) the FTMS rower doesn't work. So maybe they did 2 different things.
Anyway I will try to follow the lead that i saw from the @RowYourBoatWill logs

**Comment by cagnulein** [comment] 2024-06-14 07:00
@gitoutofhere8 did you try also ios to ios for the rower thing? you can use the fake rower setting in the experimental setting plus the virtual rower setting to simulate all of this. @RowYourBoatWill did you try the same too?

**Comment by RowYourBoatWill** [comment] 2024-06-14 07:36
I tried iOS to iOS with your beta last night and couldn’t get a full connection.  HR connected perfectly, but the rower never connected.On 14 Jun 2024, at 5:00 PM, Roberto Viola ***@***.***> wrote:﻿
@gitoutofhere8 did you try also ios to ios for the rower thing? you can use the fake rower setting in the experimental setting plus the virtual rower setting to simulate all of this. @RowYourBoatWill did you try the same too?

**Comment by RowYourBoatWill** [comment] 2024-06-14 08:26
I’ve already tried this, it doesn’t work.  Am I missing something? Is there a different beta or setting to try after last night?  Happy to try whatever.  I see QZ when I go to connect to Bluetooth, but it fails every time, virtual or real rower makes no difference.  HR works every time.On 14 Jun 2024, at 5:00 PM, Roberto Viola ***@***.***> wrote:﻿
@gitoutofhere8 did you try also ios to ios for the rower thing? you can use the fake rower setting in the experimental setting plus the virtual rower setting to simulate all of this. @RowYourBoatWill did you try the same too?

**Comment by cagnulein** [comment] 2024-06-14 08:29
> I’ve already tried this, it doesn’t work.  Am I missing something? Is there a different beta or setting to try after last night?  Happy to try whatever.  I see QZ when I go to connect to Bluetooth, but it fails every time, virtual or real rower makes no difference.

nope i was talking with @gitoutofhere8  just to be sure that also him has the same behaviour that you did since that he can to a ios to ios stream using the treadmill instead. if you want you can try the reverse, using the fake treadmill setting, and checking that also you are able to stream the ftms treadmill to peloton

**Comment by cagnulein** [comment] 2024-06-17 07:43
ok i got the issue: Peloton did what garmin does on the watches: they are checking for real devices in order to ignore the "simulate devices" like qz.

Lucky for you there is a way to avoid this, but not on the phone. The way to achieve this is:

- Use qz as usual on your phone in tandem with an ESP32 with a QZ firmware inside
- The ESP32 will comunicate transparent to QZ and peloton so it will send all the metrics there.

If you agree to this, i will produce the firmware to achieve this.

It's very time consuming, so I hope you will appreciate this (i have to find a way to monetize somehow this effort, i can't do this pro bono anymore)

let me know @PugMamma @gitoutofhere8 @RowYourBoatWill

**Comment by cagnulein** [comment] 2024-06-17 08:17
update, it seems to be possible on android https://developer.android.com/reference/android/bluetooth/le/AdvertiseData.Builder#addServiceData(android.os.ParcelUuid,%20byte[])

and also on ios

https://developer.apple.com/documentation/corebluetooth/cbadvertisementdataservicedatakey

so there is hope to use it without the ESP32!

**Comment by cagnulein** [comment] 2024-06-17 08:24
reference for me

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/a0701b1a-7102-447f-9737-e6383fc064bb)

**Comment by cagnulein** [comment] 2024-06-17 12:45
ok on ios that property is readonly. https://stackoverflow.com/questions/56315371/warning-the-advertisement-key-service-data-is-not-allowed

Let's try on android

**Comment by cagnulein** [comment] 2024-06-18 07:43
@RowYourBoatWill ok i guess we have a first one for android.

https://github.com/cagnulein/qdomyos-zwift/actions/runs/9560360460/artifacts/1611695268

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.

enable the virtual rower setting of course. I didn't try myself because I need a second android device to check it. I will do later today in case. Let me know! Try Peloton on both android and ios if possible

Let me know if you have any questions

**Comment by RowYourBoatWill** [comment] 2024-06-18 11:03
Tested and working for both Android to iOS and Android to Android.  Thank you!!!!!The Android to iOS setting is SLICK.  It connects immediately and displays metrics beautifully.  I had some drama with the Android to Android connection initially, but it’s working great now.On 18 Jun 2024, at 5:43 PM, Roberto Viola ***@***.***> wrote:﻿
@RowYourBoatWill ok i guess we have a first one for android.
https://github.com/cagnulein/qdomyos-zwift/actions/runs/9560360460/artifacts/1611695268
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to ***@***.*** mentioning this ticket and that you are on android.
enable the virtual rower setting of course. I didn't try myself because I need a second android device to check it. I will do later today in case. Let me know! Try Peloton on both android and ios if possible
Let me know if you have any questions

**Comment by cagnulein** [comment] 2024-06-18 11:35
that's great @RowYourBoatWill  !

i will test the ftms treadmill too @gitoutofhere8

**Closed** 2024-06-19 10:17 UTC
Labels: bug
