### ISSUE TITLE
[BUG]Unable to connect devices to cycling apps. No devices show up in Zwift. Peloton ok

### ISSUE THREAD

**Issue by Bike2000** [cagnulein/qdomyos-zwift#1036] opened 2022-11-12 15:40 UTC
**Describe the bug**
Discussed on Facebook:
I’m having tech difficulties connecting QZ to cycling apps and hope that some experienced users here can help point out where I’ve gone wrong, please.
I have an Echelon EX-3, run QZ on iPhone 14 and Apple Watch, other apps on iPad Air.
-Peloton app: Works perfectly, including auto-resistance. Amazing.
I then turned off Cycling Cadence Sensor (Peloton) in the QZ app, closed the  QZ app and confirmed that the setting was in fact off.

I then fail to fully connect to the other cycling apps:
-Rouvy: “Controllable” won’t connect. “Smart trainer…” connects and provides wattage. Cadence connects. Heart Rate shows as connected, but displays 0 as heart rate.(Heart rate displays properly on QZ on Watch and iPhone.) So I can ride with wattage displayed, but without auto-resistance and heart rate.

-Zwift: Before trying, I disconnected devices in Rouvy and closed the Rouvy app. Trying to pair devices in Zwift, nothing shows up. (See pic below)

-I then try Fulgaz, since that is supposed to also work well with QZ. “Trainer Resistance Control” shows as “Connecting” but it won’t connect. Power and Cadence show up properly. I can ride without auto-resistance.

I imagine that I have a setting or two improperly set in QZ, but I can’t figure out what it is. Thanks for your advice!!

**To Reproduce**

**Expected behavior**

**Screenshots**
 
![B009F9CA-BA5E-4163-B67B-DACB6C51E88A](https://user-images.githubusercontent.com/118065510/201481918-28948c5b-9d24-4bfb-b9fd-4c10360cfd19.jpeg)
![E6BC8B03-95AF-4F3F-94FD-816D632B1F27](https://user-images.githubusercontent.com/118065510/201481926-f6911ce3-b838-4540-a737-d74b9054d8fc.jpeg)

**Desktop (please complete the following information):**
 IPad Air Gen 4 (running Zwift, fulgaz…)
iOS 15.6.1

**Smartphone (please complete the following information):**
iPhone 14 Pro (running QZ)
iOS 16.0.3

**Append a debug log**

file:///var/mobile/Library/SMS/Attachments/f2/02/47633E80-7DC2-49C2-B338-5609772E621B/debug-Sat_Nov_12_07_38_37_2022.log

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment] 2022-11-12 15:41
[debug-Sat_Nov_12_07_38_37_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9995295/debug-Sat_Nov_12_07_38_37_2022.log)

**Comment by cagnulein** [comment] 2022-11-12 15:43
@Bike2000 when qz is running on your iphone, can you please send me a screenshot of what do you see on nrfconnect on the ipad?

**Comment by Bike2000** [comment] 2022-11-12 16:14
This?
![IMG_1532](https://user-images.githubusercontent.com/118065510/201483410-64cfafea-e14f-461f-b775-ac55484f8e1d.png)
![218D636E-2108-4B27-9EC8-075EDD15E3AC](https://user-images.githubusercontent.com/118065510/201483435-c8f4a7af-f48f-4029-896b-57348732e3ae.png)

**Comment by cagnulein** [comment] 2022-11-12 16:34
DomyosBR is the name with the ios peloton workaround off. Very strange.
Try this: 
1) open qz, toggle ios peloton workaround off
2) restart qz
3) connect to the bike
4) toggle on again ios peloton workaround on
5) restart qz
6) check again nrfconnect

If you see a different name, try again with zwift

Let me know

**Comment by Bike2000** [comment] 2022-11-12 17:47
No change. Should I delete and reload QZ app? I did that a few days ago tho, didn't help.

![image](https://user-images.githubusercontent.com/118065510/201487577-1ba8ee66-34ac-4a04-a8dc-53ced3025344.png)

**Comment by cagnulein** [comment] 2022-11-12 17:55
nope, if it doesn't change means that the issue is not in qz itself. do you have a third device to double check the nrfconnect results?

**Comment by Bike2000** [comment] 2022-11-12 23:34
Before next tests, I turned off my iphone (running QZ) and restarted.
Still showing DomyosBr on my iPad.
Tested on another iPhone 14 Pro running 16.0.3.
That showed DomyosBr also on nRF connect. (Pics below)

More info: I originally tried QZ last year on a different iPhone and had the same problems. I stopped using the cycling apps until last week.

Hard to understand how nRF connect on my iPad and the other iPhone are showing DomyosBr if that isn't somehow being sent.

What do you think might be causing the problem?
![image](https://user-images.githubusercontent.com/118065510/201498673-f21e1473-5b4f-4c13-b657-d42f3716feb3.jpeg)
![image](https://user-images.githubusercontent.com/118065510/201498677-b1572eb1-2cfb-44c1-ac18-ae5e9350e25d.jpeg)

**Comment by cagnulein** [comment] 2022-11-13 06:12
could you please try to install qz on the ipad without changing any settings?
I would like to see if you have the same behavior also on the other side
Let me know 
It's a mistery!

**Comment by Bike2000** [comment] 2022-11-13 07:25
I didn't do your suggestion yet, but-

Thinking that the problem is from my phone, I uninstalled some cycling apps that I had on the phone - peloton, Zwift, Rouvy. No luck.

I then went through every setting on QZ that I thought might impact this, turning on or off and seeing what showed up in nRF connect

I finally got down to Bike Power Sensor in Experimental Features. That was on. I turned it off, and nRF connect then showed QZ instead of DomyosBr. I then went into Zwift, devices appeared and it seems that I am able to connect properly. I will try the apps in the morning and see how they work.

Does this make any sense to you?

[image][image][image]

On Nov 12, 2022, at 11:13 PM, Roberto Viola ***@***.***> wrote:

﻿

could you please try to install qz on the ipad without changing any settings?
I would like to see if you have the same behavior also on the other side
Let me know
It's a mistery!

**Comment by cagnulein** [comment] 2022-11-13 07:27
Hah yes absolutely! This force the iOS peloton workaround off! That's for sure the issue. Let me know how it goes

**Comment by Bike2000** [comment] 2022-11-13 07:35
Great.
So, should Bike Power Sensor always be off for Zwift, Rouvy, etc? I don’t know if I turned it on before; what is the default when installing QZ?

Would I need to turn it on when using Peloton?

On Nov 13, 2022, at 12:27 AM, Roberto Viola ***@***.***> wrote:

﻿

Hah yes absolutely! This force the iOS peloton workaround off! That's for sure the issue. Let me know how it goes

**Comment by cagnulein** [comment] 2022-11-13 07:37
The default is off for that setting. This needs to be only for app that strictly want only a power sensor (for sure not Zwift, peloton,rgt...)
Let me know

**Comment by Bike2000** [comment] 2022-11-14 03:23
Zwift and Rouvy seem to be working perfectly now. (Not sure I have all the Zwift settings correct but setting Zwift Resistance Offset to 20 was important:)
Fulgaz recognizes QZ now, but it is not detecting heart rate from QZ. Heart rate was displayed on QZ iphone and watch:

[image]

[image]

Fulgaz does recognize heart rate from HeartCast app. But I would need another device to run it.

[image][image]

Any tricks to get heart rate from QZ to Fulgaz (along with power, etc. that is already connected)?
Thanks!


On Nov 13, 2022, at 12:37 AM, Roberto Viola ***@***.***> wrote:

﻿

The default is off for that setting. This needs to be only for app that strictly want only a power sensor (for sure not Zwift, peloton,rgt...)
Let me know

**Comment by cagnulein** [comment] 2022-11-14 07:06
Hi @Bike2000 great news!
I don't see the images, you need to upload them by github website.
Anyway Fulgaz expects the heart rate device from a separate device, that's why you don't see it (but instead you see it on Zwift and Rouvy). It's a Fulgaz limitation. You can write to their support and put me in CC.
Let me know

**Comment by Bike2000** [comment] 2022-11-14 12:38
Ok, thanks

On Nov 14, 2022, at 12:07 AM, Roberto Viola ***@***.***> wrote:

﻿

Hi @Bike2000<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBike2000&data=05%7C01%7C%7C068b0cc63884402fb2d508dac60ed596%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638040064262250599%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YPOe5wJys8mjMtt2YRTXoUD%2BcgZJwKz%2FhMBWwVn5s6c%3D&reserved=0> great news!
I don't see the images, you need to upload them by github website.
Anyway Fulgaz expects the heart rate device from a separate device, that's why you don't see it (but instead you see it on Zwift and Rouvy). It's a Fulgaz limitation. You can write to their support and put me in CC.
Let me know

**Comment by Bike2000** [comment] 2022-11-15 20:41
Roberto-
I wrote Fulgaz today and copied you.
As I was enjoying a Rouvy ride with auto-resistance this morning 😁, I was thinking of how you could earn more money from your creation. Have you considered selling advertising on the facebook page? And perhaps on the app? You would of course limit ads so not to become annoying. And I think that most of your users/fans would be glad that you are earning money that way. 10,000 facebook members is not huge, but the audience is very focused and could be attractive to companies like Zwift, Rouvy, stationary bike suppliers, cycling gear….

Possibly also some money for clicks to advertisers’ websites and a share of subscriptions and other purchases when your app users buy a subscription, equipment, etc.
Thoughts?
Scott

On Nov 14, 2022, at 12:07 AM, Roberto Viola ***@***.***> wrote:

﻿

Hi @Bike2000<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBike2000&data=05%7C01%7C%7C068b0cc63884402fb2d508dac60ed596%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638040064262250599%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YPOe5wJys8mjMtt2YRTXoUD%2BcgZJwKz%2FhMBWwVn5s6c%3D&reserved=0> great news!
I don't see the images, you need to upload them by github website.
Anyway Fulgaz expects the heart rate device from a separate device, that's why you don't see it (but instead you see it on Zwift and Rouvy). It's a Fulgaz limitation. You can write to their support and put me in CC.
Let me know

**Comment by cagnulein** [comment] 2022-11-16 07:13
> Roberto- I wrote Fulgaz today and copied you.

Uh, i didn't receive anything. Which address did you use?

> As I was enjoying a Rouvy ride with auto-resistance this morning 😁,

Great!

> I was thinking of how you could earn more money from your creation. Have you considered selling advertising on the facebook page? And perhaps on the app? You would of course limit ads so not to become annoying. And I think that most of your users/fans would be glad that you are earning money that way. 10,000 facebook members is not huge, but the audience is very focused and could be attractive to companies like Zwift, Rouvy, stationary bike suppliers, cycling gear…. Possibly also some money for clicks to advertisers’ websites and a share of subscriptions and other purchases when your app users buy a subscription, equipment, etc. Thoughts? Scott

For the moment it's ok, i mean the app on ios and android are giving me some money to run everything and I'm ok with it. I really don't like the ads, so maybe in the future I will think about other forms :) Thanks anyway for your ideas ;)
I'm closing this one, feel free to open it again in case of news!

**Closed by cagnulein** 2022-11-16 07:13 UTC
Labels: bug
