### ISSUE TITLE
Nordictrack x22i and auto speed/incline

### ISSUE THREAD

**Issue by Cwawra13** [cagnulein/qdomyos-zwift#1916] opened 2023-12-27 06:11 UTC
[debug-Tue_Dec_26_23_00_37_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13775993/debug-Tue_Dec_26_23_00_37_2023.log)

**Comment by cagnulein** [comment] 2023-12-27 06:16
ok good news, adb seems well connected

void lockscreen::adb_connect(const char *)_block_invoke connected to 192.168.86.77:5555

the command that qz is sending is

./adb shell input swipe 1845 808 1845 797 200

do you see a touch event if you are doing this from your pc @Cwawra13  ?

**Comment by Cwawra13** [comment] 2023-12-27 06:30
Shucks; I was thinking you were going to be away. I’ll test this in 6-8 hours; it’s late where I am. Sorry!

**Comment by cagnulein** [comment] 2023-12-27 06:31
no rush! i'm always trying to do my duties before my morning workouts :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 27 dic 2023 alle 07:30 Cwawra13 ***@***.***> ha
scritto:

**Comment by Cwawra13** [comment] 2023-12-27 23:13
Hi!

Thanks for your help; here's what I got.

It looks like this command is only swiping up by 11 pixels, which seems to
send not a full swipe. When I change it to this ./adb shell input swipe
1845 808 1845 750 200, that makes is 58 pixels and actually does a full
swipe action on the machine.

Thanks!

**Comment by cagnulein** [comment] 2023-12-28 07:31
perfect! this means that the engine works! We just need to understand why the coordinates aren't working as they did for https://github.com/cagnulein/QZCompanionNordictrackTreadmill/issues/65
Could you please check if the screen layout and coordinates of your treadmill is the same of the one on that post?
Also try to start the treadmill (so the speed is greater than 0) and try to do a plus action from QZ, it could be that the transition from 0 to 0.5 could be wrong. Also you can force to do a 1 km/h increment instead of a 0.5km/h in the treadmill settings, but we need to understand the root cause

**Comment by Cwawra13** [comment] 2023-12-29 04:43
Great! We are making progress.I learned something unique.  In manual mode, you need to have  choose controls so both controls are visible on the far right and left vertically for this to work.It works for me to change speed but not incline by using buttons on the qz. Incline is on the left.While I have you here.. I am under the impression qz will automatically change speed and incline via qz for a peloton workout.. is that true? If so, can you send me a GitHub link that explains how do do that? Seems like I’m close to having that happen now that they’re communicating better? Thank you for all your help! I appreciate it.Sent from my iPhoneOn Dec 28, 2023, at 12:31 AM, Roberto Viola ***@***.***> wrote:﻿
perfect! this means that the engine works! We just need to understand why the coordinates aren't working as they did for cagnulein/QZCompanionNordictrackTreadmill#65
Could you please check if the screen layout and coordinates of your treadmill is the same of the one on that post?
Also try to start the treadmill (so the speed is greater than 0) and try to do a plus action from QZ, it could be that the transition from 0 to 0.5 could be wrong. Also you can force to do a 1 km/h increment instead of a 0.5km/h in the treadmill settings, but we need to understand the root cause

**Comment by cagnulein** [comment] 2023-12-29 06:15
yes qz can have auto incline and auto speed on peloton workout!
before using auto speed it's better to check that you are able to change
speed and incline correctly via qz tiles without peloton. are you able to
do so?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 29 dic 2023 alle 05:43 Cwawra13 ***@***.***> ha
scritto:

**Comment by Cwawra13** [comment] 2023-12-29 12:45
I can change speed using qz tiles I can not change incline using qz tilesSent from my iPhoneOn Dec 28, 2023, at 11:15 PM, Roberto Viola ***@***.***> wrote:﻿
yes qz can have auto incline and auto speed on peloton workout!

before using auto speed it's better to check that you are able to change

speed and incline correctly via qz tiles without peloton. are you able to

do so?



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno ven 29 dic 2023 alle 05:43 Cwawra13 ***@***.***> ha

scritto:

**Comment by cagnulein** [comment] 2023-12-29 13:02
@Cwawra13 what happens for the incline? do you see a touch event on treadmill screen?

**Comment by Cwawra13** [comment] 2023-12-29 16:26
There is a touch event on the upper portion of the screen, but not on the
left hand side where the incline is.

Thanks!

**Comment by cagnulein** [comment] 2023-12-29 16:28
ok so probably your touchscreen is different from the one that I added. Could you please use this script to collect a screenshot of your tablet in the manual window? https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-screenshot.bat

**Comment by Cwawra13** [comment] 2023-12-30 03:20
Would this work? Sent from my iPhoneOn Dec 29, 2023, at 9:28 AM, Roberto Viola ***@***.***> wrote:﻿
ok so probably your touchscreen is different from the one that I added. Could you please use this script to collect a screenshot of your tablet in the manual window? https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-screenshot.bat

**Comment by Cwawra13** [comment] 2023-12-30 03:22
I also discovered that when  use incline on qz it adjusts the speed, not the incline. Sent from my iPhoneOn Dec 29, 2023, at 8:20 PM, Carolyn Wawra ***@***.***> wrote:﻿ Would this work? <image0.jpeg>Sent from my iPhoneOn Dec 29, 2023, at 9:28 AM, Roberto Viola ***@***.***> wrote:﻿
ok so probably your touchscreen is different from the one that I added. Could you please use this script to collect a screenshot of your tablet in the manual window? https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-screenshot.bat

**Comment by Cwawra13** [comment] 2023-12-30 03:35
﻿Attached is a screenshot using the script you provided. Sent from my iPhoneOn Dec 29, 2023, at 8:22 PM, Carolyn Wawra ***@***.***> wrote:﻿I also discovered that when  use incline on qz it adjusts the speed, not the incline. Sent from my iPhoneOn Dec 29, 2023, at 8:20 PM, Carolyn Wawra ***@***.***> wrote:﻿ Would this work? <image0.jpeg>Sent from my iPhoneOn Dec 29, 2023, at 9:28 AM, Roberto Viola ***@***.***> wrote:﻿
ok so probably your touchscreen is different from the one that I added. Could you please use this script to collect a screenshot of your tablet in the manual window? https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-screenshot.bat

**Comment by cagnulein** [comment] 2023-12-30 06:25
hi @Cwawra13 i can't see the images, you have to push them in github directly. thanks!

**Comment by cagnulein** [comment] 2023-12-30 09:26
> I also discovered that when  use incline on qz it adjusts the speed, not the incline.

that's because this setting is enabled "Simulate Inclinatin with Speed".
Maybe that's the issue that you're facing?

**Comment by Cwawra13** [comment] 2023-12-30 15:02
![12-29-2023 - 2033 - NordicTrackX22i png](https://github.com/cagnulein/qdomyos-zwift/assets/154957510/adb522b7-9082-4a87-abf8-3a6095f5681a)

**Comment by Cwawra13** [comment] 2023-12-30 15:02
![IMG_5792](https://github.com/cagnulein/qdomyos-zwift/assets/154957510/12c1583f-ed31-4ea5-b840-73fab0f55c63)

**Comment by cagnulein** [comment] 2023-12-30 15:32
> > I also discovered that when  use incline on qz it adjusts the speed, not the incline.
> 
> 
> 
> that's because this setting is enabled "Simulate Inclinatin with Speed".
> 
> Maybe that's the issue that you're facing?

@Cwawra13 did you try this?

**Comment by jr128128** [comment] 2023-12-30 16:31
![Sat12-30-2023@10-31-02 16](https://github.com/cagnulein/qdomyos-zwift/assets/24399426/107ad482-06cf-41a2-a023-a553b2874dfd)

**Comment by jr128128** [comment] 2023-12-30 16:32
![Sat12-30-2023@10-32-15 15](https://github.com/cagnulein/qdomyos-zwift/assets/24399426/80be7db9-4d92-4893-a5b1-3ed6cf807521)

**Comment by cagnulein** [comment] 2023-12-30 16:33
@jr128128 please post this in your ticket not here :) thanks

**Comment by Cwawra13** [comment] 2023-12-30 21:31
Ah ha!

Yes, I changed this and that solved the problem.

Thank you!

**Comment by cagnulein** [comment] 2023-12-30 21:38
Glad it worked!
So we can close this?


Il giorno sab 30 dic 2023 alle 22:32 Cwawra13 ***@***.***> ha
scritto:

**Comment by Cwawra13** [comment] 2023-12-30 21:40
Yes, thank you SO MUCH for your help!!!

**Comment by cagnulein** [comment] 2023-12-30 22:07
thanks for the coffees! Highly appreciated!

**Closed** 2023-12-30 22:07 UTC
Labels: bug
