### ISSUE TITLE
[BUG] NordicTrack T8.5S App Tiles Don't Update, Speed/Incline Not Controlled

### ISSUE THREAD

**Issue by jasonweaver** [cagnulein/qdomyos-zwift#2023] opened 2024-01-21 14:41 UTC
**Describe the bug**
The app is configured and phone logs show data, but tiles don't update and tile controls don't effect treadmill

**To Reproduce**
Configure Treadmill App
Configure Phone App
Start iFit on Treadmill

**Expected behavior**
Display speed/incline on phone app tiles. Control treadmill speed/incline

**Smartphone (please complete the following information):**
 - Device: Pixel 8 Pro
 - OS: Android
 - Version: 14

**Append a debug log**

[phone_debug-Sun_Jan_21_08_28_05_2024.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/14001668/phone_debug-Sun_Jan_21_08_28_05_2024.log.txt)
[phone_debug-Sun_Jan_21_08_20_03_2024.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/14001669/phone_debug-Sun_Jan_21_08_20_03_2024.log.txt)
[treadmill_logcat.txt](https://github.com/cagnulein/qdomyos-zwift/files/14001672/treadmill_logcat.txt)

**Comment by cagnulein** [comment] 2024-01-21 14:42
hi thanks, i will check it asap, in the meantime check also this
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/wiki/Troubleshooting#i-installed-the-companion-app-but-i-cant-see-any-data-on-my-qz-app

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 21 gen 2024 alle ore 15:41 jasonweaver <
***@***.***> ha scritto:

**Comment by jasonweaver** [comment] 2024-01-21 14:50
Thanks.

Sliders enabled
No touch input displayed (display setting is enabled in developer settings)
Already in Play Store beta
Enable ADB Remote app setting, no change

**Comment by cagnulein** [comment] 2024-01-21 15:03
@jasonweaver ok log checked. the main issue is that the companion can't get any metrics from the device. Which device did you select in the companion? I can't see it? did you try with the C1750 and restart the treadmill?
also use this method if it still doesn't work https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559

**Comment by jasonweaver** [comment] 2024-01-21 16:28
Thanks. Originally, the treadmilll app was set for T 8.5S.

When I try C1750 there is no data displayed in the tiles.

When I try Grand Tour Pro, the tiles update sporadicially, but they generally don't match the actual speed/incline.

**Comment by cagnulein** [comment] 2024-01-21 16:29
ok please attach a adb logcat in the grand tour scenario and I will check it 

by the way did you try also the way of restoring the tablet and DON'T update ifit? that's the best way

**Comment by jasonweaver** [comment] 2024-01-21 16:47
Thanks. Here are the logs with inconsistent display, still no response to tile increase/decrease commands.

[treadmill_logcat_240121_1040.txt](https://github.com/cagnulein/qdomyos-zwift/files/14002058/treadmill_logcat_240121_1040.txt)
[phone_debug-Sun_Jan_21_10_40_00_2024.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/14002059/phone_debug-Sun_Jan_21_10_40_00_2024.log.txt)

I did a factory reset, but don't have an easy way to block the updates.

**Comment by cagnulein** [comment] 2024-01-21 16:52
to block the updates you have to remove the gateway from your wifi setting of the tablet.

for the metrics it seems that the companion was killed over and over

so let's try first the factory reset way to see if the companion works better in this way. anyway the ifit is logging the real speed of the belt not the target speed so that's why maybe you are saying that the values seems not correct. does it make sense to you?

**Comment by jasonweaver** [comment] 2024-01-21 16:57
I understand what you are saying, but I'm not saying it's not matching while the speed is changing. I'm saying I tried to increment speed +/-0.1 and the tile doesn't update after the treadmill is on the new speed.

**Comment by jasonweaver** [comment] 2024-01-21 18:07
Thanks for the continued help.

Factory reset, setup personalDNSfilter to block ifit-wolf.s3.amazonaws.com and ifit-wolf.s3-cdn.ifit.com, which makes iFit Admin fail to complete updates.

The tile displays are now accurate with the T8.5S configuration in the treadmill app, however no touches register when using the tile controls to +/- speed or incline.
[phone_debug-Sun_Jan_21_10_48_01_2024.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/14002263/phone_debug-Sun_Jan_21_10_48_01_2024.log.txt)
[treadmill_logcat_12_40.txt](https://github.com/cagnulein/qdomyos-zwift/files/14002278/treadmill_logcat_12_40.txt)

**Comment by cagnulein** [comment] 2024-01-21 18:09
great!

ok so now from adb try the command

adb shell input 100 200 300 400 200

and check if you can see a virtual touch on the screen

also are you using the grand tour device or the right device on the
companion?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 21 gen 2024 alle 19:07 jasonweaver ***@***.***>
ha scritto:

**Comment by jasonweaver** [comment] 2024-01-21 18:13
Using the correct device now

> jason@penguin:~$ adb shell input 100 200 300 400 200
> Error: Unknown command: 100

**Comment by cagnulein** [comment] 2024-01-21 18:14
ok sorry missing a piece

adb shell input swipe 100 200 300 400 200


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 21 gen 2024 alle 19:14 jasonweaver ***@***.***>
ha scritto:

**Comment by jasonweaver** [comment] 2024-01-21 18:17
Gotcha, Yes, that registered.

**Comment by cagnulein** [comment] 2024-01-21 18:19
ok so in qz try to enable the "adb remote" setting in the nordictrack setting and restart qz

check if you can see a touch event on the treadmill then when you change the inclination on qz even if it's a wrong coordinate on the touchscreen

let me know

**Comment by jasonweaver** [comment] 2024-01-21 18:22
Enable ADB Remote, but still no touch events.

**Comment by cagnulein** [comment] 2024-01-21 18:24
that's strange, could you please append a debug log in this scenario while you're pressing the inclination button on qz?

**Comment by jasonweaver** [comment] 2024-01-21 18:28
[phone_debug-Sun_Jan_21_12_25_05_2024.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/14002372/phone_debug-Sun_Jan_21_12_25_05_2024.log.txt)
[treadmill_logcat_12_26.txt](https://github.com/cagnulein/qdomyos-zwift/files/14002373/treadmill_logcat_12_26.txt)

**Comment by cagnulein** [comment] 2024-01-21 18:32
hi the log of the phone is truncated and i can't see the settings and the
init phase. could you please do it again?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 21 gen 2024 alle ore 19:28 jasonweaver <
***@***.***> ha scritto:

**Comment by jasonweaver** [comment] 2024-01-21 18:39
[phone_debug-Sun_Jan_21_12_37_51_2024.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/14002408/phone_debug-Sun_Jan_21_12_37_51_2024.log.txt)

**Comment by cagnulein** [comment] 2024-01-21 18:43
mmm there is no error at all.
the ip is right? 192.168.1.200

if you try to do manually these are working from your pc?

adb shell input swipe 1845 779 1845 718 200
adb shell input swipe 75 714 75 729 200

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 21 gen 2024 alle ore 19:39 jasonweaver <
***@***.***> ha scritto:

**Comment by jasonweaver** [comment] 2024-01-21 18:56
adb shell input swipe 75 714 75 729 200
registers an event below the incline slider

adb shell input swipe 1845 779 1845 718 200
does not register

phone +/- speed and +/- incline
does not register

**Comment by cagnulein** [comment] 2024-01-21 19:38
> adb shell input swipe 75 714 75 729 200
> registers an event below the incline slider

ok so are you sure that from the qz inclination tile you don't see the same effect of this line?
if so we need to understand if there is something on the adb connection from your android device that doesn't work. in order to do so i need a bug report from your phone (instead of the classic debug log from qz) while you're trying to change the inclination. Are you able to do so?

**Comment by jasonweaver** [comment] 2024-01-22 01:11
[bugreport-gts9uwifixx-UP1A.231005.007-2024-01-21-19-06-34.zip](https://github.com/cagnulein/qdomyos-zwift/files/14003491/bugreport-gts9uwifixx-UP1A.231005.007-2024-01-21-19-06-34.zip)
I think this is what you're asking to review.

For what it's worth. I tried another Android 14 devices, and Android 10 device, and tested the Windows 11 app, and none registered any events.

**Comment by cagnulein** [comment] 2024-01-22 07:20
ok this the issue

`sendCommand ADB is not connected!`

i'm checking it deeply to find the root cause

**Comment by cagnulein** [comment] 2024-01-22 07:24
@jasonweaver is possible that when you were running this session the adb session was already in progress on the pc? as far as i know these treadmills are allowing only 1 adb connection at a time. I guess it's the only explanation. Maybe try to turn it off

you can also try this app https://play.google.com/store/apps/details?id=com.cgutman.androidremotedebugger&hl=it&gl=US to check if you can connect with this to the treadmill from your android 14 device

let me know!

**Comment by cagnulein** [comment] 2024-01-22 13:27
@jasonweaver great! yes! now i need to set the right coordinates. I will give you the formula here to calcualte the coordinates in order to validate them. I will be back here in a couple of hours

**Comment by cagnulein** [comment] 2024-01-22 13:39
can you validate this formula trying to the treadmill directly?
the last* variables are the value about the current value on the treadmill
the request ones are the value received from qz (qz has everything in km/h)
i suggest to start with the inclination, it easier.
let me know

```
x inclination: 78
min inclination: 610 / 0%
max inclination: 225 / 12%

y1Inclination = 610 - (int) ((QZService.lastInclinationFloat) * 32.08);
y2 = y1Inclination - (int) ((reqInclination - QZService.lastInclinationFloat) * 32.08);

adb shell input swipe 78 y1Inclination 78 y2 200

x speed: 1206
min speed: 600 / 1 mi/h
max speed: 225 / 12 mi/h

y1Speed = 600 - (int) (((QZService.lastSpeedFloat * 0.621371) - 1) * 34.10);
y2 = y1Speed - (int) (((reqSpeed * 0.621371) - (QZService.lastSpeedFloat * 0.621371)) * 34.10);

adb shell input swipe 1206 y1Speed 1206 y2 200
```

**Comment by jasonweaver** [comment] 2024-01-22 15:32
Thanks. I will try this tomorrow.

**Comment by jasonweaver** [comment] 2024-01-26 14:28
x inclination: 78
min inclination: 620 / 0%
max inclination: 225 / 12%

x speed: 1206
min speed: 600 / 1 mi/h
max speed: 225 / 12 mi/h

**Comment by cagnulein** [comment] 2024-01-26 15:06
@jasonweaver great! did you also try this new setting in the adb formula?

**Comment by jasonweaver** [comment] 2024-01-26 21:07
Yep, validated through adb

**Comment by cagnulein** [comment] 2024-01-26 21:12
ok i will change them asap

**Comment by cagnulein** [comment] 2024-01-28 07:52
done @jasonweaver 
https://github.com/cagnulein/qdomyos-zwift/actions/runs/7684333005
select the new t.85s setting in the proform/nordictrack treadmill settings and leave it enable the adb remote of course

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by jasonweaver** [comment] 2024-01-28 16:59
Thanks a lot @cagnulein the trial app works great, except the speed +/- is changing the value by 0.3 mph, not 0.1 mph. Can that be adjusted in the formula?

**Comment by cagnulein** [comment] 2024-01-28 17:15
it should be possible, i have to check the code in the next days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 28 gen 2024 alle 17:59 jasonweaver ***@***.***>
ha scritto:

**Comment by cagnulein** [comment] 2024-01-28 18:06
@jasonweaver i checked the code and i don't any limitation for the 0.1 step. are you talking about the plus and minus on the speed tile of qz? if so you can change that behaviour from the treadmill settings, speed step. let me know (qz is using always km/h on the engine, so i'm doing the conversion, so there could be any decimal issue with 0.1 mi/h)

let me know

**Comment by jasonweaver** [comment] 2024-01-28 19:46
Yes, I am talking about the plus/minus controls on the speed tile. No matter what I change the Speed Step setting to under Treadmill Settings, (after restarting) the increase/decrease is 0.3mi/0.5km per hour.

**Comment by cagnulein** [comment] 2024-01-28 19:59
i guess i fixed now
https://github.com/cagnulein/qdomyos-zwift/actions/runs/7688057954


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 28 gen 2024 alle 20:46 jasonweaver ***@***.***>
ha scritto:

**Comment by cagnulein** [comment] 2024-01-28 20:11
sorry this one https://github.com/cagnulein/qdomyos-zwift/actions/runs/7688137279

**Comment by jasonweaver** [comment] 2024-02-03 18:57
Hey @cagnulein I have 2.16.40 now from Google Play, but the toggle for T 8.5s isn't showing in the Treadmill Settings from that install, so it's not working

**Comment by cagnulein** [comment] 2024-02-03 19:00
@jasonweaver it's under the new combobox 

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/3a800a9a-2d7a-4a41-b283-7cd0bdde33b6)

**Comment by jasonweaver** [comment] 2024-02-03 20:55
Not in Android?

![1000002235](https://github.com/cagnulein/qdomyos-zwift/assets/5666694/bc0ee681-451f-4ad2-881b-063241e3426f)

**Comment by cagnulein** [comment] 2024-02-03 20:57
i didn't update the version yet on the store with the modification that i did for you, that's why :) i will do in the next days

**Comment by cagnulein** [comment] 2024-02-04 16:13
hi @jasonweaver i don't remember if i had already add you to the private beta group. if not send me an email with your google email account to Roberto.viola83 at Gmail.com indicating this ticket and I will add you!

**Comment by cagnulein** [comment] 2024-02-05 14:12
Update available in the store

**Closed** 2024-02-05 20:50 UTC
Labels: bug

**Comment by cagnulein** [comment] 2024-02-05 20:55
amazing! remember to support qz on patreon or buymeacoffee to keep this
alive!

thanks!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 5 feb 2024 alle 21:51 jasonweaver ***@***.***>
ha scritto:
