### ISSUE TITLE
t900c pi0w crash within 15 seconds or so

### ISSUE THREAD

**Issue by rickoneeleven** [cagnulein/qdomyos-zwift#58] opened 2020-11-22 09:20 UTC
not sure if this is useful, i restarted it afterwards and it worked, but it was only a short session, 30 minutes

[debug-Sun Nov 22 08_33_40 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5579218/debug-Sun.Nov.22.08_33_40.2020.log)

initially it crashed within a few seconds, log above

**Comment by cagnulein** [comment] 2020-11-22 09:40
i will check it today, thanks!

**Comment by cagnulein** [comment] 2020-11-22 16:03
i checked the log: it seems that simply the pi lost the connection from the T900c. Anyway it should not crash. I will try to simulate the same thing here tomorrow hoping to see the same crash.

**Comment by cagnulein** [comment] 2020-11-23 09:03
this morning i tried to replicate this issue without success. I put the bridge on my notebook, i connected the bridge to my treadmill and then i started to move around my house losting and gaining connection again.
So it's something different.
If you can replicate it with "enough" simplicity, please try run gdb and tell post me the gdb log (use bt command to see the full stack trace).
Thanks

**Comment by rickoneeleven** [comment] 2020-11-23 09:51
i'll see, that's the first time it has crashed so quickly. i'll see how it is the rest of the week.

_the auto restart/reconnect feature would have helped though_ :rofl:

**Comment by rickoneeleven** [comment] 2020-11-25 14:09
is this okay? i've not try to run the program yet

git pull
cd src
qmake
make -j4
![mstsc_KfkhdyXISj](https://user-images.githubusercontent.com/8156878/100238221-dba22a00-2f27-11eb-9abe-8f952542fa4b.png)

**Comment by cagnulein** [comment] 2020-11-27 19:27
@rickoneeleven when you have spare time could you please try a thing: 
1. Turn the treadmill on; just on, not running
2. Connect the pi0w to a power bank: in this way you could move the pi0w around the house
3. Connect the pi0w to the treadmill
4. Move it around the house until you will lose connection to the treadmill
5. Go again where the treadmill is visibile

If with these 5 steps you will reproduce the segfault, we can debug it with gdb. I guess it's a stupid line of code, but i can't reproduce on my own.

Have a good Friday night and don't drink too much, tomorrow you will have to debug :D

**Comment by rickoneeleven** [comment] 2020-11-27 19:52
:laughing: my wife's going to kill you, i'll have to buy another toy - a power bank!!!!! - actually, to be fair i've already got one for my phone from when i'd go on big walks, never even thought of using that to power pi :laughing: i'll give it a go tomorrow hopefully :crossed_fingers:

**Comment by cagnulein** [comment] 2020-12-17 11:01
i'm closing this one, if it happens again feel free to reopen it

**Closed by cagnulein** 2020-12-17 11:01 UTC
Labels: linux, t900c
