### ISSUE TITLE
Latest beta upgrade has regressed

### ISSUE THREAD

**Issue by venkateshks** [cagnulein/qdomyos-zwift#112] opened 2021-01-08 23:24 UTC
With latest update (updated on Jan 6), with support for HRM and Virtual device. It has become very difficult for the power meter to be discovered by zwift. I also turn on the relaxed bluetooth setting.
With the latest update, I have the "Relaxed Bluetooth" and "Virtual Device" both turned on. Else the app is not discovered by Zwift. Even when discovered, there are multiple disconnects. It almost takes about 15 minutes for me to get zwift going.

Prior to this update, just the "Relaxed Bluetooth" turned on was good enough. And in one or two attempts everything would work.

**Comment by cagnulein** [comment] 2021-01-09 04:28
Which version are you currently using? Could you please try to remove you
from beta tester and see if the stable version works?
The problem is that you don't see the bridge at all on zwift? Did you try
with nrfconnect?

Il sab 9 gen 2021, 00:24 Venkatesh Sharma <notifications@github.com> ha
scritto:

**Comment by cagnulein** [comment] 2021-01-14 15:33
#90 any update @venkateshks ?

**Comment by venkateshks** [comment] 2021-01-14 16:17
I moved off beta and the problem disappeared

**Comment by cagnulein** [comment] 2021-01-14 16:28
ok but i guess we have to understand it otherwise when the new version will pushed to production you have the issue again. if you want we could test version to version and understand where the issue started @venkateshks

**Comment by venkateshks** [comment] 2021-01-15 02:45
Spoke too soon. I had trouble today getting on. Took several attempts.

**Comment by cagnulein** [comment] 2021-01-15 05:20
Infact I think i didn't touch anything on that side. I guess you have other
correlated issue. Could you try to do some troubleshooting?
If you need realtime help I'm available by whatsapp and Messenger

Il ven 15 gen 2021, 03:45 Venkatesh Sharma <notifications@github.com> ha
scritto:

**Comment by cagnulein** [comment] 2021-01-25 09:17
any news @venkateshks could we close this?

**Comment by venkateshks** [comment] 2021-01-25 16:14
There is some regression. There was a window between when you introduced
"troubled bluetooth" setting and befornyour introduced the "virtual device"
setting when zwift would work really well. Nowadays it is completely
unpredictable. Having said this, I am fine with this being closed.

**Comment by cagnulein** [comment] 2021-01-25 16:17
@venkateshks are you still using it? i don't know if the google play offers to the beta tester to choose which version could use. i will check it

**Comment by cagnulein** [comment] 2021-01-25 16:18
@venkateshks ok i guess i found it. I can create a group only for you and we can "bisect" the versions. Are you ok with this? of course i need your time to test it :(

**Comment by venkateshks** [comment] 2021-01-26 01:51
Sure, happy to help

**Comment by cagnulein** [comment] 2021-01-26 06:42
@venkateshks ok i just push to the beta channel, just for you, the version 2.1.1
let's start from here. tell me if it is good or not.
Thanks

**Comment by cagnulein** [comment] 2021-08-04 09:22
@venkateshks i'm closing this one. if you still need help please reopen it :)

**Closed by cagnulein** 2021-08-04 09:22 UTC
