### ISSUE TITLE
Domyos Bike 500 - Econnected Snoop Log

### ISSUE THREAD

**Issue by firetrappe** [cagnulein/qdomyos-zwift#48] opened 2020-11-04 10:18 UTC
I connected my Bike 500 to the eConnected app to capture a very short Snoop log before I had to leave for work.

![Screenshot_20201104-082146](https://user-images.githubusercontent.com/66125348/98096926-36de8080-1e84-11eb-9036-9850c6629dbc.png)

I tried to maintain a steady cadence and change the resistance levels on the bike's console to get some sort of usable log.

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/5486989/btsnoop_hci.log)

One thing I did notice was that when eConnected opened and detected the bike, 'bluetooth' scrolled across the middle of the bike's console. I don't recall ever seeing that before :/

**Comment by cagnulein** [comment] 2020-11-04 10:49
@firetrappe ok, this snoop was very useful: infact, your bike is different from the @alpat59 and @kenands
i have to create a similar profile for this one. i will tell you when i'm ready

**Comment by cagnulein** [comment] 2020-11-04 14:00
@firetrappe i just submit a new commit.
I found several differencies from the other version ("changyow" is its name).

So please, test and send me the log generated from the bridge.

Please split the 2 issue:
1. is the display issue that this commit should fix (i hope, but i'm not really 100% confident yet)
2. the ipad issue

Here talk about only the first one, if the zwift ipad continues, try with other devices. If the problem is only on the ipad, please open a new issue.

Thanks, i hope that this release brings some good news :P

**Comment by firetrappe** [comment] 2020-11-04 14:43
@cagnulein Thank you so much for looking into this. 

I recognised the 'chagyow' name, but I couldn't remember where I had seen it before. Then I suddenly remembered....
![Screenshot_20201104-143720 (Medium)](https://user-images.githubusercontent.com/66125348/98124958-be8bb580-1eab-11eb-80b8-bd93cce4861e.png)

This is the app on my iPad which works with my Reebok Treadmill!

My treadmill has never been powered on while testing the bike.

**Comment by cagnulein** [comment] 2020-11-04 14:46
@firetrappe hahah just to be clear: the chagyow bike is the @kenands one. Yours has provided by telink.
So your reebok treadmill has been built by the same company of the domyos treadmill. There is a lot of possibilities that reebok treadmill has the same protocol (and maybe the same firmware) of the domyos one.

You should definitely try :D (open another issue of course in case :P)

**Comment by firetrappe** [comment] 2020-11-04 14:54
@cagnulein  Wow lol. I was getting REALLY confused there for a minute! 
That's really interesting though. 

I'll pull the latest commit and test later tonight :+1:

**Comment by firetrappe** [comment] 2020-11-04 20:26
@cagnulein I just tested the latest commit.

The bike console exhibits the same behaviour as previously unfortunately. Log attached.

[debug-Wed Nov 4 20-20-13 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5490325/debug-Wed.Nov.4.20-20-13.2020.log)

**Comment by cagnulein** [comment] 2020-11-04 20:33
@firetrappe no differences at ALL? unbelieavable :( tomorrow i will check the snoop again, i surely missed something this morning :(

**Comment by firetrappe** [comment] 2020-11-04 20:45
@cagnulein The console just showed the Bluetooth symbol and the resistance options again I'm afraid.

Would a snoop log from Kinomap be of any use?

**Comment by cagnulein** [comment] 2020-11-04 21:32
@firetrappe no i don't think so. I guess the file you collected is enough, I just missed something stupid I hope.

Have a good night

**Comment by cagnulein** [comment] 2020-11-05 08:24
@firetrappe just to be sure: in yout snoop log i saw a lot of packet to a "nintendo" device. Is it known? Because i'm start thinking that you have 2 endpoint in your bike, maybe with 2 different bluetooth device

the mac address of this device is [Destination: Nintendo_c9:65:d2 (7c:bb:8a:c9:65:d2)]

Do you recognize it?

**Comment by cagnulein** [comment] 2020-11-05 08:36
@firetrappe i commit a new one. I tried to be more on the snoop way. give it a try ;)

**Comment by firetrappe** [comment] 2020-11-05 10:17
> @firetrappe just to be sure: in your snoop log i saw a lot of packet to a "nintendo" device. Is it known? Because i'm start thinking that you have 2 endpoint in your bike, maybe with 2 different bluetooth device
> 
> the mac address of this device is [Destination: Nintendo_c9:65:d2 (7c:bb:8a:c9:65:d2)]
> 
> Do you recognize it?

@cagnulein we don't have any nintendo consoles connected. However, I just used nRF Connect to try and locate it.
It appears that it is one of the kids bluetooth devices they use when they play Pokemon Go :/

**Comment by firetrappe** [comment] 2020-11-05 17:19
Just got home and pulled latest commit.

Similar experience to yesterday - Bike console just shows BT and Resistance.
I did open zwift just to see what happened. Zwift detected the bridge, but no avatar movment as expected :(

[debug-Thu Nov 5 17-11-43 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5495910/debug-Thu.Nov.5.17-11-43.2020.log)

**Comment by cagnulein** [comment] 2020-11-05 18:36
> @cagnulein I Just got home and pulled latest commit.
> 
> Similar experience to yesterday - Bike console just shows BT and Resistance.

Tomorrow I will be more free than today and I will triple check it. Are you 100% sure that during the snoop log the console has populate by data?

> I did open zwift just to see what happened. Zwift detected the bridge, but no avatar movment as expected :(

Didn't you try yet with another zwift device?

**Comment by firetrappe** [comment] 2020-11-05 23:06
@cagnulein Thank you for persisting with this.

To try and help I have created 2 more snoop logs. 1 with Econnected and 1 with Kinomap.
Both apps show different data on the bike console.

I also created a video of each session which I thought might help.

Kinomap Video: https://youtu.be/K8tKrRfpBKw
Kinomap Snoop Log: [kinomap btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/5497892/kinomap.btsnoop_hci.log)

Econnected Video: https://youtu.be/2WJgeZ9bGbc
Econnected Snoop Log: [econnected btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/5497901/econnected.btsnoop_hci.log)

**Comment by cagnulein** [comment] 2020-11-06 05:00
@firetrappe wonderful debug activity :) I will check it

**Comment by cagnulein** [comment] 2020-11-06 06:49
@firetrappe i checked the 2 snoop logs but in both of them there aren't any trace of connection to the TM, only with a garmin smartwatch. I'm sorry but they are useless :( could you please retry? if you want, before send me them, you could double check them with wireshark looking for your treadmill mac address (as your very first snoop log has)

**Comment by firetrappe** [comment] 2020-11-06 09:20
@cagnulein Ah Damn! That's disappointing. The only thing I can remember doing differently for those logs was disabling and re-enabling bt after enabling HCI snooping, then restarting the phone. I'll get wireshark as suggested to check the logs.

Would you like new videos of each session, or are they not so important now?

I'm at home this afternoon, so I'll see what I can do when i'm a bit less tired!

**Comment by cagnulein** [comment] 2020-11-06 09:35
> @cagnulein Ah Damn! That's disappointing. The only thing I can remember doing differently for those logs was disabling and re-enabling bt after enabling HCI snooping, then restarting the phone. I'll get wireshark as suggested to check the logs.

;)

> Would you like new videos of each session, or are they not so important now?

they were useful, but now i'm ok, you shouldn't take it.
 
> I'm at home this afternoon, so I'll see what I can do when i'm a bit less tired!

ihihih ok

> Edit: Ah, I figured out what I did wrong! I ran the snoop on my phone and the apps on my ipad :/ Thank you @rickoneeleven for making the same mistake :)

hihihi ok!

**Comment by rickoneeleven** [comment] 2020-11-06 09:45
@firetrappe it's what I do best :laughing:

**Comment by firetrappe** [comment] 2020-11-06 14:46
@cagnulein Ok, lets try this again!

Econnected Snoop: [econnected v2 btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/5501784/econnected.v2.btsnoop_hci.log)

Kinomap Snoop: [Kinomap v2 btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/5501785/Kinomap.v2.btsnoop_hci.log)

Both sessions were similar; Open app, pedal to power on bike, connect to app, pedal slowly increasing from resistance=1 to resistance=15

Both logs checked in Wireshark for 'Telink' entry ;) 🤞

**Comment by cagnulein** [comment] 2020-11-06 15:05
@firetrappe ok, i followed the kinomap snoop as is. it's very simple, much simple than before. if it doesn't work, i will start looking for another job 🤣 

please pull it, compile it, and check the display. send me the log in case it doesn't work

**Comment by firetrappe** [comment] 2020-11-06 15:25
@cagnulein Please don't look for another job 😢 

[debug-Fri Nov 6 15-10-36 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5501940/debug-Fri.Nov.6.15-10-36.2020.log)

The new pull compiled and executed without any issues. The display had the usual reaction. 
I opened Zwift on my Pixel and the bike wasn't detected. Then about 30 seconds later the console display changed to this :

![PXL_20201106_151346172 (Phone)](https://user-images.githubusercontent.com/66125348/98383035-e31a9580-2043-11eb-98dd-d79c3797a4f2.jpg)

The console showed the additioinal fields, but pedaling didn't change any of the displayed values.
I checked the bridge and the code was still running.

**Comment by cagnulein** [comment] 2020-11-06 15:28
Ok it's a good sign! Now I'm out with my dog, I will check it later. For zwift, did you try to restart the bridge?
Another device?

**Comment by firetrappe** [comment] 2020-11-06 15:34
@cagnulein I'll reboot the bridge and then test with iP**

Enjoy your walk 🐶

**Comment by cagnulein** [comment] 2020-11-06 15:35
Don't reboot, just restart my script. It's different

**Comment by firetrappe** [comment] 2020-11-06 15:53
@cagnulein I restarted the script. The console reacted as before. Loaded Zwift on the iPad and it automatically detected the bridge. While pedalling all fields remained at zero though:

![IMG_0329 (Phone)](https://user-images.githubusercontent.com/66125348/98385992-933dcd80-2047-11eb-9674-2fcf4d38edac.PNG)

I disabled bt on iPad, stopped and restarted your script, opened Zwift on the Pixel but it couldn't detect the bridge.

nRF Connect now appears to scan and detect the bridge and the bike simulaneously.

**Comment by cagnulein** [comment] 2020-11-06 21:23
If nrf connects detect it it's very strange. Seems a filter on services on zwift side. 
But I can't understand why it happens only to someone.
Could you try to connect with nrfconnect and send me a snapshot of the services from the Pixel?

**Comment by firetrappe** [comment] 2020-11-06 21:51
@cagnulein I don't understand it either 😞 

I just powered on the bike and then started the bridge again on the pi. 
nRF scans and shows the bike until the bridge connects. As soon at the bridge connects I get this:

![PXL_20201106_214213744 (Phone)](https://user-images.githubusercontent.com/66125348/98418009-ed578680-2079-11eb-9586-90ff04ce98ae.jpg)

And then neither show on nRF:

![Screenshot_20201106-214135 (Phone)](https://user-images.githubusercontent.com/66125348/98418045-0102ed00-207a-11eb-987a-7f3194978a9d.png)

🤷‍♂️

[debug-Fri Nov 6 21-38-23 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5503675/debug-Fri.Nov.6.21-38-23.2020.log)

**Comment by firetrappe** [comment] 2020-11-06 22:08
It's crazy that I had a perfect session on my first attempt 5 days ago:
https://github.com/cagnulein/qdomyos-zwift/issues/22#issuecomment-720365510

Every session since then it has failed 😢

**Comment by cagnulein** [comment] 2020-11-07 04:04
> It's crazy that I had a perfect session on my first attempt 5 days ago:
> [#22 (comment)](https://github.com/cagnulein/qdomyos-zwift/issues/22#issuecomment-720365510)
> 
> https://strava.app.link/CcwnhQrFcbb
> 
> Every session since then it has failed 😢

oh! i didn't remember! i have a deal for you: why don't you checkout that commit, check if everything works again, and commit after commit, you will try when error appears? i guess it's only effective way.

**Comment by cagnulein** [comment] 2020-11-07 12:07
@firetrappe if you want there is a useful command on git, called git bisect

**Comment by firetrappe** [comment] 2020-11-07 12:50
Ok, I did the following:

`git checkout 209da708c9833f25207d8252b6ce14ef4606c782`
`cd src`
`qmake`
`make -j4`

This commit worked first time - as before 🎉 
The bluetooth settings on the iPad showed the bridge as an available device.
Starting Zwift on the iPad I had a popup asking me to connect/pair.

The bike console populated with data, but none of the fields updated in realtime:

![PXL_20201107_111823166 (Phone)](https://user-images.githubusercontent.com/66125348/98440133-c5563a80-20ee-11eb-8719-4c5e53cb1b0e.jpg)

The fields did update after I went back the the Zwift menu; the time updated from 1:01 to 3:xx.

[debug-Sat Nov 7 11-14-09 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5504639/debug-Sat.Nov.7.11-14-09.2020.log)


Then I stopped the script and waited for the bike to power off. 
I started the bridge again and went through the same steps. This time the iPad didn't detect the bridge and therefore Zwift didn't work 😞    

[debug-Sat Nov 7 11-33-20 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5504662/debug-Sat.Nov.7.11-33-20.2020.log)

It seems that I have to start the bridge and then pedal to power on the bike quickly before the script gets a Seg Fault. If the bike is already powered then it doesn't work. If the bridge is already running then the bike appears to connect (console changes to BT + Resistance display only), but Zwift/iPad/nRF Connect can't detect anything.
Unfortunately I can't seem to replicate this every time.

This was my latest attempt:
[debug-Sat Nov 7 12-35-43 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5504730/debug-Sat.Nov.7.12-35-43.2020.log)

I do seem to get this notification on the iPad after a successful session:
![IMG_0330 (Phone)](https://user-images.githubusercontent.com/66125348/98441509-b70c1c80-20f6-11eb-8f24-c866e0c846ff.PNG)

But as i've mentioned before, there doesn't appear to be a method to remove known devices in Zwift (unpair?)

Apologies for the long post. I'm just trying to document everything i'm testing for my own future reference.

**Comment by cagnulein** [comment] 2020-11-07 13:24
> It seems that I have to start the bridge and then pedal to power on the bike quickly before the script gets a Seg Fault. If the bike is already powered then it doesn't work. If the bridge is already running then the bike appears to connect (console changes to BT + Resistance display only), but Zwift/iPad/nRF Connect can't detect anything.
> Unfortunately I can't seem to replicate this every time.

i've already fix this issue in the next commits. but we have to focus on an issue at a time. try to discover which is the commit that break everything. When we will have understood which is the root issue, we will fix zwift issue too.

**Comment by firetrappe** [comment] 2020-11-07 14:18
> > It seems that I have to start the bridge and then pedal to power on the bike quickly before the script gets a Seg Fault. If the bike is already powered then it doesn't work. If the bridge is already running then the bike appears to connect (console changes to BT + Resistance display only), but Zwift/iPad/nRF Connect can't detect anything.
> > Unfortunately I can't seem to replicate this every time.
> 
> i've already fix this issue in the next commits. but we have to focus on an issue at a time. try to discover which is the commit that break everything. When we will have understood which is the root issue, we will fix zwift issue too.

Thanks for your continued help. I will test some more.

I'm not sure how to get back to the latest version now. Now I have used `checkout` I get a message telling me to 'specify which branch you want to merge with'

**Comment by rickoneeleven** [comment] 2020-11-07 14:40
@firetrappe

Checkout master
Git pull
Qmake
Make - j4

To get back to latest

**Comment by cagnulein** [comment] 2020-11-07 14:50
@firetrappe try to run the next one instead of the lastest and so on

**Comment by cagnulein** [comment] 2020-11-07 19:37
Uh ok @firetrappe i will investigate it, I hope it will do with the treadmill too

**Comment by cagnulein** [comment] 2020-11-07 19:55
@firetrappe you were right, I applied only to treadmill 27f207b022acec6fb8abb6c9cd7d1b3808460df3

**Comment by firetrappe** [comment] 2020-11-07 20:24
> @firetrappe you were right, I applied only to treadmill [27f207b](https://github.com/cagnulein/qdomyos-zwift/commit/27f207b022acec6fb8abb6c9cd7d1b3808460df3)

Great, thanks!

I have just checked out `209da70` again (the original one that worked this morning too) just to test before I move to other commits. I can't get it to work. Should I look at older or newer commits? I'm not sure what I should be doing now :/

[debug-Sat Nov 7 20-19-11 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5505380/debug-Sat.Nov.7.20-19-11.2020.log)

**Comment by rickoneeleven** [comment] 2020-11-07 20:25
After a seg fault I always had to reboot

**Comment by firetrappe** [comment] 2020-11-07 20:26
Ok ok, i'll try that, thanks! 👍 thumb:

**Comment by cagnulein** [comment] 2020-11-07 20:28
> Ok ok, i'll try that, thanks! 👍 

I didn't apply to bike yet, I will do it tomorrow. Have a good night

**Comment by cagnulein** [comment] 2020-11-08 05:21
ok @firetrappe did it. you could try

**Comment by firetrappe** [comment] 2020-11-08 10:05
> ok @firetrappe did it. you could try

Good morning!

I just tested the latest commit. No Seg Fault. Great! That makes life so much easier, especially with autostart 🥳 
I kept the bridge running and let the bike power off, then pedalled the bike to power it on the bridge detects it again.

**Comment by cagnulein** [comment] 2020-11-08 10:50
Awesome! @firetrappe remember, when you will have time, to bisect the commits in order to understand if I had introduced some issue in times. Thanks

**Comment by firetrappe** [comment] 2020-11-08 11:25
@cagnulein I will research how to use the `bisect` command. 

I think with the latest commit my autostart isn't working as it should. CTRL+C closes the terminal now and doesn't create a log. I will have to stop using it for now.

The current situation using nRF to monitor connections is as follows-
Bike is detected when powered on.
Bike disappears and Domyos Bridge appears when the bridge detects the bike.
Bridge disappears about 10 seconds later.

[debug-Sun Nov 8 10-39-55 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5506244/debug-Sun.Nov.8.10-39-55.2020.log)

**Comment by cagnulein** [comment] 2020-11-08 11:30
@firetrappe by chance your issue is similar to this https://youtu.be/gaB2eUHPIm8 ? Check the part of the video when the icon says "nessun segnale" (no signal)

**Comment by firetrappe** [comment] 2020-11-08 12:39
> @firetrappe by chance your issue is similar to this https://youtu.be/gaB2eUHPIm8 ? Check the part of the video when the icon says "nessun segnale" (no signal)

@cagnulein Great video! You have very good English 👍 

I think my issue is different. Here's a video showing what is happening at the moment. Maybe you can spot something that I am doing wrong?

https://youtu.be/ckWsc2BW6W4

**Comment by cagnulein** [comment] 2020-11-08 13:00
I guess something is trying to connect with the bridge, is why it disappears. I will add some debug print to understand it. Does it happens the same even with your bluetooth iPad off?

**Comment by firetrappe** [comment] 2020-11-08 13:09
> I guess something is trying to connect with the bridge, is why it disappears. I will add some debug print to understand it. Does it happens the same even with your bluetooth iPad off?

Thank you so much for investigating.

I just tested again with the iPad in airplane mode with bluetooth off. The bridge still disappears.

**Comment by cagnulein** [comment] 2020-11-08 13:21
@firetrappe in the meanwhile could you please try to add the parameter -only-virtualbike ?

**Comment by firetrappe** [comment] 2020-11-08 13:41
> @firetrappe in the meanwhile could you please try to add the parameter -only-virtualbike ?

@cagnulein I just tested that. The bridge shows up in nRF continuously until I reboot the Pi

**Comment by cagnulein** [comment] 2020-11-08 13:45
So Is a issue when the bluetooth adaptor acts as central - and peripheral at the same time. Do you have a rasp 3b isn't it? The same model of @rickoneeleven 
But you said also that the old commit works so it can't be an hardware issue.

So, we're back to the old question: bisect! :D

**Comment by firetrappe** [comment] 2020-11-08 14:01
> So Is a issue when the bluetooth adaptor acts as central - and peripheral at the same time. Do you have a rasp 3b isn't it? The same model of @rickoneeleven
> But you said also that the old commit works so it can't be an hardware issue.
> 
> So, we're back to the old question: bisect! :D

Yeah, 3b.

The old commit worked twice, even though I must have tested it 50 times. It seems like if the timing of the connections isn't perfect then it doesn't work.

**Comment by bvalat** [comment] 2020-11-08 14:18
It seems that i have same bike/console as firetrappe.
If needed i can do some test.

**Comment by cagnulein** [comment] 2020-11-08 14:26
> > So Is a issue when the bluetooth adaptor acts as central - and peripheral at the same time. Do you have a rasp 3b isn't it? The same model of @rickoneeleven
> > But you said also that the old commit works so it can't be an hardware issue.
> > 
> > So, we're back to the old question: bisect! :D
> 
> Yeah, 3b.
> 
> The old commit worked twice, even though I must have tested it 50 times. It seems like if the timing of the connections isn't perfect then it doesn't work.

There is a 100,100 on the code of the virtual bike. They're the milliseconds of advertising. Try to change them, for example, 1000,1000 and check if something change.

**Comment by cagnulein** [comment] 2020-11-08 14:26
> It seems that i have same bike/console as firetrappe.
> If needed i can do some test.

Welcome aboard! Yeah absolutely! If you can do a quick test...

**Comment by cagnulein** [comment] 2020-11-08 19:01
@firetrappe as i promised i added a new debug log system with this commit https://github.com/cagnulein/qdomyos-zwift/commit/79f8942b06eb0a531f763fb2d283a24ea06cb4da
I hope that doesn't brake anything.

i should get more info about zwift issue.
Tomorrow will be an hard day, but the day after tomorrow i could check the logs that you will post :)

**Comment by firetrappe** [comment] 2020-11-08 19:05
> There is a 100,100 on the code of the virtual bike. They're the milliseconds of advertising. Try to change them, for example, 1000,1000 and check if something change.

@cagnulein Thanks for that suggestion. I tested with 1000,1000 and even 10000,10000. nRF detected the bridge for both attempts, although the 10000,10000 was very slow to detect, obviously.

**Comment by firetrappe** [comment] 2020-11-08 19:06
> It seems that i have same bike/console as firetrappe.
> If needed i can do some test.

@bvalat Brilliant! Thank you for joining. I am glad I am not the only one in the world with a different console 😄

**Comment by firetrappe** [comment] 2020-11-08 19:09
> @firetrappe as i promised i added a new debug log system with this commit [79f8942](https://github.com/cagnulein/qdomyos-zwift/commit/79f8942b06eb0a531f763fb2d283a24ea06cb4da)
> I hope that doesn't brake anything.
> 
> i should get more info about zwift issue.
> Tomorrow will be an hard day, but the day after tomorrow i could check the logs that you will post :)

Great, thank you for all your efforts. We will crack this thing!
I will checkout the new commit and hopefully the logs will show you something. 🤞

**Comment by cagnulein** [comment] 2020-11-08 19:13
> @cagnulein Thanks for that suggestion. I tested with 1000,1000 and even 10000,10000. nRF detected the bridge for both attempts, although the 10000,10000 was very slow to detect, obviously.

You mean that parameter improve the bridge connection? So maybe this is the root cause of the problem? Do I should re-put this value to default (1000, 1000)?

**Comment by firetrappe** [comment] 2020-11-08 19:18
> > @cagnulein Thanks for that suggestion. I tested with 1000,1000 and even 10000,10000. nRF detected the bridge for both attempts, although the 10000,10000 was very slow to detect, obviously.
> 
> You mean that parameter improve the bridge connection? So maybe this is the root cause of the problem? Do I should re-put this value to default (1000, 1000)?

Sorry, I only tested with -only-virtualbike
I will change to 1000,1000 and test with the bike.

**Comment by cagnulein** [comment] 2020-11-08 19:19
> Sorry, I only tested with -only-virtualbike
> I will change to 1000,1000 and test with the bike.

Ok, I'm really curious

**Comment by firetrappe** [comment] 2020-11-08 19:22
Here's a log file from your latest commit:
[debug-Sun Nov 8 19_19_38 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5507019/debug-Sun.Nov.8.19_19_38.2020.log)

Now I will change the .cpp file to 1000,1000 and test.

**Comment by firetrappe** [comment] 2020-11-08 19:28
I get the same result with 1000,1000 unfortunately. Bridge disappears.

Here's the log file for that session, just in case it's helpful:
[debug-Sun Nov 8 19_24_43 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5507025/debug-Sun.Nov.8.19_24_43.2020.log)

**Comment by cagnulein** [comment] 2020-11-08 19:34
Ok, if you haven't time to do a git bisect, do it manually, checking out commit by commit. It might be easier for you

I hope @bvalat has a different behavior so we can compare them

**Comment by firetrappe** [comment] 2020-11-08 19:38
Ok, I have a busy day tomorrow too, but I will see what I can do.
Do you recommend I start from the original commit I used, or start further back with an even older one?

I'm really looking forward to hearing how @bvalat gets on too.

**Comment by cagnulein** [comment] 2020-11-08 19:51
Start from the original commit that you used in the past and that worked

**Comment by rickoneeleven** [comment] 2020-11-08 20:02
If i understood firetrap correctly, and I may have not. Even the one that "worked" only did so two in fifty times, so there may have never been a "stable"

**Comment by cagnulein** [comment] 2020-11-08 20:07
> If i understood firetrap correctly, and I may have not. Even the one that "worked" only did so two in fifty times, so there may have never been a "stable" 

Yes I understood it too, but 2 times it's better than nothing. I guess this is a typical scenario where you have more than one issue and it's a really nightmare to debug them. So I would like to understand one thing at a time.

Of course it's not so simple because I can't test it directly :(

**Comment by firetrappe** [comment] 2020-11-08 20:13
It's all good. I think I have figured out how bisect works. It shouldn't take too long to test. They may all fail, but we won't know until we try.

**Comment by cagnulein** [comment] 2020-11-08 20:19
> It's all good. I think I have figured out how bisect works. It shouldn't take too long to test. They may all fail, but we won't know until we try.

Of course, remberber at every bisect to run a make ;)

**Comment by firetrappe** [comment] 2020-11-10 01:49
Ok, I finally got around to using bisect.

The latest commit and the original commit didn't work - the bridge connected, resistance displayed but not speed.
However, one of the attempts did work:

![PXL_20201110_011520486 (Phone)](https://user-images.githubusercontent.com/66125348/98616699-3f581080-22f5-11eb-8e8c-9104761987c2.jpg)
Photo was taken at 01:15 (yes, it was a late night! lol)

None of the following attempts were successful. This was the final result:

![Capture](https://user-images.githubusercontent.com/66125348/98616790-6e6e8200-22f5-11eb-8b7e-4624c5f405eb.PNG)

Here are the logs:

[debug-Tue Nov 10 01-04-24 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5514230/debug-Tue.Nov.10.01-04-24.2020.log)
[debug-Tue Nov 10 01-11-12 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5514231/debug-Tue.Nov.10.01-11-12.2020.log)
[debug-Tue Nov 10 01-18-45 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5514226/debug-Tue.Nov.10.01-18-45.2020.log)
[debug-Tue Nov 10 01-22-02 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5514227/debug-Tue.Nov.10.01-22-02.2020.log)
[debug-Tue Nov 10 01-24-35 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5514228/debug-Tue.Nov.10.01-24-35.2020.log)
[debug-Tue Nov 10 01-27-05 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5514229/debug-Tue.Nov.10.01-27-05.2020.log)

**Comment by cagnulein** [comment] 2020-11-10 06:53
thanks @firetrappe for your work, i feel guilty about it :(
few questions:

1. when you said "The latest commit and the original commit didn't work - the bridge connected, resistance displayed but not speed." displayed where? on bike or zwift?
2. which is the log that it works? this one debug-Tue Nov 10 01-11-12 2020.log ? IT IS VERY IMPORTANT BECAUSE I can diff the log and check
3. when you said "None of the following attempts were successful. This was the final result:" so you didn't find any commits that really works. I mean, there is always a unstable condition, isn't it? So the very first time you tried you were lucky, i guess, do you agree?

**Comment by firetrappe** [comment] 2020-11-10 07:39
> thanks @firetrappe for your work, i feel guilty about it :(
No need to feel guilty lol. This is what beta testing is all about. I'm very stubborn, I don't give up easily 😄 

> few questions:
> 
> 1. when you said "The latest commit and the original commit didn't work - the bridge connected, resistance displayed but not speed." displayed where? on bike or zwift?

My test method was to start the bridge using each commit. Then just use the GUI on the bridge to see if any speed was detected. When speed was detected then I loaded Zwift on the iPad to test. On every commit the bridge displays resistance changes when I change them manually on the bike.

> 2. which is the log that it works? this one debug-Tue Nov 10 01-11-12 2020.log ? IT IS VERY IMPORTANT BECAUSE I can diff the log and check

Yes, that is the one. I wasn't sure which is why I checked the timestamp of the photo. That is also the biggest log, the bridge ran for longer because I tested with zwift once I saw speed updating in the bridge GUI

> 3. when you said "None of the following attempts were successful. This was the final result:" so you didn't find any commits that really works. I mean, there is always a unstable condition, isn't it? So the very first time you tried you were lucky, i guess, do you agree?

None of the other commits (offered by bisect) that I tested detected speed changes in the bridge GUI.

**Comment by cagnulein** [comment] 2020-11-10 09:34
@firetrappe i guess i have good news! i guess i solved your issue. Please pull it and test it and send me the log. I've done something really invasive: so if i missed something, i need to check the log.

The idea comes from your last night logs, so they were super useful!

**Comment by firetrappe** [comment] 2020-11-10 10:21
> @firetrappe i guess i have good news! i guess i solved your issue. Please pull it and test it and send me the log. I've done something really invasive: so if i missed something, i need to check the log.
> 
> The idea comes from your last night logs, so they were super useful!

@cagnulein This sounds promising! Unfortunately I am at work for another 6 hours so I can't test until I get home :cry: 

I'm glad the bisect logs were useful. I'm curious as to what the difference was.
I'm so glad you spotted something different anyway.  

I'm crossing everything for both of us! :crossed_fingers:

**Comment by cagnulein** [comment] 2020-11-10 10:35
> I'm curious as to what the difference was

the difference is about timings. But look it deeper i found that i should wait for a bike bluetooth event on init phase. So i tried to synchronize with that event. The same event is avaiable on my treadmill, so i tested and it works (but my TM works even without this event).

**Comment by firetrappe** [comment] 2020-11-10 11:01
That's really interesting. We thought it was probably to do with timings, that makes sense.

Hopefully this may fix some issues with other peoples equipment too.

I noticed last night that the console on my bike has a switch on the back to choose between Rowing Machine, Elliptical or Bike. Maybe Domyos use the same console on other types of product?

By the way, knowing your skills and where you live, if you don't work for Ferrari then you should! :wink:

**Comment by cagnulein** [comment] 2020-11-10 11:13
> That's really interesting. We thought it was probably to do with timings, that makes sense.

i had always this feeling too, but i didn't have the evidences until this morning! (thanks again :) )
 
> Hopefully this may fix some issues with other peoples equipment too.

i hope so!

> I noticed last night that the console on my bike has a switch on the back to choose between Rowing Machine, Elliptical or Bike. Maybe Domyos use the same console on other types of product?

absolutely! Infact, the treadmill and bike from domyos has more or less the same protocol, and it has sense.

> By the way, knowing your skills and where you live, if you don't work for Ferrari then you should! 😉

hahaha in this very moment i would like to stay away from Ferrari 😆 

I really hope that this commit makes the difference for you ;)

**Comment by firetrappe** [comment] 2020-11-10 17:29
@cagnulein I just got home and tested...
Android and Linux versions both appear to work with the bike! 🎉 🚀 

I need to test further after I have eaten dinner, but I think you have cracked it 🎆

**Comment by cagnulein** [comment] 2020-11-10 19:06
@firetrappe we will have a beer together one of these days! Great!

**Comment by firetrappe** [comment] 2020-11-11 09:37
> @firetrappe we will have a beer together one of these days! Great!

Sounds like a plan my friend. I'll have to pop over, we can have a little 5k race around Fiarano :smile:

**Comment by cagnulein** [comment] 2020-11-18 10:33
everything ok @firetrappe ? could we close this issue?

**Comment by cagnulein** [comment] 2020-12-03 10:50
@firetrappe is everything allright? i'm starting to worry about you

**Comment by cagnulein** [comment] 2020-12-14 07:26
@firetrappe i'm closing this one. if you have any issue, feel free to reopen it!

**Closed** 2020-12-14 07:26 UTC
Labels: bike 500, domyos cyclette
