### ISSUE TITLE
[BUG] Renpho AI bike lacking any change in resistance when inclination changes or when power-ups are used in Zwift

### ISSUE THREAD

**Issue by kubrick101** [cagnulein/qdomyos-zwift#1712] opened 2023-10-18 14:19 UTC
**Describe the bug**
In Zwift, while biking, using the power-ups does not have any noticeable effects on the resistance nor does the change in inclination.

One thing I did adjust that could be problematic was this variable: "bike_resistance_offset" QVariant(QString, "60"). 

I did this so I could get the max power out of the gear resistance, but I'm not sure if that could effect the inclination resistance. Let me know.

**Smartphone (please complete the following information):**
 - Device: Galaxy S21 
 - OS: Android 13

**Append a debug log**

I am attempting to append the debug log, but apparently it is 39MB large and won't allow anything over 25MB. 
I have truncated the file instead and kept in the seemingly more relevant beginning of the file..

[debug-Tue_Oct_17_15_05_02_2023-truncated.log](https://github.com/cagnulein/qdomyos-zwift/files/13029638/debug-Tue_Oct_17_15_05_02_2023-truncated.log)

**Comment by cagnulein** [comment] 2023-10-18 14:27
@kubrick101 hi! Powerups doesn't have any effects on the bike for ANY bike. The powerups runs on the server side and they simply put your avatar faster.

Beside of the powerups, which issue do you have?
For the log you can simply zip it before sending it here.
Let me know!

**Comment by kubrick101** [comment] 2023-10-18 14:56
Ok, thanks for letting me know about the power-ups. The main issue for me is that the change in route inclination in Zwift does not change the resistance on my bike. Whether I am going uphill or downhill, the resistance is always the same. Here is the zipped log file.
[debug-Tue_Oct_17_15_05_02_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/13030170/debug-Tue_Oct_17_15_05_02_2023.zip)

**Comment by cagnulein** [comment] 2023-10-18 15:10
log checked @kubrick101 

for the renpho bike, when you're on zwift, QZ is acting like a pass trough: since your bike is already capable to handle the Zwift messages, qz is sending the zwift messages directly to your bike.

In your log I see this behaviour correctly and I also see the answer from your bike.

So it seems that your bike acknowledge the qz request but it doesn't apply.

In order to go deeper can you try to connect the bike directly on zwift? do you feel the resistance changing in that way?
other test: with zwift disconnected, can you try to press the plus button of the reistance tile of qz? do you feel any changes?

let me know

**Comment by kubrick101** [comment] 2023-10-18 15:24
Yes, for sure when I connect directly to Zwift with the bike there are significant adjustments in resistance when I hit different inclinations.

When I try just using QZ on its own and hit the plus or minus sign on Resistance or Peloton R(%) tiles, nothing happens. I can't make the numbers go up or down. The only Resistance tile that I can change is the Target R... but it has no effect on the resistance amounts I am feeling on the bike.

**Comment by cagnulein** [comment] 2023-10-18 15:48
ok i will check again tomorrow (evening here in italy) and i will let you
know

Il giorno mer 18 ott 2023 alle 17:24 kubrick101 ***@***.***>
ha scritto:

**Comment by kubrick101** [comment] 2023-10-18 18:26
No problem. In the meantime, here are all the things I tested to see if there would ever be a change in resistance whenever the Zwift gradient would change. Note, I always restarted the app on any change to be sure and also was forced to keep reconnecting to Zwift. Also, Zwift does show that I am connected to all three sensors (Power, Cadence and Resistance).

1) Set the Trainer difficulty level to MAX in Zwift so it would be very noticeable when a change would occur.
2) Set the Double Negative Inclination toggle to on and off
3) In Bike options I tried adjusting the Zwift Resistance Offset from 4, to 20, to 60.
4) In the Renpho Bike Options I tried toggling the Use 0.5 resistance lvls, but nothing changed. Also tried toggling the New Peloton formula, but nothing changed.

For all of the above, I would also test with toggling the Auto resistance on and off in QZ as well, but unfortunately nothing seemed to cause any change in resistance.
The only time the resistance value would change in the QZ tiles is when I would change gears on the Renpho bike dial. The plus/minus buttons on the tile don't cause any changes.

So that is everything I have tried today. Thanks for your help.

**Comment by kubrick101** [comment] 2023-10-19 12:49
Do you mean that when I start Zwift I need to NOT connect to my phone in both the Cadence and Power in the Zwift app and just connect the Resistance to the phone? Or is there something in the QZ app you want me to disconnect?

**Comment by cagnulein** [comment] 2023-10-19 13:08
nope in qz directly, settings, accessories

**Comment by kubrick101** [comment] 2023-10-19 14:09
There are quite a few settings in the list... so I'm not sure which you want me to toggle or disable. Here is a screenshot of how it currently looks. Is it simply a question of unselecting RQ002 from the dropdown list? Or do I need to toggle any of the slide buttons above it?
![Screenshot_20231019_100341](https://github.com/cagnulein/qdomyos-zwift/assets/148276388/17a63876-4c41-4307-8526-de6c4ece16fe)

**Comment by cagnulein** [comment] 2023-10-19 14:11
power sensor and cadence sensor that are now on RQ002 must be set to "Disabled" and press ok on both and restart QZ

**Comment by kubrick101** [comment] 2023-10-19 15:07
So did some testing and the moment I disable the power sensor in QZ, Zwift no longer receives a power signal, nor does the QZ app... the Watts remain at zero in both QZ and Zwift. However, Zwift and QZ can pick up the cadence even when the sensor is disabled. Since there was no power being received I couldn't move the avatar to see if the resistance had been fixed. I also tested it with the power sensor back on and cadence off, but it did not fix the resistance issue. 

FYI, I tried disconnecting and reconnecting multiple times to Zwift just to see if anything would change... still the same result. Attached are some logs. Thanks again.
[debug-list.zip](https://github.com/cagnulein/qdomyos-zwift/files/13044328/debug-list.zip)

**Comment by kubrick101** [comment] 2023-10-19 15:35
Yes, exactly. The big number stays at zero, but the small numbers beneath do seem to change as I peddle. Also the average watts tile big number DOES change as well as I peddle. The issue only seems to be that Zwift does not receive the signal, yet it does receive the cadence.

**Comment by cagnulein** [comment] 2023-10-19 15:36
yeah the problem is the big watt number. I'm investigating, it must be a stupid issue but I have to find it :)

**Comment by cagnulein** [comment] 2023-10-19 15:48
I'm still looking the log, in the meantime, could you please join the beta
from the play store page of QZ and check if the problem is the same with
the better version? Thanks.

Il giorno gio 19 ott 2023 alle 17:35 kubrick101 ***@***.***>
ha scritto:

**Comment by kubrick101** [comment] 2023-10-19 15:51
Will do. I'll let you know if beta works better. Thanks again for your incredible support.

**Comment by kubrick101** [comment] 2023-10-19 18:57
Ok, I got the beta version and did some testing. What it comes down to is that resistance still isn't effected by the grade in Zwift.
I have to make sure that my RQ002 bike is selected in the FTMS Bike section in order for QZ to recognize the power. If I don't select any bike, power is not recognized. Once I do select the bike in that dropdown, I am able to disable power and cadence in the accessories section and still get proper power levels showing up in QZ and Zwift... but resistance doesn't change in game still..
[debug-Thu_Oct_19_14_45_53_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/13046646/debug-Thu_Oct_19_14_45_53_2023.zip)

**Comment by cagnulein** [comment] 2023-10-19 19:20
nope please don't select it in ftms bike. renpho is a different profile.
just leave all the settings disabled, also can you clear the data of the
app so you will turn back everything to default and, without changing any
settings, try again?
I'm going to bed now, i will check the log tomorrow
thanks

Il giorno gio 19 ott 2023 alle 20:57 kubrick101 ***@***.***>
ha scritto:

**Comment by kubrick101** [comment] 2023-10-19 20:43
Yes, that is what I initially tried. Kept everything at default with all the options turned off or disabled, but as soon as I do that no Watts are registered in QZ or Zwift (only the small numbers change in QZ watts Tile). Just tried clearing the cache and setting everything to default again, but same issue. Cadence shows up fine, but not Watts. Thanks again.

**Comment by cagnulein** [comment] 2023-10-20 04:24
ok thanks again for the test. i will check it again

Il giorno gio 19 ott 2023 alle 22:43 kubrick101 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment] 2023-10-20 06:24
@kubrick101 I guess I understood your issue. Could you please disable also the speed based on power setting and try again? if it still doesn't work could you send me a fresh log in this scenario?
Thanks!

**Comment by kubrick101** [comment] 2023-10-20 15:36
So this worked, Roberto! The resistance now DOES change based on gradient change in game... however, this has returned me back to the gear power problem, which is why I purchased your app to fix. Basically, the default behavior with Zwift and Renpho (without QZ) is that the max gears are 20 and even at gear 20, it doesn't allow for much power in the game. I can peddle at my max cadence and maybe I'll reach 350 watts... this is now occurring with QZ app as well.

But when I first started using your app it wasn't using the gear system anymore (when using the old settings we initially started with)... I could increment the "gear power" up in 0.5 intervals all the way up to 40, which gave exceptional resistance and much more power availability.

Is there any way we can keep all these working settings but add in that "40" power possibility as well? Not sure if this makes much sense for you though...

**Comment by cagnulein** [comment] 2023-10-20 16:14
great! @kubrick101 are you talking about erg session or free ride session? on erg mode i already handle the gears, instead on free rides no, but i can add it easily!

Let me know

**Comment by kubrick101** [comment] 2023-10-20 16:19
Yes, I am talking about free rides and races. That would be wonderful if you could add it back in. Then all will be working exactly as I had hoped for. Thanks again!

**Comment by cagnulein** [comment] 2023-10-20 16:20
Sure thing. I will try to do in these days!
I will let you know when I will be ready!

Il giorno ven 20 ott 2023 alle 18:19 kubrick101 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment] 2023-10-21 12:22
Modification done! It will be in the 2.16.19, I'm uploading it now, you
will see it in the store in the next hours. let me know if something will
not work!
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 20 ott 2023 alle ore 18:20 cagnulein ***@***.***> ha
scritto:

**Comment by kubrick101** [comment] 2023-10-21 14:27
Thanks a lot Roberto. Exceptional support you give! I'm still waiting for the beta update to show up in Google Play. Will let you know how it goes once it's installed.

**Comment by cagnulein** [comment] 2023-10-21 17:08
should be out now

**Comment by kubrick101** [comment] 2023-10-22 13:55
It's still not showing up in Google Play for me... Still showing version 2.16.18 only...

**Comment by cagnulein** [comment] 2023-10-22 13:58
hah you're right, google is still reviewing. damn google, it's worst than
apple nowadays

Il giorno dom 22 ott 2023 alle 15:55 kubrick101 ***@***.***>
ha scritto:

**Comment by kubrick101** [comment] 2023-10-23 22:07
I did get the update, but it didn't seem to adjust the gears to the N-m possibilities... it remains in the 1 to 20 gear mode. I tried to see if there was anywhere new to select anything, but didn't find anything. Let me know if I missed something.
[debug-Mon_Oct_23_17_57_34_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13079547/debug-Mon_Oct_23_17_57_34_2023.log)

**Comment by cagnulein** [comment] 2023-10-24 09:13
probably I misunderstood your question here: what I did in this version is to use the gear tile (0 in the whole file) to override the zwift requests. You're obtaining the same as the N-m possibilites. Give it a try and if you are not satisfied I will do also the N-m thing (a bit more complicated since I don't have to forward the zwift frames as I do now, but I have to control power directly)

let me know

**Comment by cagnulein** [comment] 2023-10-24 14:36
yes exaclty! Let me know

**Comment by cagnulein** [comment] 2023-10-24 14:37
you can also link a bluetooth remote to qz and changing the gears from it!

**Comment by kubrick101** [comment] 2023-10-24 14:41
But there is no way to link the gear dial on the Renpho bike to QZ?

**Comment by cagnulein** [comment] 2023-10-24 14:54
actually I did this for the echelon bike, so it should be possible. It's possible only if you see for a little moment, that the resistance tile on qz is changing when you turn the knob. if it's so, yes I can use that event to change the gears :)

**Comment by kubrick101** [comment] 2023-10-24 15:14
I just tested it out and there seem to be some problems. First, when I adjust the Gears on the QZ tile there is no change in response on the bike. Also, it seems like the resistance to gradient changes is no longer working either now... very strange.

And yes, when I change the dial on the Renpho bike, the resistance tile in QZ changes accordingly.
[debug-Tue_Oct_24_11_03_12_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13120074/debug-Tue_Oct_24_11_03_12_2023.log)

**Comment by cagnulein** [comment] 2023-10-24 15:33
the problem is that you disabled auto resistance. did you do to check the
dial thing?

Il giorno mar 24 ott 2023 alle 17:14 kubrick101 ***@***.***>
ha scritto:

**Comment by kubrick101** [comment] 2023-10-24 16:01
Sorry about that. I hadn't noticed... my finger must have hit it accidentally. So after fixing that it seems like things work for the most part. The gear tile does change resistance, but doesn't seem consistent. Sometimes I have to adjust the dial on the bike for the resistance to change... it's a bit confusing how it's working. It does seem to give me more power and resistance than regular Zwift connection gives though. Thank you for your time with all this.

**Comment by cagnulein** [comment] 2023-10-24 16:05
qz is forcing to higher/lower hill to the bike. share me a debug log so i
can check if the implementation is correct.
also, the current implementation, force it only when a new gradient has
been received from zwift. if you want i can put it immediately.
Let me know

Il giorno mar 24 ott 2023 alle 18:01 kubrick101 ***@***.***>
ha scritto:

**Comment by kubrick101** [comment] 2023-10-24 16:21
Here is the debug log. 
[debug-Tue_Oct_24_11_48_01_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/13120996/debug-Tue_Oct_24_11_48_01_2023.zip)

**Comment by cagnulein** [comment] 2023-10-24 16:29
thanks I will check it tomorrow.

for what I saw the patch is working as expected: when a new hill gradient has been received from zwift, i'm applying the gear value so for example a -3% gradient is transformed on a +2.5% and so this should be handled by your bike increasing the resistance 

you can check better this increasing the gear value a lot so it should be very visible 

remember that the mod is applied, for now, only when a new gradient has been received

**Comment by kubrick101** [comment] 2023-10-24 17:54
Hmmm.. not sure I really understand what's happening internally. If there is a -3% grade, shouldn't the resistance drop instead of increase by +2.5 if I am understanding correctly what you are saying?

It just seems with this new update, there is some conflicts happening when it comes to the gear power/resistance changes when I + or - it on the tile. The fact that the dial on the Renpho bike can somehow trigger the change as well when it's not kicking in on QZ is odd too. And then I think the gradient change adds another layer of complexity to the gear resistance/power dynamics. I will try more testing though later today. Thanks again.

**Comment by cagnulein** [comment] 2023-10-24 18:00
> Hmmm.. not sure I really understand what's happening internally. If there is a -3% grade, shouldn't the resistance drop instead of increase by +2.5 if I am understanding correctly what you are saying?

yes i mean without gears, if you go from 0% to -2% the resistance will decrease. Good. now if you set the gears for example to 10, i'm expecting that the hill will become a 4% instead of -2% (each gear is a 0.5% increment). is it better now?

also don't change the knob for now, it will create an expected behavior with the actual version

**Closed** 2023-11-15 23:48 UTC
Labels: bug, wontfix

**Comment by cagnulein** [comment] 2023-11-16 07:14
@kubrick101 are we ok with this?

**Comment by kubrick101** [comment] 2023-11-16 15:04
Yeah, sorry for the delay. I feel like it's become too difficult to change the gears easily during a race with the QZ app + or - buttons... I will continue to use the app in it's default mode where I can use the Renpho dial to change the gears and just not have the inclination resistance changing as I go. It will allow me to get to the higher gears still but the hills will just act like flat land... I appreciate the effort you made though. Thanks again.

**Comment by cagnulein** [comment] 2023-11-16 15:05
> during a race with the QZ app + or - buttons..

do you know that you can pair a bluetooth remote to your phone and use that one to change the gears on qz already?

**Comment by kubrick101** [comment] 2023-11-16 15:15
Maybe something that can help is to have an option that allows me to set the increment values to more than 0.5 or 1, so that I could jump gears quicker?
