### ISSUE TITLE
[REQ] Calroies in Apple Fitness App.

### ISSUE THREAD

**Issue by anseok83** [cagnulein/qdomyos-zwift#302] opened 2021-05-06 23:57 UTC
Thank you for your great project QZ and appreciate that I really enjoying the project.

This is just simple and think you may know already. If not, please notice the following.

**Is your feature request related to a problem? Please describe.**

I'm running QZ on my iphone with apple watch. With QZ watchkit, heart rate tracking works perfect.

However, workout calroies are not shown correctly in Apple Fitness App. It just shows 0KCAL as seen in the captured image.
![IMG_0410](https://user-images.githubusercontent.com/7554736/117379116-b7ed0200-af11-11eb-8b49-0b823b0e8231.jpeg)

**Describe the solution you'd like**

Just simple calculation of workout calories and sync with Apple Fitness app will be great.

**Comment by cagnulein** [comment] 2021-05-07 04:24
Yes it's already in the Todo list :)

**Comment by cagnulein** [comment] 2021-05-10 08:44
#72

**Comment by cagnulein** [comment] 2021-05-12 12:39
it will be in the 2.6.28

**Closed by cagnulein** 2021-05-12 12:39 UTC
Labels: enhancement

**Comment by anseok83** [comment] 2021-05-19 14:29
Good to hear that. Wait for that version!

**Comment by cagnulein** [comment] 2021-05-19 14:37
the beta is already available. Are you in the beta group? If not send me a
mail to roberto.viola83 At gmail.com

Il mer 19 mag 2021, 16:29 ans ***@***.***> ha scritto:

**Comment by anseok83** [comment] 2021-05-25 00:46
Hi, i'm in the test group of beta 2.6.30.

Calrories and distance of QZ workouts is appearing in the Apple Fitness now. 

One weird thing to report is that the listing of workouts in the Apple Fitness since workouts have some delay. For instance, a workout have been done in Sunday morning is shown in the app now (Tuesday morning), but a workout have been done in yesterday (Monday) evening is not shown yet.

Do you have any idea on that?

**Comment by cagnulein** [comment] 2021-05-25 04:34
I have no control on it. When you press stop on the watch i write it
immediately :(
In the apple watch simulator i saw it immediately :(
But also another user reports me this.
Other workout apps have the same behavior?

Il mar 25 mag 2021, 02:46 ans ***@***.***> ha scritto:

**Comment by anseok83** [comment] 2021-05-25 13:51
I think other workout apps I've used (Nike Run Club, Sports tracker, moov, ...) haven't that kind of behavior, reports were immediately listed in the fitness app after workout.

Now, the riding yesterday (monday) evening is shown in the fitness app. Roughly around of one day of delay I guess.

**Comment by cagnulein** [comment] 2021-05-25 17:48
Ok i will check with other users if the issue is common to others

Il mar 25 mag 2021, 15:52 ans ***@***.***> ha scritto:
