### ISSUE TITLE
Synology - docker

### ISSUE THREAD

**Issue by mitchoklemen** [cagnulein/qdomyos-zwift#54] opened 2020-11-09 14:09 UTC
Hi,

Can you make a Docker image, to run it on Synology?

Thank you for effort, Mitcho

**Comment by cagnulein** [comment] 2020-11-09 14:19
@mitchoklemen welcome aboard!
what about the bluetooth? how could you provide the bluetooth to synology? usb dongle?

just for the stats: which machinery do you have? is it already working?

**Comment by mitchoklemen** [comment] 2020-11-09 14:28
I thought USB dongle yes. which do you preffer?
I have T900. I didnt run it yet.

**Comment by cagnulein** [comment] 2020-11-09 14:37
@mitchoklemen first of all it's better to test the bridge on a PC/Mac/Raspberry in order to understand if your dongle works.
@rickoneeleven has a lot of trouble with dongles...

check also #13 if you didn't

i'm here to help you in order to setup it! 👍

**Comment by cagnulein** [comment] 2020-11-09 14:38
@mitchoklemen i guess, if you have a PC, the easy way is to test with #39

**Comment by mitchoklemen** [comment] 2020-11-09 14:43
OK I'll try that!

**Comment by mitchoklemen** [comment] 2020-11-11 19:23
In virtualBox I get Error Failed to attach the USB device Apple Bluetooth Host Controller 0156.
Callee RC: NS_Error_Failure (0x80004005)
Macbook Pro late 2012.

I tried also with some generic USB bluetooth dongle but Error said that device is used by another app.

**Comment by cagnulein** [comment] 2020-11-11 20:05
@mitchoklemen on macOs you don't need the virtual box. On macOs it runs natively. You can compile my code on Qt Creator and run it disabling the mac bluetooth and using the dongle one.

**Comment by rickoneeleven** [comment] 2020-11-11 20:11
@mitchoklemen i had that issue on windows, i managed to get it working intermittently by turning bluetooth off on the PC itself, then trying to attach the interface to the VM, if that failed, sometimes switching the bluetooth back on and then trying managed to attach it. Very hit and miss.

**Comment by cagnulein** [comment] 2020-11-18 10:32
any news @mitchoklemen ?

**Comment by mitchoklemen** [comment] 2020-11-19 12:40
In virtualBox I cant get it through with my Bluetooth dongle. Always get Error with it. Like in Windows like in OsX.
I didnt try the native MacOS yet, but I will soon. I'll report then.
I also have androidTV box with Android 10 and bluetooth on it? I Installed APK but it's little tall for my format. I didnt try to connect it yet. I'll try it probably today when I come from work.
Thanx for support.

**Comment by cagnulein** [comment] 2020-11-19 12:46
@mitchoklemen ok, the behaviour of the dongle is very strange, but i just tested only my Dell's bluetooth dongle, so i don't have a wide knowledge of bluetooth's dongle.
On MacOS i'm quite sure that every works: my GF uses it everyday on my MacBook Air.
Android TV should work, i'm working right now on a UI for mobile: probably i need some days to set it up. After this i will publish it on the play store.
Thanks for debugging it!

**Comment by cagnulein** [comment] 2020-12-03 16:00
@mitchoklemen any news?

**Comment by mitchoklemen** [comment] 2020-12-04 06:25
Sorry didnt have time to test... I'll try this weekend. Will report!

**Comment by mitchoklemen** [comment] 2020-12-06 17:30
[debug-Sun Dec 6 14_50_52 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5649212/debug-Sun.Dec.6.14_50_52.2020.log)

There is debug file from my Android 10 TVbox. Old version was ok most of times. With new one 1.1.0 I have problem connecting. It starts treadmill by it self, cant operate with buttons, fan works but only to +.

**Comment by cagnulein** [comment] 2020-12-06 18:38
hi @mitchoklemen i don't see any issue in your log. the treadmill is well connected. did you try to clean the app (remove data and cache)? did you try the last version avaiable https://github.com/cagnulein/qdomyos-zwift/files/5648950/android-1.4.0.zip ?

the last one you tried is this one https://github.com/cagnulein/qdomyos-zwift/issues/51#issuecomment-731965289 ?

**Comment by mitchoklemen** [comment] 2020-12-08 18:05
I installed 1.4.0. Can you look LOG file for errors?
[debug-Mon Dec 7 19_36_25 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5660920/debug-Mon.Dec.7.19_36_25.2020.log)

**Comment by cagnulein** [comment] 2020-12-08 18:22
> I installed 1.4.0. Can you look LOG file for errors?
> [debug-Mon Dec 7 19_36_25 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5660920/debug-Mon.Dec.7.19_36_25.2020.log)
> 

Yes the treadmill stop to answering back after 20 seconds from the startup. Maybe it's when you try to connect with Zwift? Did you clean the app data as i suggested? It's very strange

**Comment by cagnulein** [comment] 2020-12-08 18:30
Could you try also this version again? https://github.com/cagnulein/qdomyos-zwift/files/5581370/android-build-debug.zip it's the first one you tried. I would like to be sure that this one works for you so I can check the differences

**Comment by mitchoklemen** [comment] 2020-12-09 09:17
Yes I cleaned the data. I'll try with first ver. and report.

**Comment by cagnulein** [comment] 2020-12-10 09:40
@rickoneeleven which commit are you using now? just to give a @mitchoklemen a hand, @rickoneeleven  could you try to use the last commit?
i would like to see if i hadn't put a regression, because another user on facebook alerts me about the same @mitchoklemen issue on T900C.
thanks

**Comment by rickoneeleven** [comment] 2020-12-10 09:50
I'm using commit d5424a38fac9c20498c3170f8e3830ea95955735

I'll compile latest version tonight and give it a go

**Comment by cagnulein** [comment] 2020-12-10 09:53
ok thanks @rickoneeleven . any chance to give a try to the android version too? just to understand if the @mitchoklemen issue is only on android and if you see it too only on android. thanks

**Comment by rickoneeleven** [comment] 2020-12-10 09:55
the andrio version never worked for me, bridge wouldn't show up in zwift

**Comment by cagnulein** [comment] 2020-12-10 10:00
@rickoneeleven yes because in the first versions i didn't manage the heart service correctly. In the new android version i can't share the heart rate service as i did to linux or older android version. In the https://github.com/cagnulein/qdomyos-zwift/files/5648950/android-1.4.0.zip i managed and it should work. There is also a setting to play with it if not works. Anyway i'm interested in the connection with the treadmill, zwift comes after

**Comment by rickoneeleven** [comment] 2020-12-10 10:02
i'll try the latest commit tonight, and take a look at android tomorrow or Saturday :+1:

**Comment by rickoneeleven** [comment] 2020-12-10 18:13
just had a full session with 235748cd680cd2a4bb4c76df3a4950038cb4408e - zero segfaults (or if there were any, i never noticed them), so doesn't look you've introduced any issues

**Comment by cagnulein** [comment] 2020-12-10 18:47
Ok, so i guess it's an android issue. Thanks

**Comment by cagnulein** [comment] 2020-12-10 21:57
ok i've uploaded the new commit about synchronizing event on domyostreadmill. Tomorrow i will build it for android too and i would like if @mitchoklemen will try it.
have a good night guys!

**Comment by cagnulein** [comment] 2020-12-11 07:36
@mitchoklemen @rickoneeleven could you please test this version? send me the logs at the end, thanks.
http://80.211.67.253:8080/android-build-1.5.1.zip

**Comment by rickoneeleven** [comment] 2020-12-11 07:38
what should I do to test? usually I do a run on zwift but if the bridge bit possibly doesn't work yet, what do you want me to do, just see if it connects to treadmill?

**Comment by cagnulein** [comment] 2020-12-11 07:41
yes @rickoneeleven , anyway, as i said before, with this version zwift should work. you have only to play with the heart rate setting (try it with on or off). 

But a quick connection test to the treadmill is enough (try to change the speed, start and stop command...)

**Comment by mitchoklemen** [comment] 2020-12-11 16:18
Logs...
I still have problem with it... at start its ok, then buttons just wont change the speed or inclinacion (like freez) 

[debug-Fri Dec 11 16_51_26 2020 (1).log](https://github.com/cagnulein/qdomyos-zwift/files/5680282/debug-Fri.Dec.11.16_51_26.2020.1.log)
[debug-Fri Dec 11 16_55_53 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5680284/debug-Fri.Dec.11.16_55_53.2020.log)
[debug-Fri Dec 11 16_58_16 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5680285/debug-Fri.Dec.11.16_58_16.2020.log)
[debug-Fri Dec 11 17_00_39 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5680286/debug-Fri.Dec.11.17_00_39.2020.log)
[debug-Fri Dec 11 17_04_09 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5680287/debug-Fri.Dec.11.17_04_09.2020.log)

**Comment by cagnulein** [comment] 2020-12-11 19:43
@mitchoklemen in the log I saw version 1.4.8 are you sure you use version 1.5.1 that i have linked above?
Thanks!

**Comment by mitchoklemen** [comment] 2020-12-11 20:04
sure! I dont have any onther than 1.5.1 and older 1.4.

**Comment by cagnulein** [comment] 2020-12-11 20:22
No i guess i didn't explain me well. You are using the version 1.4.8
I guess the installation of the 1.5.1 didn't go well. Could you please
double check it?
Thanks

Il ven 11 dic 2020, 21:04 mitchoklemen <notifications@github.com> ha
scritto:

**Comment by cagnulein** [comment] 2020-12-12 07:31
@mitchoklemen sorry, my fault. i uploaded a wrong file. please try again with this http://80.211.67.253:8080/android-build-1.5.1a.zip

**Comment by rickoneeleven** [comment] 2020-12-12 11:47
okay using that version, it has connected to my treadmill and zwift. it's running now in my garage (where the treadmill is). i increased and decreased the speed using the buttons on my treadmill and that successfull sped up and slowed down on zwift, do you need me to test anything else?

**Comment by cagnulein** [comment] 2020-12-12 11:50
Great! So this version is running on android! Well! @mitchoklemen i need a confirm from you now. Because if it doesn't work to you I guess it's something in your setup that we have to understand.

@rickoneeleven just as reference, could you please attach here the log available on your download folder on android?

Thanks

**Comment by rickoneeleven** [comment] 2020-12-12 11:58
yes https://photos.app.goo.gl/FAcW5qPZigBEPgnNA log to follow

**Comment by rickoneeleven** [comment] 2020-12-12 12:02
log 
[debug-Sat Dec 12 11_44_08 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5683025/debug-Sat.Dec.12.11_44_08.2020.log)

**Comment by mitchoklemen** [comment] 2020-12-12 16:49
OK now it is 1.5.1. when I tap fan it stuck. 
[debug-Sat Dec 12 17_32_35 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5683448/debug-Sat.Dec.12.17_32_35.2020.log)
[debug-Sat Dec 12 17_30_17 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5683449/debug-Sat.Dec.12.17_30_17.2020.log)
[debug-Sat Dec 12 17_28_36 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5683450/debug-Sat.Dec.12.17_28_36.2020.log)
[debug-Sat Dec 12 17_27_53 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5683451/debug-Sat.Dec.12.17_27_53.2020.log)
[debug-Sat Dec 12 17_34_09 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5683452/debug-Sat.Dec.12.17_34_09.2020.log)
[debug-Sat Dec 12 17_00_34 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5683453/debug-Sat.Dec.12.17_00_34.2020.log)

**Comment by cagnulein** [comment] 2020-12-12 17:20
thanks @mitchoklemen this time is very clear on the logs! if you don't touch the fan does it work well? i'm trying to understand and solving the fan issue

**Comment by cagnulein** [comment] 2020-12-12 17:48
@mitchoklemen finally solved the fan issue too http://80.211.67.253:8080/android-build-1.5.2.zip !! give me a confirmation, please :)

**Comment by mitchoklemen** [comment] 2020-12-12 19:02
Yihaaa, Everything works! 👍👏
One strange thing only... I didnt find the LOG file in Downloads... date and time wasn't right... I checked the system date and its OK. One question more... on the treadmill, the run time stops (was 13:41) or is not synced with Zwift... can you look at it?

[debug-Fri Nov 6 14_23_44 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5683605/debug-Fri.Nov.6.14_23_44.2020.log)

**Comment by cagnulein** [comment] 2020-12-12 19:51
Do you want to know what problem is about the time? Check better the logs, the datetime has synced during the workout, so at one moment, instantly the date passed from 6th November to today :D and of course everything based on time was shit :D

So i guess it's a no-problem ;)

**Comment by cagnulein** [comment] 2020-12-12 19:51
If you are ok, we can close this one ;)

**Comment by mitchoklemen** [comment] 2020-12-12 20:34
sure! Bravo to you and thanx for get us great link ... to Zwift

**Closed** 2020-12-12 20:42 UTC
Labels: docker
